// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class HrLeaveTypeCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class HrLeaveTypeGetAllocationDataRequestDto
    {
        public object Employees { get; set; }
        public object Date { get; set; }
    }
    
    public class HrLeaveTypeGetAllocationDataRequestRequestDto
    {
        public object TargetDate { get; set; }
        public object HiddenAllocations { get; set; }
    }
}