using Volo.Abp.Domain.Entities;
using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Domain.Shared.Interfaces;
using Bamboo.Core.Application.Contracts.Interfaces.Mixins;
namespace Bamboo.Core.Application.Contracts.Interfaces.Mixins
{
    public interface IBaseAppService : IMixinAppService
    {
        Task<TEntity> AddGroupbyValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object groupby_read_specification, List<string> groupby, List<object> current_groups) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> AliasGetErrorInternalAsync<TEntity>(IEnumerable<TEntity> entities, object message, object message_dict, object @alias) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> CanReturnContentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field_name, object access_token) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> FindValueFromFieldPathInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field_path) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> FormatWebSearchReadResultsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object records, object offset, object limit, object count_limit) where TEntity : IEntity<Guid>, IBaseable;
        Task<List<Dictionary<string, object>>> FormattedReadGroupAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object groupby, object aggregates, object having, int offset, object limit, object order) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> FormattedReadGroupWithLengthInternalAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object groupby, object aggregates, object offset, object limit, object order) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> FormattedReadGroupingSetsAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object grouping_sets, object aggregates) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetAccessActionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object access_uid, object force_website) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetBackendRootMenuIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetBaseLangInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetBaseUrlAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultActivityViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultCalendarViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultFormViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultGraphViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultKanbanViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultListViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultPivotViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetDefaultSearchViewInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<string> GetEmptyListHelpAsync<TEntity>(IEnumerable<TEntity> entities, string help_message) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetFieldTranslationsAsync<TEntity>(IEnumerable<TEntity> entities, object field_name, object langs) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetFieldsSpecInternalAsync<TEntity>(IEnumerable<TEntity> entities, object view_info) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetFormviewActionAsync<TEntity>(IEnumerable<TEntity> entities, object access_uid) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetFormviewIdAsync<TEntity>(IEnumerable<TEntity> entities, object access_uid) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetHtmlLinkInternalAsync<TEntity>(IEnumerable<TEntity> entities, object title) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetImportTemplatesAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<string> GetReadGroupOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object dict_order, List<string> groupby, object aggregates) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetRecordsActionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewAsync<TEntity>(IEnumerable<TEntity> entities, Guid view_id, object view_type) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewCacheInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid view_id, object view_type) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewCacheKeyInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid view_id, object view_type) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewFieldAttributesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object view_type, object models) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid view_id, object view_type) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewPostprocessedInternalAsync<TEntity>(IEnumerable<TEntity> entities, object view, object arch) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetViewsAsync<TEntity>(IEnumerable<TEntity> entities, object views, object options) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> GetWebsiteMetaAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> HierarchyReadAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object specification, object parent_field, object child_field, object order) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailAllowedQwebExpressionsAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetAliasDomainsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object default_company) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetCompaniesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @default) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetCompanyFieldInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetCustomerInternalAsync<TEntity>(IEnumerable<TEntity> entities, object introspect_fields) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetMessageSubtypesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetOperationForMailMessageOperationInternalAsync<TEntity>(IEnumerable<TEntity> entities, object message_operation) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetPartnerFieldsAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetPartnerFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object introspect_fields) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetPartnersInternalAsync<TEntity>(IEnumerable<TEntity> entities, object introspect_fields) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetPrimaryEmailFieldInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetPrimaryEmailInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGetTimezoneInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailGroupByOperationForMailMessageOperationInternalAsync<TEntity>(IEnumerable<TEntity> entities, object message_operation) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailTrackGetFieldSequenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object fname) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailTrackInternalAsync<TEntity>(IEnumerable<TEntity> entities, object tracked_fields, object initial_values) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MailTrackOrderFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object tracked_fields) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MessageAddDefaultRecipientsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MessageAddSuggestedRecipientsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object force_primary_email) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MessageGetDefaultRecipientsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object with_cc, object all_tos) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MessageGetSuggestedRecipientsBatchInternalAsync<TEntity>(IEnumerable<TEntity> entities, object reply_discussion, object reply_message, object no_create, object primary_email, object additional_partners) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> MessageGetSuggestedRecipientsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object reply_discussion, object reply_message, object no_create, object primary_email, object additional_partners) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> NotifyByEmailGetHeadersInternalAsync<TEntity>(IEnumerable<TEntity> entities, object headers) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> NotifyGetReplyToBatchInternalAsync<TEntity>(IEnumerable<TEntity> entities, object defaults, List<Guid> author_ids) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> NotifyGetReplyToFormattedEmailInternalAsync<TEntity>(IEnumerable<TEntity> entities, object record_email, Guid author_id) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> NotifyGetReplyToInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @default, Guid author_id) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> OnchangeAsync<TEntity>(IEnumerable<TEntity> entities, Dictionary<string, object> values, List<string> field_names, Dictionary<string, object> fields_spec) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> OnchangeSpecInternalAsync<TEntity>(IEnumerable<TEntity> entities, object view_info) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> OpenGroupsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> PhoneFormatInternalAsync<TEntity>(IEnumerable<TEntity> entities, object fname, object number, object country, object force_format, object raise_exception) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> PhoneFormatNumberInternalAsync<TEntity>(IEnumerable<TEntity> entities, object number, object country, object force_format, object raise_exception) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> PhoneGetCountryFieldInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> PhoneGetCountryInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> PhoneGetNumberFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> ReadProgressBarAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object group_by, object progress_bar) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelDomainImageInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field_name, object domain, object set_count, object limit) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelFieldImageInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field_name) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelGlobalCountersInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values_range, object parent_name) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelSanitizedParentHierarchyInternalAsync<TEntity>(IEnumerable<TEntity> entities, object records, object parent_name, object ids) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelSelectMultiRangeAsync<TEntity>(IEnumerable<TEntity> entities, object field_name) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelSelectRangeAsync<TEntity>(IEnumerable<TEntity> entities, object field_name) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SearchPanelSelectionRangeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field_name) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SmsGetRecipientsInfoInternalAsync<TEntity>(IEnumerable<TEntity> entities, object force_field, object partner_fallback) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> SortSuggestedMessagesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object messages) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> UnlinkAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> ValidFieldParameterInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field, object name) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> ViewHeaderGetAsync<TEntity>(IEnumerable<TEntity> entities, Guid view_id, object view_type) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebNameSearchAsync<TEntity>(IEnumerable<TEntity> entities, object name, object specification, object domain, object @operator, object limit) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebOverrideTranslationsAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IBaseable;
        Task<List<Dictionary<string, object>>> WebReadAsync<TEntity>(IEnumerable<TEntity> entities, object specification) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebReadGroupAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object groupby, object aggregates, object limit, int offset, object order) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebReadGroupExpandInternalAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object groups, object groupby_spec, object aggregates, object order) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebReadGroupFieldExpandInternalAsync<TEntity>(IEnumerable<TEntity> entities, object groupby) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebReadGroupFillTemporalInternalAsync<TEntity>(IEnumerable<TEntity> entities, object groups, object groupby, object aggregates, object fill_from, object fill_to, object min_groups) where TEntity : IEntity<Guid>, IBaseable;
        Task<List<Dictionary<string, object>>> WebReadGroupFormatInternalAsync<TEntity>(IEnumerable<TEntity> entities, object groupby, object aggregates, List<object> groups) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebReadGroupGroupbyFormatterInternalAsync<TEntity>(IEnumerable<TEntity> entities, object groupby_spec, object values) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebReadGroupGroupbyPropertiesFormatterInternalAsync<TEntity>(IEnumerable<TEntity> entities, object groupby_spec, object values) where TEntity : IEntity<Guid>, IBaseable;
        Task<List<Dictionary<string, object>>> WebResequenceAsync<TEntity>(IEnumerable<TEntity> entities, object specification, string field_name, int offset) where TEntity : IEntity<Guid>, IBaseable;
        Task<List<Dictionary<string, object>>> WebSaveAsync<TEntity>(IEnumerable<TEntity> entities, object vals, object specification, Guid next_id) where TEntity : IEntity<Guid>, IBaseable;
        Task<List<Dictionary<string, object>>> WebSaveMultiAsync<TEntity>(IEnumerable<TEntity> entities, List<Dictionary<string, object>> vals_list, object specification) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WebSearchReadAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object specification, object offset, object limit, object order, object count_limit) where TEntity : IEntity<Guid>, IBaseable;
        Task<TEntity> WithUserAsync<TEntity>(IEnumerable<TEntity> entities, object user) where TEntity : IEntity<Guid>, IBaseable;
    }
}