using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Entities;
using Bamboo.Core.Domain.Shared.Interfaces;
using Bamboo.Core.Application.Contracts.Interfaces.Mixins;
namespace Bamboo.Core.Application.Contracts.Interfaces.Mixins
{
    public interface IGoogleCalendarSyncAppService : IMixinAppService
    {
        Task<TEntity> ActionJoinMeetingAsync<TEntity>(IEnumerable<TEntity> entities, Guid partner_id) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionJoinVideoCallAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionMassArchiveAsync<TEntity>(IEnumerable<TEntity> entities, object recurrence_update_setting) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionMassDeletionAsync<TEntity>(IEnumerable<TEntity> entities, object recurrence_update_setting) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionOpenCalendarEventAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionOpenComposerAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionSendSmsAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ActionSendmailAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ApplyRecurrenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object specific_values_creation, object no_send_edit, object generic_values_creation) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ApplyRecurrenceValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values, object future) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> AttendeesValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partner_commands) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> BreakRecurrenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object future) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CancelInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CancelMicrosoftInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ChangeAttendeeStatusAsync<TEntity>(IEnumerable<TEntity> entities, object status, object recurrence_update_setting) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckAnyRecordsToSyncInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckCalendarPrivacyWritePermissionsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckClosingDateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckEmployeesAvailabilityForEventInternalAsync<TEntity>(IEnumerable<TEntity> entities, object schedule_by_partner, object event_interval) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckMicrosoftSyncStatusInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckModifyEventPermissionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckOrganizerValidationConditionsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals_list) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckOrganizerValidationInternalAsync<TEntity>(IEnumerable<TEntity> entities, object sender_user, object partner_included) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckPrivateEventConditionsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckRecurrenceOverlappingInternalAsync<TEntity>(IEnumerable<TEntity> entities, object new_start) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CheckValuesToSyncInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ClearVideocallLocationAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeAttendeesCountInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeCandidateIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeCurrentAttendeeInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeDatesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeDisplayDescriptionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeDisplayNameInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeDisplayTimeInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeDtstartInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeDurationInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeFieldValueInternalAsync<TEntity>(IEnumerable<TEntity> entities, object field) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeGoogleIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeInvalidEmailPartnerIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeIsHighlightedInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeIsOrganizerAloneInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeNameInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeRecurrenceInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeRruleInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeRruleTypeUiInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeShouldShowStatusInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeStopInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeUnavailablePartnerIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeUserCanEditInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeVideocallLocationInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ComputeVideocallSourceInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CopyAsync<TEntity>(IEnumerable<TEntity> entities, object @default) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CreateAsync<TEntity>(IEnumerable<TEntity> entities, object vals_list) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CreateFromGoogleInternalAsync<TEntity>(IEnumerable<TEntity> entities, object gevents, object vals_list) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CreateVideocallChannelIdInternalAsync<TEntity>(IEnumerable<TEntity> entities, object name, List<Guid> partner_ids) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> CreateVideocallChannelInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> DefaultGetAsync<TEntity>(IEnumerable<TEntity> entities, object fields) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> DefaultPartnersInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> DefaultStartInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> DefaultStopInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> DetachEventsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object events) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> DoSmsReminderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object alarms) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> EnsureAttendeesHaveEmailInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> EventIdsFromGoogleIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities, List<Guid> google_ids) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> FetchQueryInternalAsync<TEntity>(IEnumerable<TEntity> entities, object query, object fields) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> FindPartnerCustomerAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ForbidRecurrenceCreationInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ForbidRecurrenceUpdateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> FromGoogleIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities, List<Guid> google_ids) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetActivityDeadlineFromStartInternalAsync<TEntity>(IEnumerable<TEntity> entities, object start, object allday) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetActivityExcludedModelsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetArchiveValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetAttendeeEmailsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetAttendeeStatusO2mInternalAsync<TEntity>(IEnumerable<TEntity> entities, object attendee) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetCustomFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetCustomerDescriptionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetCustomerSummaryInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDailyRecurrenceNameInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDateFormatsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDefaultDurationAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDefaultPrivacyDomainInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDiscussVideocallLocationAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDisplayTimeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object start, object stop, object zduration, object zallday) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDisplayTimeTzAsync<TEntity>(IEnumerable<TEntity> entities, object tz) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetDurationInternalAsync<TEntity>(IEnumerable<TEntity> entities, object start, object stop) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetEventGoogleIdInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @event) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetEventUserInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetEventUserMInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid user_id) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetEventsFromInternalAsync<TEntity>(IEnumerable<TEntity> entities, object dtstart) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetEventsIntervalInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetFirstEventInternalAsync<TEntity>(IEnumerable<TEntity> entities, object include_outliers) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetGoogleSyncedFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetIcsFileInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetLangWeekStartInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetMailMessageAccessInternalAsync<TEntity>(IEnumerable<TEntity> entities, List<Guid> res_ids, object operation, object model_name) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetMailTzInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetMicrosoftSyncDomainInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetMicrosoftSyncedFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetMonthlyRecurrenceNameInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetNextAlarmDateAsync<TEntity>(IEnumerable<TEntity> entities, object events_by_alarm) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetOccurrencesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object dtstart) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetOrganizerInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetOrganizerUserChangeInfoInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetOutliersInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetPostSyncValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object request_values, object google_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetPublicFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRangesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object start, object event_duration) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRecordsToSyncInternalAsync<TEntity>(IEnumerable<TEntity> entities, object full_sync) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRecurrenceNameAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRecurrenceParamsByDateInternalAsync<TEntity>(IEnumerable<TEntity> entities, object event_date) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRecurrenceParamsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRecurrentFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRemoveSyncIdValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetRruleInternalAsync<TEntity>(IEnumerable<TEntity> entities, object dtstart) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetStartDateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetStartOfPeriodInternalAsync<TEntity>(IEnumerable<TEntity> entities, object dt) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetStateSelectionsAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetSyncDomainInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetSyncPartnerInternalAsync<TEntity>(IEnumerable<TEntity> entities, object emails) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetTimeFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetTimeUpdateDictInternalAsync<TEntity>(IEnumerable<TEntity> entities, object base_event, object time_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetTimezoneInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetTriggerAlarmTypesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetUnusualDaysAsync<TEntity>(IEnumerable<TEntity> entities, object date_from, object date_to) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetUpdateFutureEventsValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetUpdatedRecurrenceValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object new_start_date) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetWeekDaysInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetWeeklyRecurrenceNameInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GetYearlyRecurrenceNameInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GoogleDeleteInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_service, Guid google_id, object timeout) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GoogleErrorHandlingInternalAsync<TEntity>(IEnumerable<TEntity> entities, object http_error) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GoogleInsertInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_service, object values, object timeout) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GooglePatchInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_service, Guid google_id, object values, object timeout) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> GoogleValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> HandleAlldayRecurrencesEdgeCaseInternalAsync<TEntity>(IEnumerable<TEntity> entities, object records, object vals_list) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> HasBaseEventTimeFieldsChangedInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @new) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> InverseDatesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> InverseRruleInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> IsAlldayInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> IsCrmLeadInternalAsync<TEntity>(IEnumerable<TEntity> entities, object defaults, object ctx) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> IsEventOverInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> IsGoogleInsertionBlockedInternalAsync<TEntity>(IEnumerable<TEntity> entities, object sender_user) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> IsMatchingTimeslotInternalAsync<TEntity>(IEnumerable<TEntity> entities, object start, object stop, object allday) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> IsMicrosoftInsertionBlockedInternalAsync<TEntity>(IEnumerable<TEntity> entities, object sender_user) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> MicrosoftToOdooRecurrenceValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object microsoft_event, object default_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> MicrosoftToOdooValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object microsoft_event, object default_reminders, object default_values, List<Guid> with_ids) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> MicrosoftValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object fields_to_sync, object initial_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> MicrosoftValuesOccurenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object initial_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> NeedVideoCallInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> OdooAttendeeCommandsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_event) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> OdooAttendeeCommandsMInternalAsync<TEntity>(IEnumerable<TEntity> entities, object microsoft_event) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> OdooRemindersCommandsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object reminders) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> OdooRemindersCommandsMInternalAsync<TEntity>(IEnumerable<TEntity> entities, object microsoft_event) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> OdooValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_event, object default_reminders) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> OnchangeDateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RangeCalculationInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @event, object duration) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RangeInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ReadGroupAsync<TEntity>(IEnumerable<TEntity> entities, object domain, object fields, object groupby, object offset, object limit, object @orderby, object lazy) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ReconcileEventsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object ranges) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RecreateEventDifferentOrganizerInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values, object sender_user) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> ResetAttendeesStatusInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RestartGoogleSyncInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RestartMicrosoftSyncInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RewriteRecurrenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values, object time_values, object recurrence_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RruleParseInternalAsync<TEntity>(IEnumerable<TEntity> entities, object rule_str, object date_start) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> RruleSerializeInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SearchCurrentAttendeeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @operator, object @value) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SelectNewBaseEventInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SetDiscussVideocallLocationAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SetDiscussVideocallLocationInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SetVideocallLocationInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals_list) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SetupAlarmsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SkipSendMailStatusUpdateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SplitFromInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @event, object recurrence_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SplitRecurrenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object time_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> StopAtInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @event) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SyncActivitiesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object fields) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SyncGoogle2odooInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_events, object write_dates, object default_reminders) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> SyncOdoo2googleInternalAsync<TEntity>(IEnumerable<TEntity> entities, object google_service) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> UnlinkAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> UpdateAttendeeStatusInternalAsync<TEntity>(IEnumerable<TEntity> entities, List<Guid> attendee_ids) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> UpdateFutureEventsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values, object time_values, object recurrence_values) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> WriteAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> WriteEventsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values, object dtstart) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> WriteFromGoogleInternalAsync<TEntity>(IEnumerable<TEntity> entities, object gevent, object vals) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
        Task<TEntity> WriteFromMicrosoftInternalAsync<TEntity>(IEnumerable<TEntity> entities, object microsoft_event, object vals) where TEntity : IEntity<Guid>, IGoogleCalendarSyncable;
    }
}