using Volo.Abp.Application.Services;
using System.Linq;
using Volo.Abp.Domain.Entities;
using System.Collections.Generic;
using Bamboo.Core.Domain.Shared.Interfaces;
using System;
using Bamboo.Core.Application.Contracts.Interfaces.Mixins;
using System.Threading.Tasks;
namespace Bamboo.Core.Application.Contracts.Interfaces.Mixins
{
    public interface IIrQwebAppService : IMixinAppService
    {
        Task<TEntity> AdaptStyleBackgroundImageInternalAsync<TEntity>(IEnumerable<TEntity> entities, object atts, object url_adapter) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> AppendTextInternalAsync<TEntity>(IEnumerable<TEntity> entities, object text, object compile_context) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileBoolInternalAsync<TEntity>(IEnumerable<TEntity> entities, object attr, object @default) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveAsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveAttInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveCacheInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveCallAssetsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveCallInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveConsumedOptionsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveDebugInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveElifInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveElseInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveEscInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveFieldInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveForeachInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveGroupsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveIfInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveInnerContentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveInstallInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object indent) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object directive, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveLangInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveNocacheInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveOptionsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveOutInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectivePlaceholderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object indent) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveRawInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveSetInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveSnippetCallInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object indent) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveSnippetInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object indent) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveTagCloseInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveTagOpenInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveValueInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectiveValuefInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileDirectivesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileExprInternalAsync<TEntity>(IEnumerable<TEntity> entities, object expr, object raise_on_missing) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileExprTokensInternalAsync<TEntity>(IEnumerable<TEntity> entities, object tokens, object allowed_keys, object argument_names, object raise_on_missing) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileFormatInternalAsync<TEntity>(IEnumerable<TEntity> entities, object expr) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileInternalAsync<TEntity>(IEnumerable<TEntity> entities, object template) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileNodeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileStaticNodeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context, object level) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> CompileToStrInternalAsync<TEntity>(IEnumerable<TEntity> entities, object expr) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> DebugTraceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object debugger, object values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> DirectivesEvalOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> FlushTextInternalAsync<TEntity>(IEnumerable<TEntity> entities, object compile_context, object level, object rstrip) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GenerateAssetLinksCacheInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle, object css, object js, object assets_params, object rtl) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GenerateAssetLinksInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle, object css, object js, object debug_assets, object assets_params, object rtl) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GenerateCodeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object template) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetAssetBundleInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle_name, object css, object js, object debug_assets, object rtl, object assets_params) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetAssetContentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle, object assets_params) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetAssetLinkUrlsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle, object debug) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetAssetLinksInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle, object css, object js, object debug) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetAssetNodesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bundle, object css, object js, object debug, object defer_load, object lazy_load, object media) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetBundlesToPregenarateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetCacheKeyInternalAsync<TEntity>(IEnumerable<TEntity> entities, object cache_key) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetCachedValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object cache_key, object get_value) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetConvertedImageDataUriInternalAsync<TEntity>(IEnumerable<TEntity> entities, object base64_source) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetFieldInternalAsync<TEntity>(IEnumerable<TEntity> entities, object record, object field_name, object expression, object tagName, object field_options, object values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetTemplateCacheKeysInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetTemplateInternalAsync<TEntity>(IEnumerable<TEntity> entities, object template) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetViewIdInternalAsync<TEntity>(IEnumerable<TEntity> entities, object template) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> GetWidgetInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @value, object expression, object tagName, object field_options, object values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> IsExpressionAllowedInternalAsync<TEntity>(IEnumerable<TEntity> entities, object expression, object model) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> IsStaticNodeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object el, object compile_context) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> LinkToNodeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object path, object defer_load, object lazy_load, object media) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> LinksToNodesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object paths, object defer_load, object lazy_load, object media) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> LoadInternalAsync<TEntity>(IEnumerable<TEntity> entities, object @ref) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> LoadValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object cache_key, object get_value, object loaded_values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> PostProcessingAttInternalAsync<TEntity>(IEnumerable<TEntity> entities, object tagName, object atts) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> PregenerateAssetsBundlesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> PrepareEnvironmentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> PrepareFrontendEnvironmentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> RenderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object template, object values) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> RstripTextInternalAsync<TEntity>(IEnumerable<TEntity> entities, object compile_context) where TEntity : IEntity<Guid>, IIrQwebable;
        Task<TEntity> _PrepareGlobalsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IIrQwebable;
    }
}