using Volo.Abp.Domain.Entities;
using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Domain.Shared.Interfaces;
using Bamboo.Core.Application.Contracts.Interfaces.Mixins;
namespace Bamboo.Core.Application.Contracts.Interfaces.Mixins
{
    public interface IPosBusMixinAppService : IMixinAppService
    {
        Task<TEntity> AccumulateAmountsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionCreateInvoicesAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosConfigModalEditAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosOrderCancelAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosOrderInvoiceAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosOrderPaidAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosSessionCloseAsync<TEntity>(IEnumerable<TEntity> entities, object balancing_account, object amount_to_balance, object bank_payment_method_diffs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosSessionClosingControlAsync<TEntity>(IEnumerable<TEntity> entities, object balancing_account, object amount_to_balance, object bank_payment_method_diffs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosSessionOpenAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionPosSessionValidateAsync<TEntity>(IEnumerable<TEntity> entities, object balancing_account, object amount_to_balance, object bank_payment_method_diffs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionSendMailAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionSendReceiptAsync<TEntity>(IEnumerable<TEntity> entities, object email, object ticket_image, object basic_image) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionShowPaymentsListAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionStockPickingAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionToOpenUiInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionViewInvoiceAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionViewOrderAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionViewRefundOrdersAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ActionViewRefundedOrderAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> AddPaymentAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> AddTrustedConfigIdInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid config_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> AlertOldSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> AmountConverterInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amount, object date, object round) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ApplyDiffOnAccountPaymentMoveInternalAsync<TEntity>(IEnumerable<TEntity> entities, object account_payment, object payment_method, object diff_amount) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CannotCloseSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object bank_payment_method_diffs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckBeforeCreatingNewSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckCompaniesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckCompanyHasFiscalCountryInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckCompanyHasTemplateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckCompanyPaymentInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckCurrenciesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckGroupsImpliedInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckHeaderFooterInternalAsync<TEntity>(IEnumerable<TEntity> entities, object values) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckIfNoDraftOrdersInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckInvoicesArePostedInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckModulesToInstallInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckPaymentMethodIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckPaymentMethodIdsJournalInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckPosConfigInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckPricelistsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckProfitLossCashJournalInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckRoundingMethodStrategyInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckStartDateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CheckTrustedConfigIdsCurrencyInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CleanPaymentLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CloseSessionActionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amount_to_balance) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CloseSessionFromUiAsync<TEntity>(IEnumerable<TEntity> entities, object bank_payment_method_diff_pairs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CloseUiAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CompleteValuesFromSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object session, object values) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeAmountPaidInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCashBalanceInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCashControlInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCashJournalInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCompanyHasTemplateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeContactDetailsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCurrencyInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCurrencyRateInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCurrentSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeCurrentSessionUserInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeFastPaymentMethodIdsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeHasRefundableLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeInvoiceStatusInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeIsEditedInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeIsInCompanyCurrencyInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeIsInstalledAccountAccountantInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeIsInvoicedInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeIsTotalCostComputedInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeLastSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeLocalDataIntegrityInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeMarginInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeOrderConfigIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeOrderCountInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeOrderNameInternalAsync<TEntity>(IEnumerable<TEntity> entities, object session) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputePickingCountInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputePricesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeRefundRelatedFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeStatisticsForSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeTotalCostAtSessionClosingInternalAsync<TEntity>(IEnumerable<TEntity> entities, object stock_moves) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeTotalCostInRealTimeInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ComputeTotalPaymentsAmountInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateAccountMoveInternalAsync<TEntity>(IEnumerable<TEntity> entities, object balancing_account, object amount_to_balance, object bank_payment_method_diffs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateAsync<TEntity>(IEnumerable<TEntity> entities, object vals_list) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateBalancingLineInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data, object balancing_account, object amount_to_balance) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateBankPaymentMovesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateCashPaymentMethodInternalAsync<TEntity>(IEnumerable<TEntity> entities, object cash_journal_vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateCashStatementLinesAndCashMoveLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateCombineAccountPaymentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_method, object amounts, object diff_amount) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateDiffAccountMoveForSplitPaymentMethodInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_method, object diff_amount) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateInvoiceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object move_vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateInvoiceReceivableLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateJournalAndPaymentMethodsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object cash_ref, object cash_journal_vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateMiscReversalMoveInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_moves) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateNonReconciliableMoveLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateOrderPickingInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreatePayLaterReceivableLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreatePickingAtEndOfSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreatePmChangeLogInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateSequencesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateSplitAccountPaymentInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment, object amounts) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreateStockValuationLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> CreditAmountsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partial_move_line_vals, object amount, object amount_converted, object force_company_currency) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DebitAmountsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partial_move_line_vals, object amount, object amount_converted, object force_company_currency) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DefaultInvoiceJournalInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DefaultPaymentMethodsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DefaultPickingTypeIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DefaultSaleJournalInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DefaultWarehouseIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DeleteCashInOutAsync<TEntity>(IEnumerable<TEntity> entities, Guid absl_id, Guid partner_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> DeleteOpeningControlSessionAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> EnsureAccessTokenInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> EnsureToKeepLastPreparationChangeInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> EnvWithCleanContextInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ExecuteAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> FilterLocalDataAsync<TEntity>(IEnumerable<TEntity> entities, object models_to_filter) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> FindProductByBarcodeAsync<TEntity>(IEnumerable<TEntity> entities, object barcode, Guid config_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GeneratePosOrderInvoiceInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetAttributesByPtalIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetAvailablePricelistsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetBalancingAccountInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetCapturedPaymentsDomainInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetCashInOutListAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetClosedOrdersInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetClosingControlDataAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetCombineReceivableValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_method, object amount, object amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetCombineStatementLineValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object journal, object amount, object payment_method) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetCustomerDisplayDataInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetDefaultDemoDataXmlIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetDefaultTipProductInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetDemoDataLoaderMethodsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetDiffAccountMoveRefInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_method) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetDiffValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid payment_method_id, object diff_amount, object outstanding_account) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetDisplayDeviceIpInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetForbiddenChangeFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetGroupPosManagerInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetGroupPosUserInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetInvoiceLinesValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object line_values, object pos_line, object move_type) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetInvoicePostContextInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetInvoiceReceivableValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amount, object amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetInvoiceTotalListInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetLimitedPartnerCountInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetLimitedPartnersLoadingAsync<TEntity>(IEnumerable<TEntity> entities, object offset) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetLimitedProductCountAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetMailAttachmentsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object name, object ticket, object basic_ticket) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetNextOrderRefsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object device_identifier) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetOpenOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetOtherRelatedMovesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPartnerBankIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPartnersDomainInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPaymentMethodInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_type) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPosAngloSaxonPriceUnitInternalAsync<TEntity>(IEnumerable<TEntity> entities, object product, Guid partner_id, object quantity) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPosKanbanViewStateAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPosUiProductPricelistItemByProductAsync<TEntity>(IEnumerable<TEntity> entities, List<Guid> product_tmpl_ids, List<Guid> product_ids, Guid config_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetPreparationChangeAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetReceivableAccountInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_method) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetRecordByRefAsync<TEntity>(IEnumerable<TEntity> entities, object recordRefs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetReferenceLastPartAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetRefundedOrdersInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetRelatedAccountMovesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetRoundedAmountInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amount, object force_round) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetRoundingDifferenceValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amount, object amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSaleKeyInternalAsync<TEntity>(IEnumerable<TEntity> entities, object base_line) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSaleValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object key, object sale_vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSessionOrdersAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSpecialProductsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSplitReceivableValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment, object amount, object amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSplitStatementLineValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object journal, object amount, object payment) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetStatisticsForSessionAsync<TEntity>(IEnumerable<TEntity> entities, object session) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetStockExpenseValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object exp_account, object amount, object amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetStockValuationValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object stock_val_account, object amount, object amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetSuffixedRefNameInternalAsync<TEntity>(IEnumerable<TEntity> entities, object ref_name) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetTaxValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object key, object amount, object amount_converted, object base_amount_converted) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetTotalDiscountAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetTotalInvoiceInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetUrlToCacheInternalAsync<TEntity>(IEnumerable<TEntity> entities, object debug) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> GetValidSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> InstallPosRestaurantAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> IsJournalExistInternalAsync<TEntity>(IEnumerable<TEntity> entities, object journal_code, object name, Guid company_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> IsPosOrderPaidInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> IsPosPmExistInternalAsync<TEntity>(IEnumerable<TEntity> entities, object name, Guid journal_id, Guid company_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> IsQuantitiesSetInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> KeepNewValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LinkSameNonCashPaymentMethodsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object source_config) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadDataAsync<TEntity>(IEnumerable<TEntity> entities, object models_to_load) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadDataParamsAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadDemoDataAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingBakeryDemoDataInternalAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingBakeryScenarioAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingClothesDemoDataInternalAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingClothesScenarioAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingFurnitureDemoDataInternalAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingFurnitureScenarioAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadOnboardingRetailScenarioAsync<TEntity>(IEnumerable<TEntity> entities, object with_demo_data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadPosDataDomainInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data, object config) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadPosDataFieldsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object config) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadPosDataModelsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object config) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadPosDataReadInternalAsync<TEntity>(IEnumerable<TEntity> entities, object records, object config) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LoadPosDataRelationsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object model, object fields) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> LogPartnerMessageAsync<TEntity>(IEnumerable<TEntity> entities, Guid partner_id, object action, object message_type) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> MarkupListMessageInternalAsync<TEntity>(IEnumerable<TEntity> entities, object message) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> NotifyInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> NotifySynchronisationAsync<TEntity>(IEnumerable<TEntity> entities, Guid session_id, object device_identifier, object records) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OnchangeAmountAllInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OnchangeEpsonPrinterIpInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OnchangePartnerIdInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OpenExistingSessionCbAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OpenFrontendCbAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OpenOpenedRescueSessionFormAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OpenSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid session_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> OpenUiAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PosHasValidProductInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PostCashDetailsMessageInternalAsync<TEntity>(IEnumerable<TEntity> entities, object state, object expected, object difference, object notes) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PostCloseRegisterMessageAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PostClosingCashDetailsAsync<TEntity>(IEnumerable<TEntity> entities, object counted_cash) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PostStatementDifferenceInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amount) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareAccountBankStatementLineValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object session, object sign, object amount, object reason, Guid partner_id, object extras) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareAmlValuesListPerNatureInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareBalancingLineValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object imbalance_amount, object move, object balancing_account) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareInvoiceLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object move_type) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareInvoiceValsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareMailValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object email, object ticket, object basic_ticket) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PreparePosLogInternalAsync<TEntity>(IEnumerable<TEntity> entities, object body) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareProductAmlDictInternalAsync<TEntity>(IEnumerable<TEntity> entities, object base_line_vals, object update_base_line_vals, object rate, object sign) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareRefundValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object current_session) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareStatementLineAmountValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object journal, object amount) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PrepareTaxBaseLineValuesInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> PreprocessX2manyValsFromSettingsViewInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ProcessOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order, object existing_order) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ProcessPaymentLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object pos_order, object order, object pos_session, object draft) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ProcessSavedOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object draft) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ReadConfigOpenOrdersAsync<TEntity>(IEnumerable<TEntity> entities, object domain, List<Guid> record_ids) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ReadPosDataAsync<TEntity>(IEnumerable<TEntity> entities, object data, object config) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ReadPosDataUuidAsync<TEntity>(IEnumerable<TEntity> entities, object uuid) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ReadPosOrdersAsync<TEntity>(IEnumerable<TEntity> entities, object domain) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ReconcileAccountMoveLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object data) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ReconcileInvoicePaymentsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object invoice, object payment_moves) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> RefundAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> RefundInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> RegisterNewDeviceIdentifierAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> RemoveFromUiAsync<TEntity>(IEnumerable<TEntity> entities, List<Guid> server_ids) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> RemoveTrustedConfigIdInternalAsync<TEntity>(IEnumerable<TEntity> entities, Guid config_id) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ResetDefaultOnValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> RoundAmountsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object amounts) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SearchPaidOrderIdsAsync<TEntity>(IEnumerable<TEntity> entities, Guid config_id, object domain, object limit, object offset) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SendOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SetDefaultPosLoadLimitInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SetFiscalPositionInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SetOpeningControlAsync<TEntity>(IEnumerable<TEntity> entities, int cashbox_value, string notes) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SetOpeningControlDataInternalAsync<TEntity>(IEnumerable<TEntity> entities, int cashbox_value, string notes) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ShouldCreatePickingRealTimeInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ShowCashRegisterAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ShowJournalItemsAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> SyncFromUiAsync<TEntity>(IEnumerable<TEntity> entities, object orders) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> TryCashInOutAsync<TEntity>(IEnumerable<TEntity> entities, object _type, object amount, object reason, Guid partner_id, object extras) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UnlinkAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UnlinkExceptDraftOrCancelInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UpdateAmountsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object old_amounts, object amounts_to_add, object date, object round, object force_company_currency) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UpdateClosingControlStateSessionAsync<TEntity>(IEnumerable<TEntity> entities, object notes) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UpdateCustomerDisplayAsync<TEntity>(IEnumerable<TEntity> entities, object order, object device_uuid) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UpdatePreparationPrintersMenuitemVisibilityInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> UpdateSequenceNumberInternalAsync<TEntity>(IEnumerable<TEntity> entities, object session, object values) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> ValidateSessionInternalAsync<TEntity>(IEnumerable<TEntity> entities, object balancing_account, object amount_to_balance, object bank_payment_method_diffs) where TEntity : IEntity<Guid>, IPosBusMixinable;
        Task<TEntity> WriteAsync<TEntity>(IEnumerable<TEntity> entities, object vals) where TEntity : IEntity<Guid>, IPosBusMixinable;
    }
}