// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces.Mixins;
using Bamboo.Core.Domain.Shared.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Entities;
namespace Bamboo.Core.Application.Contracts.Interfaces.Mixins
{
    public interface IPurchaseEdiXmlUblBis3AppService : IMixinAppService
    {
        Task<TEntity> ExportOrderInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> ExportOrderValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> ExportPurchaseOrderFilenameInternalAsync<TEntity>(IEnumerable<TEntity> entities, object purchase_order) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetAnticipatedMonetaryTotalValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object purchase_order, object order_lines) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetCountryValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object country) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetDeliveryPartyValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object delivery) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetItemValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order, object order_line) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetLineAllowanceChargeValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object line) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetLineItemPriceValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object line) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetOrderLinesInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetPartnerAddressValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partner) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetPartnerContactValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partner) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetPartnerPartyLegalEntityValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partner) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetPartnerPartyTaxSchemeValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partner) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetPartnerPartyValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object partner, object role) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetPaymentTermsValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object payment_term) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
        Task<TEntity> GetTaxCategoryValsInternalAsync<TEntity>(IEnumerable<TEntity> entities, object order, object order_line) where TEntity : IEntity<Guid>, IPurchaseEdiXmlUblBis3able;
    }
}