// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces.Mixins;
using Bamboo.Core.Domain.Shared.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Entities;
namespace Bamboo.Core.Application.Contracts.Interfaces.Mixins
{
    public interface ITransifexTranslationAppService : IMixinAppService
    {
        Task<TEntity> GetTransifexProjectsInternalAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : IEntity<Guid>, ITransifexTranslationable;
        Task<TEntity> UpdateTransifexUrlInternalAsync<TEntity>(IEnumerable<TEntity> entities, object translations) where TEntity : IEntity<Guid>, ITransifexTranslationable;
    }
}