// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IFetchmailServerAppService : IGenericApplicationService<FetchmailServer>
    {
        Task<FetchmailServer> ButtonConfirmLoginAsync(Guid id);
        Task<FetchmailServer> ConnectAsync(Guid id, object allow_archived);
        Task<FetchmailServer> FetchMailAsync(Guid id, object raise_exception);
        Task<FetchmailServer> OnchangeServerTypeAsync(Guid id);
        Task<FetchmailServer> SetDraftAsync(Guid id);
    }
}