// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrAssetFilterDuplicateRequestDto
    {
        public Guid WebsiteId { get; set; }
    }
}