// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MrpProductionCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class MrpProductionGetEmptyListHelpRequestDto
    {
        public object HelpMessage { get; set; }
    }
}