// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IHrLeaveTypeAppService : IGenericApplicationService<HrLeaveType>
    {
        Task<HrLeaveType> CheckAllocationRequirementEditValidityAsync(Guid id);
        Task<HrLeaveType> CopyDataAsync(Guid id, object @default);
        Task<HrLeaveType> GetAllocationDataAsync(Guid id, object employees, object date);
        Task<HrLeaveType> GetAllocationDataRequestAsync(Guid id, object target_date, object hidden_allocations);
        Task<HrLeaveType> HasAccrualAllocationAsync(Guid id);
        Task<HrLeaveType> RequestedDisplayNameAsync(Guid id);
        Task<HrLeaveType> SeeAccrualPlansAsync(Guid id);
        Task<HrLeaveType> SeeDaysAllocatedAsync(Guid id);
        Task<HrLeaveType> SeeGroupLeavesAsync(Guid id);
    }
}