// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class CrmIapLeadHelpersLeadValsFromResponseRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? LeadType { get; set; }
        public Guid? TeamId { get; set; }
        public List<Guid>? TagIds { get; set; }
        public Guid? UserId { get; set; }
        public object? CompanyData { get; set; }
        public object? PeopleData { get; set; }
    }
}