// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class CrmTeamUpdateInvoicedTargetRequestDto
    {
        public object Value { get; set; }
    }
}