// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class DeliveryCarrierAvailableCarriersRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Partner { get; set; }
        public object? Source { get; set; }
    }
    
    public class DeliveryCarrierBaseOnRuleCancelShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
    }
    
    public class DeliveryCarrierBaseOnRuleGetTrackingLinkRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Picking { get; set; }
    }
    
    public class DeliveryCarrierBaseOnRuleRateShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Order { get; set; }
    }
    
    public class DeliveryCarrierBaseOnRuleSendShippingRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
    }
    
    public class DeliveryCarrierCancelShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
    }
    
    public class DeliveryCarrierCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class DeliveryCarrierFixedCancelShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
    }
    
    public class DeliveryCarrierFixedGetTrackingLinkRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Picking { get; set; }
    }
    
    public class DeliveryCarrierFixedRateShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Order { get; set; }
    }
    
    public class DeliveryCarrierFixedSendShippingRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
    }
    
    public class DeliveryCarrierGelatoRateShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Order { get; set; }
    }
    
    public class DeliveryCarrierGetReturnLabelRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
        public object? TrackingNumber { get; set; }
        public object? OriginDate { get; set; }
    }
    
    public class DeliveryCarrierGetTrackingLinkRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Picking { get; set; }
    }
    
    public class DeliveryCarrierLogXmlRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? XmlString { get; set; }
        public object? Func { get; set; }
    }
    
    public class DeliveryCarrierRateShipmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Order { get; set; }
    }
    
    public class DeliveryCarrierSendShippingRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Pickings { get; set; }
    }
}