// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class LoyaltyCardGetGiftCardStatusRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? GiftCode { get; set; }
        public Guid? ConfigId { get; set; }
    }
    
    public class LoyaltyCardGetLoyaltyCardPartnerByCodeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Code { get; set; }
    }
}