// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class PosOrderAddLoyaltyHistoryLinesRequestDto
    {
        public object CouponData { get; set; }
        public object CouponUpdates { get; set; }
    }
    
    public class PosOrderAddPaymentRequestDto
    {
        public object Data { get; set; }
    }
    
    public class PosOrderConfirmCouponProgramsRequestDto
    {
        public object CouponData { get; set; }
    }
    
    public class PosOrderGetAndSetOnlinePaymentsDataRequestDto
    {
        public object NextOnlinePaymentAmount { get; set; }
    }
    
    public class PosOrderReadPosDataRequestDto
    {
        public object Data { get; set; }
        public object Config { get; set; }
    }
    
    public class PosOrderReadPosDataUuidRequestDto
    {
        public object Uuid { get; set; }
    }
    
    public class PosOrderReadPosOrdersRequestDto
    {
        public object Domain { get; set; }
    }
    
    public class PosOrderRemoveFromUiRequestDto
    {
        public List<Guid> ServerIds { get; set; }
    }
    
    public class PosOrderSearchPaidOrderIdsRequestDto
    {
        public Guid ConfigId { get; set; }
        public object Domain { get; set; }
        public object Limit { get; set; }
        public object Offset { get; set; }
    }
    
    public class PosOrderSendReceiptRequestDto
    {
        public object Email { get; set; }
        public object TicketImage { get; set; }
        public object BasicImage { get; set; }
    }
    
    public class PosOrderSendSelfOrderReceiptRequestDto
    {
        public object Email { get; set; }
        public Guid MailTemplateId { get; set; }
        public object TicketImage { get; set; }
        public object BasicImage { get; set; }
    }
    
    public class PosOrderSentMessageOnSmsRequestDto
    {
        public object Phone { get; set; }
        public object _Unnamed_ { get; set; }
        public object BasicImage { get; set; }
    }
    
    public class PosOrderSyncFromUiRequestDto
    {
        public object Orders { get; set; }
    }
    
    public class PosOrderValidateCouponProgramsRequestDto
    {
        public object PointChanges { get; set; }
        public object NewCodes { get; set; }
    }
}