// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class PosOrderLineGetExistingLotsRequestDto
    {
        public Guid CompanyId { get; set; }
        public Guid ProductId { get; set; }
    }
}