// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class PosPaymentMethodCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class PosPaymentMethodGetProviderStatusRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? ModulesList { get; set; }
    }
    
    public class PosPaymentMethodGetQrCodeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
        public object? FreeCommunication { get; set; }
        public object? StructuredCommunication { get; set; }
        public object? Currency { get; set; }
        public object? DebtorPartner { get; set; }
    }
    
    public class PosPaymentMethodMpGetPaymentStatusRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? PaymentId { get; set; }
    }
    
    public class PosPaymentMethodMpPaymentIntentCancelRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? PaymentIntentId { get; set; }
    }
    
    public class PosPaymentMethodMpPaymentIntentCreateRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Infos { get; set; }
    }
    
    public class PosPaymentMethodMpPaymentIntentGetRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? PaymentIntentId { get; set; }
    }
    
    public class PosPaymentMethodPineLabsCancelPaymentRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodPineLabsFetchPaymentStatusRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodPineLabsMakePaymentRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodProxyAdyenRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
        public object? Operation { get; set; }
    }
    
    public class PosPaymentMethodQfpaySignRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Payload { get; set; }
    }
    
    public class PosPaymentMethodRazorpayCancelPaymentRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodRazorpayFetchPaymentStatusRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodRazorpayMakePaymentRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodRazorpayMakeRefundRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodSendDpopayRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
        public object? Endpoint { get; set; }
    }
    
    public class PosPaymentMethodStripeCapturePaymentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? PaymentIntentId { get; set; }
        public object? Amount { get; set; }
    }
    
    public class PosPaymentMethodStripePaymentIntentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
    }
    
    public class PosPaymentMethodVivaComGetPaymentStatusRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? SessionId { get; set; }
    }
    
    public class PosPaymentMethodVivaComSendPaymentCancelRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodVivaComSendPaymentRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
    
    public class PosPaymentMethodVivaComSendRefundRequestRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Data { get; set; }
    }
}