// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class PosSessionCloseSessionFromUiRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? BankPaymentMethodDiffPairs { get; set; }
    }
    
    public class PosSessionDeleteCashInOutRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? AbslId { get; set; }
        public Guid? PartnerId { get; set; }
    }
    
    public class PosSessionFilterLocalDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? ModelsToFilter { get; set; }
    }
    
    public class PosSessionFindProductByBarcodeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Barcode { get; set; }
        public Guid? ConfigId { get; set; }
    }
    
    public class PosSessionGetPosUiProductPricelistItemByProductRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? ProductTmplIds { get; set; }
        public List<Guid>? ProductIds { get; set; }
        public Guid? ConfigId { get; set; }
    }
    
    public class PosSessionLoadDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? ModelsToLoad { get; set; }
    }
    
    public class PosSessionLogPartnerMessageRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? PartnerId { get; set; }
        public object? Action { get; set; }
        public object? MessageType { get; set; }
    }
    
    public class PosSessionPosSessionCloseRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? BalancingAccount { get; set; }
        public object? AmountToBalance { get; set; }
        public object? BankPaymentMethodDiffs { get; set; }
    }
    
    public class PosSessionPosSessionClosingControlRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? BalancingAccount { get; set; }
        public object? AmountToBalance { get; set; }
        public object? BankPaymentMethodDiffs { get; set; }
    }
    
    public class PosSessionPosSessionValidateRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? BalancingAccount { get; set; }
        public object? AmountToBalance { get; set; }
        public object? BankPaymentMethodDiffs { get; set; }
    }
    
    public class PosSessionPostClosingCashDetailsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? CountedCash { get; set; }
    }
    
    public class PosSessionSetOpeningControlRequestDto
    {
        public Guid[]? Ids { get; set; }
        public int? CashboxValue { get; set; }
        public string? Notes { get; set; }
    }
    
    public class PosSessionTryCashInOutRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? _Type { get; set; }
        public object? Amount { get; set; }
        public object? Reason { get; set; }
        public Guid? PartnerId { get; set; }
        public object? Extras { get; set; }
    }
    
    public class PosSessionUpdateClosingControlStateSessionRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Notes { get; set; }
    }
}