// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProductTemplateCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class ProductTemplateCreateProductVariantRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? ProductTemplateAttributeValueIds { get; set; }
    }
    
    public class ProductTemplateCreateProductVariantFromPosRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? AttributeValueIds { get; set; }
        public Guid? ConfigId { get; set; }
    }
    
    public class ProductTemplateGetContextualPriceRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Product { get; set; }
    }
    
    public class ProductTemplateGetEmptyListHelpRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? HelpMessage { get; set; }
    }
    
    public class ProductTemplateGetProductAccountsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? FiscalPos { get; set; }
    }
    
    public class ProductTemplateGetProductInfoPosRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Price { get; set; }
        public object? Quantity { get; set; }
        public Guid? PosConfigId { get; set; }
        public Guid? ProductVariantId { get; set; }
    }
    
    public class ProductTemplateLoadProductFromPosRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? ConfigId { get; set; }
        public object? Domain { get; set; }
        public object? Offset { get; set; }
        public object? Limit { get; set; }
    }
}