// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProductTemplateCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class ProductTemplateCreateProductVariantRequestDto
    {
        public List<Guid> ProductTemplateAttributeValueIds { get; set; }
    }
    
    public class ProductTemplateGetContextualPriceRequestDto
    {
        public object Product { get; set; }
    }
    
    public class ProductTemplateGetEmptyListHelpRequestDto
    {
        public object HelpMessage { get; set; }
    }
    
    public class ProductTemplateGetProductAccountsRequestDto
    {
        public object FiscalPos { get; set; }
    }
}