// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProductProductGetEmptyListHelpRequestDto
    {
        public object HelpMessage { get; set; }
    }
    
    public class ProductProductViewHeaderGetRequestDto
    {
        public Guid ViewId { get; set; }
        public object ViewType { get; set; }
    }
}