// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProductProductGetEmptyListHelpRequestDto
    {
        public object HelpMessage { get; set; }
    }
    
    public class ProductProductGetProductInfoPosRequestDto
    {
        public object Price { get; set; }
        public object Quantity { get; set; }
        public Guid PosConfigId { get; set; }
    }
    
    public class ProductProductViewHeaderGetRequestDto
    {
        public Guid ViewId { get; set; }
        public object ViewType { get; set; }
    }
}