// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class RestaurantFloorDeactivateFloorRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? SessionId { get; set; }
    }
    
    public class RestaurantFloorRenameFloorRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? NewName { get; set; }
    }
    
    public class RestaurantFloorSyncFromUiRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Name { get; set; }
        public object? BackgroundColor { get; set; }
        public Guid? ConfigId { get; set; }
    }
}