// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SaleOrderCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class SaleOrderCreateDocumentFromAttachmentRequestDto
    {
        public List<Guid> AttachmentIds { get; set; }
    }
    
    public class SaleOrderGetEmptyListHelpRequestDto
    {
        public object HelpMessage { get; set; }
    }
    
    public class SaleOrderGetPromoCodeErrorRequestDto
    {
        public object Delete { get; set; }
    }
    
    public class SaleOrderGetPromoCodeSuccessMessageRequestDto
    {
        public object Delete { get; set; }
    }
    
    public class SaleOrderLoadSaleOrderFromPosRequestDto
    {
        public Guid ConfigId { get; set; }
    }
    
    public class SaleOrderSetDeliveryLineRequestDto
    {
        public object Carrier { get; set; }
        public object Amount { get; set; }
    }
    
    public class SaleOrderViewInvoiceRequestDto
    {
        public object Invoices { get; set; }
    }
}