// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IBaseImportImportAppService : IGenericApplicationService<BaseImportImport>
    {
        Task<BaseImportImport> ExecuteImportAsync(Guid id, object fields, object columns, object options, object dryrun);
        Task<BaseImportImport> GetFieldsTreeAsync(Guid id, object model, object depth);
        Task<BaseImportImport> ParsePreviewAsync(Guid id, object options, object count);
    }
}