// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class LinkTrackerConvertLinksRequestDto
    {
        public object Html { get; set; }
        public object Vals { get; set; }
        public object Blacklist { get; set; }
    }
    
    public class LinkTrackerGetUrlFromCodeRequestDto
    {
        public object Code { get; set; }
    }
    
    public class LinkTrackerRecentLinksRequestDto
    {
        public object Filter { get; set; }
        public object Limit { get; set; }
    }
    
    public class LinkTrackerSearchOrCreateRequestDto
    {
        public object ValsList { get; set; }
    }
}