// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MailingMailingCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class MailingMailingFetchFavoritesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? ExtraDomain { get; set; }
    }
    
    public class MailingMailingSendMailRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? ResIds { get; set; }
    }
    
    public class MailingMailingSendSmsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? ResIds { get; set; }
    }
}