// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MailingContactAddToListRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Name { get; set; }
        public Guid? ListId { get; set; }
    }
}