// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MailingListCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class MailingListMergeRequestDto
    {
        public object SrcLists { get; set; }
        public object Archive { get; set; }
    }
}