// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SurveyQuestionValidateQuestionRequestDto
    {
        public object Answer { get; set; }
        public object Comment { get; set; }
    }
}