// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class GamificationChallengeReportProgressRequestDto
    {
        public object Users { get; set; }
        public object SubsetGoals { get; set; }
    }
}