// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class HrContractGenerateWorkEntriesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? DateStart { get; set; }
        public object? DateStop { get; set; }
        public object? Force { get; set; }
    }
    
    public class HrContractGetAttributeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Code { get; set; }
        public object? Attribute { get; set; }
    }
    
    public class HrContractSetAttributeValueRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Code { get; set; }
        public object? Active { get; set; }
    }
}