// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class HrJobCopyDataRequestDto
    {
        public object Default { get; set; }
    }
}