// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class HrLeaveAddFollowerRequestDto
    {
        public Guid EmployeeId { get; set; }
    }
    
    public class HrLeaveApproveRequestDto
    {
        public object CheckState { get; set; }
    }
    
    public class HrLeaveCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class HrLeaveGetUnusualDaysRequestDto
    {
        public object DateFrom { get; set; }
        public object DateTo { get; set; }
    }
    
    public class HrLeaveMessageSubscribeRequestDto
    {
        public List<Guid> PartnerIds { get; set; }
        public List<Guid> SubtypeIds { get; set; }
    }
    
    public class HrLeaveOpenRecordsRequestDto
    {
        public List<Guid> LeaveIds { get; set; }
    }
    
    public class HrLeaveValidateRequestDto
    {
        public object CheckState { get; set; }
    }
}