// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class HrVersionGenerateWorkEntriesRequestDto
    {
        public object DateStart { get; set; }
        public object DateStop { get; set; }
        public object Force { get; set; }
    }
    
    public class HrVersionGetFormviewActionRequestDto
    {
        public object AccessUid { get; set; }
    }
    
    public class HrVersionGetValuesFromContractTemplateRequestDto
    {
        public Guid ContractTemplateId { get; set; }
    }
}