// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class HrVersionGenerateWorkEntriesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? DateStart { get; set; }
        public object? DateStop { get; set; }
        public object? Force { get; set; }
    }
    
    public class HrVersionGetFormviewActionRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? AccessUid { get; set; }
    }
    
    public class HrVersionGetValuesFromContractTemplateRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? ContractTemplateId { get; set; }
    }
}