// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IPosConfigAppService : IGenericApplicationService<PosConfig>
    {
        Task<PosConfig> CloseKioskSessionAsync(Guid id);
        Task<PosConfig> ExecuteAsync(Guid id);
        Task<PosConfig> GetCategoriesAsync(Guid id, object categories);
        Task<PosConfig> GetKioskUrlAsync(Guid id);
        Task<PosConfig> GetLimitedPartnersLoadingAsync(Guid id);
        Task<PosConfig> GetLimitedProductCountAsync(Guid id);
        Task<PosConfig> GetLimitedProductsLoadingAsync(Guid id, object fields);
        Task<PosConfig> GetPosKanbanViewStateAsync(Guid id);
        Task<PosConfig> GetRecordsAsync(Guid id, object data);
        Task<PosConfig> InstallPosRestaurantAsync(Guid id);
        Task<PosConfig> LoadOnboardingBakeryScenarioAsync(Guid id);
        Task<PosConfig> LoadOnboardingBarScenarioAsync(Guid id);
        Task<PosConfig> LoadOnboardingClothesScenarioAsync(Guid id);
        Task<PosConfig> LoadOnboardingFurnitureScenarioAsync(Guid id);
        Task<PosConfig> LoadOnboardingKioskScenarioAsync(Guid id);
        Task<PosConfig> LoadOnboardingRestaurantScenarioAsync(Guid id);
        Task<PosConfig> LoadSelfDataAsync(Guid id);
        Task<PosConfig> NotifySynchronisationAsync(Guid id, Guid session_id, object login_number, object records);
        Task<PosConfig> OpenExistingSessionCbAsync(Guid id);
        Task<PosConfig> OpenOpenedRescueSessionFormAsync(Guid id);
        Task<PosConfig> OpenUiAsync(Guid id);
        Task<PosConfig> OpenWizardAsync(Guid id);
        Task<PosConfig> PosConfigModalEditAsync(Guid id);
        Task<PosConfig> PreviewSelfOrderAppAsync(Guid id);
        Task<PosConfig> ReadConfigOpenOrdersAsync(Guid id, object domain, List<Guid> record_ids);
        Task<PosConfig> UpdateCustomerDisplayAsync(Guid id, object order, object access_token);
        Task<PosConfig> UseCouponCodeAsync(Guid id, object code, object creation_date, Guid partner_id, Guid pricelist_id);
    }
}