// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResourceCalendarCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class ResourceCalendarGetWorkDurationDataRequestDto
    {
        public object FromDatetime { get; set; }
        public object ToDatetime { get; set; }
        public object ComputeLeaves { get; set; }
        public object Domain { get; set; }
    }
    
    public class ResourceCalendarGetWorkHoursCountRequestDto
    {
        public object StartDt { get; set; }
        public object EndDt { get; set; }
        public object ComputeLeaves { get; set; }
        public object Domain { get; set; }
    }
    
    public class ResourceCalendarPlanDaysRequestDto
    {
        public object Days { get; set; }
        public object DayDt { get; set; }
        public object ComputeLeaves { get; set; }
        public object Domain { get; set; }
    }
    
    public class ResourceCalendarPlanHoursRequestDto
    {
        public object Hours { get; set; }
        public object DayDt { get; set; }
        public object ComputeLeaves { get; set; }
        public object Domain { get; set; }
        public object Resource { get; set; }
    }
    
    public class ResourceCalendarTransferLeavesToRequestDto
    {
        public object OtherCalendar { get; set; }
        public object Resources { get; set; }
        public object FromDate { get; set; }
    }
}