// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountCashRoundingComputeDifferenceRequestDto
    {
        public object Currency { get; set; }
        public object Amount { get; set; }
    }
    
    public class AccountCashRoundingRoundRequestDto
    {
        public object Amount { get; set; }
    }
}