// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountAssetAssetComputeGeneratedEntriesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Date { get; set; }
        public object? AssetType { get; set; }
    }
    
    public class AccountAssetAssetCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class AccountAssetAssetOnchangeCategoryIdValuesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? CategoryId { get; set; }
    }
}