// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountMoveCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class AccountMoveGetCurrencyRateRequestDto
    {
        public Guid CompanyId { get; set; }
        public Guid ToCurrencyId { get; set; }
        public object Date { get; set; }
    }
    
    public class AccountMoveGetInboundTypesRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveGetInvoiceLocalisationFieldsRequiredToInvoiceRequestDto
    {
        public Guid CountryId { get; set; }
    }
    
    public class AccountMoveGetInvoiceTypesRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveGetOutboundTypesRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveGetPurchaseTypesRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveGetSaleTypesRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveIsInboundRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveIsInvoiceRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveIsOutboundRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveIsPurchaseDocumentRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveIsSaleDocumentRequestDto
    {
        public object IncludeReceipts { get; set; }
    }
    
    public class AccountMoveJsAssignOutstandingLineRequestDto
    {
        public Guid LineId { get; set; }
    }
    
    public class AccountMoveJsRemoveOutstandingPartialRequestDto
    {
        public Guid PartialId { get; set; }
    }
    
    public class AccountMoveMessageNewRequestDto
    {
        public object MsgDict { get; set; }
        public object CustomValues { get; set; }
    }
    
    public class AccountMoveProcessEdiWebServicesRequestDto
    {
        public object WithCommit { get; set; }
    }
}