// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountFiscalPositionAdjustValsCountryIdRequestDto
    {
        public object Vals { get; set; }
    }
    
    public class AccountFiscalPositionMapAccountRequestDto
    {
        public object Account { get; set; }
    }
    
    public class AccountFiscalPositionMapTaxRequestDto
    {
        public object Taxes { get; set; }
    }
    
    public class AccountFiscalPositionRaiseVatErrorMessageRequestDto
    {
        public object Country { get; set; }
    }
}