// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountBankStatementLineNewRequestDto
    {
        public object Values { get; set; }
        public object Origin { get; set; }
        public object Ref { get; set; }
    }
}