// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountTaxComputeAllRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? PriceUnit { get; set; }
        public object? Currency { get; set; }
        public object? Quantity { get; set; }
        public object? Product { get; set; }
        public object? Partner { get; set; }
        public object? IsRefund { get; set; }
        public object? HandlePriceInclude { get; set; }
        public object? IncludeCabaTags { get; set; }
        public object? RoundingMethod { get; set; }
    }
    
    public class AccountTaxCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class AccountTaxGetTaxTagsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? IsRefund { get; set; }
        public object? RepartitionType { get; set; }
    }
}