// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountCashRoundingComputeDifferenceRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Currency { get; set; }
        public object? Amount { get; set; }
    }
    
    public class AccountCashRoundingRoundRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
    }
}