// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SlideSlideCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class SlideSlideSetViewedRequestDto
    {
        public object QuizAttemptsInc { get; set; }
    }
}