// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SlideSlideCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class SlideSlideSetViewedRequestDto
    {
        public object QuizAttemptsInc { get; set; }
    }
}