// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SlideSlideCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class SlideSlideSetViewedRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? QuizAttemptsInc { get; set; }
    }
}