// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class WebsitePageClonePageRequestDto
    {
        public Guid PageId { get; set; }
        public object PageName { get; set; }
        public object CloneMenu { get; set; }
    }
    
    public class WebsitePageCopyDataRequestDto
    {
        public object Default { get; set; }
    }
}