using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using Bamboo.Core.Models;
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Application.Contracts.DTOs;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResPartnerAppService : IGenericApplicationService<ResPartner>
    {
        Task<ResPartner> AddressGetAsync(Guid id, ResPartnerAddressGetRequestDto input);
        Task<ResPartner> AutocompleteAsync(Guid id, ResPartnerAutocompleteRequestDto input);
        Task<ResPartner> AutocompleteByNameAsync(Guid id, ResPartnerAutocompleteByNameRequestDto input);
        Task<ResPartner> AutocompleteByVatAsync(Guid id, ResPartnerAutocompleteByVatRequestDto input);
        Task<ResPartner> ButtonAccountPeppolCheckPartnerEndpointAsync(Guid id, ResPartnerButtonAccountPeppolCheckPartnerEndpointRequestDto input);
        Task<ResPartner> CanEditVatAsync(Guid id);
        Task<ResPartner> CheckGstInAsync(Guid id, ResPartnerCheckGstInRequestDto input);
        Task<ResPartner> CheckVatAlAsync(Guid id, ResPartnerCheckVatAlRequestDto input);
        Task<ResPartner> CheckVatAsync(Guid id);
        Task<ResPartner> CheckVatBrAsync(Guid id, ResPartnerCheckVatBrRequestDto input);
        Task<ResPartner> CheckVatChAsync(Guid id, ResPartnerCheckVatChRequestDto input);
        Task<ResPartner> CheckVatCrAsync(Guid id, ResPartnerCheckVatCrRequestDto input);
        Task<ResPartner> CheckVatDeAsync(Guid id, ResPartnerCheckVatDeRequestDto input);
        Task<ResPartner> CheckVatEcAsync(Guid id, ResPartnerCheckVatEcRequestDto input);
        Task<ResPartner> CheckVatGrAsync(Guid id, ResPartnerCheckVatGrRequestDto input);
        Task<ResPartner> CheckVatHuAsync(Guid id, ResPartnerCheckVatHuRequestDto input);
        Task<ResPartner> CheckVatIdAsync(Guid id, ResPartnerCheckVatIdRequestDto input);
        Task<ResPartner> CheckVatIeAsync(Guid id, ResPartnerCheckVatIeRequestDto input);
        Task<ResPartner> CheckVatIlAsync(Guid id, ResPartnerCheckVatIlRequestDto input);
        Task<ResPartner> CheckVatInAsync(Guid id, ResPartnerCheckVatInRequestDto input);
        Task<ResPartner> CheckVatMaAsync(Guid id, ResPartnerCheckVatMaRequestDto input);
        Task<ResPartner> CheckVatMxAsync(Guid id, ResPartnerCheckVatMxRequestDto input);
        Task<ResPartner> CheckVatNoAsync(Guid id, ResPartnerCheckVatNoRequestDto input);
        Task<ResPartner> CheckVatPeAsync(Guid id, ResPartnerCheckVatPeRequestDto input);
        Task<ResPartner> CheckVatPhAsync(Guid id, ResPartnerCheckVatPhRequestDto input);
        Task<ResPartner> CheckVatRoAsync(Guid id, ResPartnerCheckVatRoRequestDto input);
        Task<ResPartner> CheckVatRuAsync(Guid id, ResPartnerCheckVatRuRequestDto input);
        Task<ResPartner> CheckVatSaAsync(Guid id, ResPartnerCheckVatSaRequestDto input);
        Task<ResPartner> CheckVatTAsync(Guid id, ResPartnerCheckVatTRequestDto input);
        Task<ResPartner> CheckVatTrAsync(Guid id, ResPartnerCheckVatTrRequestDto input);
        Task<ResPartner> CheckVatUaAsync(Guid id, ResPartnerCheckVatUaRequestDto input);
        Task<ResPartner> CheckVatUyAsync(Guid id, ResPartnerCheckVatUyRequestDto input);
        Task<ResPartner> CheckVatVeAsync(Guid id, ResPartnerCheckVatVeRequestDto input);
        Task<ResPartner> CheckVatVnAsync(Guid id, ResPartnerCheckVatVnRequestDto input);
        Task<ResPartner> CopyDataAsync(Guid id, ResPartnerCopyDataRequestDto input);
        Task<ResPartner> CreateCompanyAsync(Guid id);
        Task<ResPartner> CreateMembershipInvoiceAsync(Guid id, ResPartnerCreateMembershipInvoiceRequestDto input);
        Task<ResPartner> DoButtonPrintAsync(Guid id);
        Task<ResPartner> DoPartnerMailAsync(Guid id);
        Task<ResPartner> DoPartnerManualActionAsync(Guid id, ResPartnerDoPartnerManualActionRequestDto input);
        Task<ResPartner> DoPartnerManualDermanordAsync(Guid id, ResPartnerDoPartnerManualDermanordRequestDto input);
        Task<ResPartner> DoPartnerPrintAsync(Guid id, ResPartnerDoPartnerPrintRequestDto input);
        Task<ResPartner> DoneAsync(Guid id);
        Task<ResPartner> EnrichByDomainAsync(Guid id, ResPartnerEnrichByDomainRequestDto input);
        Task<ResPartner> EnrichByDunsAsync(Guid id, ResPartnerEnrichByDunsRequestDto input);
        Task<ResPartner> EnrichByGstAsync(Guid id, ResPartnerEnrichByGstRequestDto input);
        Task<ResPartner> EnrichCompanyAsync(Guid id, ResPartnerEnrichCompanyRequestDto input);
        Task<ResPartner> EventViewAsync(Guid id);
        Task<ResPartner> FieldsViewGetAsync(Guid id, ResPartnerFieldsViewGetRequestDto input);
        Task<ResPartner> FindOrCreateAsync(Guid id, ResPartnerFindOrCreateRequestDto input);
        Task<ResPartner> FixEuVatNumberAsync(Guid id, ResPartnerFixEuVatNumberRequestDto input);
        Task<ResPartner> FormatVatChAsync(Guid id, ResPartnerFormatVatChRequestDto input);
        Task<ResPartner> FormatVatEuAsync(Guid id, ResPartnerFormatVatEuRequestDto input);
        Task<ResPartner> FormatVatSmAsync(Guid id, ResPartnerFormatVatSmRequestDto input);
        Task<ResPartner> GeoLocalizeAsync(Guid id);
        Task<ResPartner> GetAttendeeDetailAsync(Guid id, ResPartnerGetAttendeeDetailRequestDto input);
        Task<ResPartner> GetBackendMenuIdAsync(Guid id);
        Task<ResPartner> GetFollowupTableHtmlAsync(Guid id);
        Task<ResPartner> GetImportTemplatesAsync(Guid id);
        Task<ResPartner> GetMentionSuggestionsAsync(Guid id, ResPartnerGetMentionSuggestionsRequestDto input);
        Task<ResPartner> GetMentionSuggestionsFromChannelAsync(Guid id, ResPartnerGetMentionSuggestionsFromChannelRequestDto input);
        Task<ResPartner> GetPartnerLocalisationFieldsRequiredToInvoiceAsync(Guid id, ResPartnerGetPartnerLocalisationFieldsRequiredToInvoiceRequestDto input);
        Task<ResPartner> GetWorkingHoursForAllAttendeesAsync(Guid id, ResPartnerGetWorkingHoursForAllAttendeesRequestDto input);
        Task<ResPartner> GetWorklocationAsync(Guid id, ResPartnerGetWorklocationRequestDto input);
        Task<ResPartner> GoogleMapImgAsync(Guid id, ResPartnerGoogleMapImgRequestDto input);
        Task<ResPartner> GoogleMapLinkAsync(Guid id, ResPartnerGoogleMapLinkRequestDto input);
        Task<ResPartner> IapPartnerAutocompleteAddTagsAsync(Guid id, ResPartnerIapPartnerAutocompleteAddTagsRequestDto input);
        Task<ResPartner> ImSearchAsync(Guid id, ResPartnerImSearchRequestDto input);
        Task<ResPartner> IsValidRucEcAsync(Guid id, ResPartnerIsValidRucEcRequestDto input);
        Task<ResPartner> OnchangeCompanyTypeAsync(Guid id);
        Task<ResPartner> OnchangeEmailAsync(Guid id);
        Task<ResPartner> OnchangeParentIdAsync(Guid id);
        Task<ResPartner> OpenBusinessDocAsync(Guid id);
        Task<ResPartner> OpenCommercialEntityAsync(Guid id);
        Task<ResPartner> OpenEmployeesAsync(Guid id);
        Task<ResPartner> PrivacyLookupAsync(Guid id);
        Task<ResPartner> ReadByVatAsync(Guid id, ResPartnerReadByVatRequestDto input);
        Task<ResPartner> ScheduleMeetingAsync(Guid id);
        Task<ResPartner> SearchForChannelInviteAsync(Guid id, ResPartnerSearchForChannelInviteRequestDto input);
        Task<ResPartner> SignupCancelAsync(Guid id);
        Task<ResPartner> SignupGetAuthParamAsync(Guid id);
        Task<ResPartner> SignupPrepareAsync(Guid id);
        Task<ResPartner> SignupPrepareAsync(Guid id, ResPartnerSignupPrepareRequestDto input);
        Task<ResPartner> SimpleVatCheckAsync(Guid id, ResPartnerSimpleVatCheckRequestDto input);
        Task<ResPartner> UpdateAddressAsync(Guid id, ResPartnerUpdateAddressRequestDto input);
        Task<ResPartner> ViewCertificationsAsync(Guid id);
        Task<ResPartner> ViewCoursesAsync(Guid id);
        Task<ResPartner> ViewHeaderGetAsync(Guid id, ResPartnerViewHeaderGetRequestDto input);
        Task<ResPartner> ViewLoyaltyCardsAsync(Guid id);
        Task<ResPartner> ViewOpportunityAsync(Guid id);
        Task<ResPartner> ViewPartnerInvoicesAsync(Guid id);
        Task<ResPartner> ViewPartnerWithSameBankAsync(Guid id);
        Task<ResPartner> ViewPosOrderAsync(Guid id);
        Task<ResPartner> ViewSaleOrderAsync(Guid id);
        Task<ResPartner> ViewStockLotsAsync(Guid id);
        Task<ResPartner> ViewTasksAsync(Guid id);
    }
}