using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Models;
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Application.Contracts.DTOs;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResPartnerAppService : IGenericAppService<ResPartner>
    {
        Task<ResPartner> AddressGetAsync(ResPartnerAddressGetRequestDto input);
        Task<ResPartner> AutocompleteByNameAsync(ResPartnerAutocompleteByNameRequestDto input);
        Task<ResPartner> AutocompleteByVatAsync(ResPartnerAutocompleteByVatRequestDto input);
        Task<ResPartner> ButtonAccountPeppolCheckPartnerEndpointAsync(ResPartnerButtonAccountPeppolCheckPartnerEndpointRequestDto input);
        Task<ResPartner> CanEditVatAsync(Guid[] ids);
        Task<ResPartner> CheckVatAlAsync(ResPartnerCheckVatAlRequestDto input);
        Task<ResPartner> CheckVatBrAsync(ResPartnerCheckVatBrRequestDto input);
        Task<ResPartner> CheckVatChAsync(ResPartnerCheckVatChRequestDto input);
        Task<ResPartner> CheckVatCrAsync(ResPartnerCheckVatCrRequestDto input);
        Task<ResPartner> CheckVatDeAsync(ResPartnerCheckVatDeRequestDto input);
        Task<ResPartner> CheckVatDoAsync(ResPartnerCheckVatDoRequestDto input);
        Task<ResPartner> CheckVatEcAsync(ResPartnerCheckVatEcRequestDto input);
        Task<ResPartner> CheckVatGrAsync(ResPartnerCheckVatGrRequestDto input);
        Task<ResPartner> CheckVatGtAsync(ResPartnerCheckVatGtRequestDto input);
        Task<ResPartner> CheckVatHuAsync(ResPartnerCheckVatHuRequestDto input);
        Task<ResPartner> CheckVatIdAsync(ResPartnerCheckVatIdRequestDto input);
        Task<ResPartner> CheckVatIeAsync(ResPartnerCheckVatIeRequestDto input);
        Task<ResPartner> CheckVatIlAsync(ResPartnerCheckVatIlRequestDto input);
        Task<ResPartner> CheckVatInAsync(ResPartnerCheckVatInRequestDto input);
        Task<ResPartner> CheckVatJpAsync(ResPartnerCheckVatJpRequestDto input);
        Task<ResPartner> CheckVatMaAsync(ResPartnerCheckVatMaRequestDto input);
        Task<ResPartner> CheckVatMxAsync(ResPartnerCheckVatMxRequestDto input);
        Task<ResPartner> CheckVatNoAsync(ResPartnerCheckVatNoRequestDto input);
        Task<ResPartner> CheckVatPeAsync(ResPartnerCheckVatPeRequestDto input);
        Task<ResPartner> CheckVatPhAsync(ResPartnerCheckVatPhRequestDto input);
        Task<ResPartner> CheckVatRoAsync(ResPartnerCheckVatRoRequestDto input);
        Task<ResPartner> CheckVatRsAsync(ResPartnerCheckVatRsRequestDto input);
        Task<ResPartner> CheckVatRuAsync(ResPartnerCheckVatRuRequestDto input);
        Task<ResPartner> CheckVatSaAsync(ResPartnerCheckVatSaRequestDto input);
        Task<ResPartner> CheckVatThAsync(ResPartnerCheckVatThRequestDto input);
        Task<ResPartner> CheckVatTrAsync(ResPartnerCheckVatTrRequestDto input);
        Task<ResPartner> CheckVatTwAsync(ResPartnerCheckVatTwRequestDto input);
        Task<ResPartner> CheckVatUaAsync(ResPartnerCheckVatUaRequestDto input);
        Task<ResPartner> CheckVatUyAsync(ResPartnerCheckVatUyRequestDto input);
        Task<ResPartner> CheckVatVeAsync(ResPartnerCheckVatVeRequestDto input);
        Task<ResPartner> CheckVatVnAsync(ResPartnerCheckVatVnRequestDto input);
        Task<ResPartner> CopyDataAsync(ResPartnerCopyDataRequestDto input);
        Task<ResPartner> CreateCompanyAsync(Guid[] ids);
        Task<ResPartner> DoButtonPrintAsync(Guid[] ids);
        Task<ResPartner> DoPartnerMailAsync(Guid[] ids);
        Task<ResPartner> DoPartnerManualActionAsync(ResPartnerDoPartnerManualActionRequestDto input);
        Task<ResPartner> DoPartnerManualDermanordAsync(ResPartnerDoPartnerManualDermanordRequestDto input);
        Task<ResPartner> DoPartnerPrintAsync(ResPartnerDoPartnerPrintRequestDto input);
        Task<ResPartner> DoneAsync(Guid[] ids);
        Task<ResPartner> EnrichByDomainAsync(ResPartnerEnrichByDomainRequestDto input);
        Task<ResPartner> EnrichByDunsAsync(ResPartnerEnrichByDunsRequestDto input);
        Task<ResPartner> EnrichByGstAsync(ResPartnerEnrichByGstRequestDto input);
        Task<ResPartner> EventViewAsync(Guid[] ids);
        Task<ResPartner> FieldsViewGetAsync(ResPartnerFieldsViewGetRequestDto input);
        Task<ResPartner> FindOrCreateAsync(ResPartnerFindOrCreateRequestDto input);
        Task<ResPartner> FormatVatChAsync(ResPartnerFormatVatChRequestDto input);
        Task<ResPartner> FormatVatClAsync(ResPartnerFormatVatClRequestDto input);
        Task<ResPartner> FormatVatCoAsync(ResPartnerFormatVatCoRequestDto input);
        Task<ResPartner> FormatVatEuAsync(ResPartnerFormatVatEuRequestDto input);
        Task<ResPartner> FormatVatHuAsync(ResPartnerFormatVatHuRequestDto input);
        Task<ResPartner> FormatVatSmAsync(ResPartnerFormatVatSmRequestDto input);
        Task<ResPartner> FormatVatVnAsync(ResPartnerFormatVatVnRequestDto input);
        Task<ResPartner> GeoLocalizeAsync(Guid[] ids);
        Task<ResPartner> GetAttendeeDetailAsync(ResPartnerGetAttendeeDetailRequestDto input);
        Task<ResPartner> GetBackendMenuIdAsync(Guid[] ids);
        Task<ResPartner> GetFollowupTableHtmlAsync(Guid[] ids);
        Task<ResPartner> GetImportTemplatesAsync(Guid[] ids);
        Task<ResPartner> GetMentionSuggestionsAsync(ResPartnerGetMentionSuggestionsRequestDto input);
        Task<ResPartner> GetMentionSuggestionsFromChannelAsync(ResPartnerGetMentionSuggestionsFromChannelRequestDto input);
        Task<ResPartner> GetNewPartnerAsync(ResPartnerGetNewPartnerRequestDto input);
        Task<ResPartner> GetPartnerLocalisationFieldsRequiredToInvoiceAsync(ResPartnerGetPartnerLocalisationFieldsRequiredToInvoiceRequestDto input);
        Task<ResPartner> GetWorkingHoursForAllAttendeesAsync(ResPartnerGetWorkingHoursForAllAttendeesRequestDto input);
        Task<ResPartner> GetWorklocationAsync(ResPartnerGetWorklocationRequestDto input);
        Task<ResPartner> GoogleMapImgAsync(ResPartnerGoogleMapImgRequestDto input);
        Task<ResPartner> GoogleMapLinkAsync(ResPartnerGoogleMapLinkRequestDto input);
        Task<ResPartner> IapPartnerAutocompleteGetTagIdsAsync(ResPartnerIapPartnerAutocompleteGetTagIdsRequestDto input);
        Task<ResPartner> IsValidRucEcAsync(ResPartnerIsValidRucEcRequestDto input);
        Task<ResPartner> OnchangeCompanyTypeAsync(Guid[] ids);
        Task<ResPartner> OnchangeParentIdAsync(Guid[] ids);
        Task<ResPartner> OpenBusinessDocAsync(Guid[] ids);
        Task<ResPartner> OpenCommercialEntityAsync(Guid[] ids);
        Task<ResPartner> OpenEmployeesAsync(Guid[] ids);
        Task<ResPartner> PrivacyLookupAsync(Guid[] ids);
        Task<ResPartner> ScheduleMeetingAsync(Guid[] ids);
        Task<ResPartner> SearchForChannelInviteAsync(ResPartnerSearchForChannelInviteRequestDto input);
        Task<ResPartner> SignupCancelAsync(Guid[] ids);
        Task<ResPartner> SignupGetAuthParamAsync(Guid[] ids);
        Task<ResPartner> SignupPrepareAsync(Guid[] ids);
        Task<ResPartner> SignupPrepareAsync(ResPartnerSignupPrepareRequestDto input);
        Task<ResPartner> ViewCertificationsAsync(Guid[] ids);
        Task<ResPartner> ViewCoursesAsync(Guid[] ids);
        Task<ResPartner> ViewHeaderGetAsync(ResPartnerViewHeaderGetRequestDto input);
        Task<ResPartner> ViewLivechatSessionsAsync(Guid[] ids);
        Task<ResPartner> ViewLoyaltyCardsAsync(Guid[] ids);
        Task<ResPartner> ViewOpportunityAsync(Guid[] ids);
        Task<ResPartner> ViewPartnerInvoicesAsync(Guid[] ids);
        Task<ResPartner> ViewPosOrderAsync(Guid[] ids);
        Task<ResPartner> ViewStockSerialAsync(Guid[] ids);
        Task<ResPartner> ViewTasksAsync(Guid[] ids);
    }
}