using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Models;
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Application.Contracts.DTOs;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResUsersAppService : IGenericAppService<ResUsers>
    {
        Task<ResUsers> ApiKeyWizardAsync(Guid[] ids);
        Task<ResUsers> ArchiveAsync(Guid[] ids);
        Task<ResUsers> AuthOauthAsync(ResUsersAuthOauthRequestDto input);
        Task<ResUsers> AuthenticateAsync(ResUsersAuthenticateRequestDto input);
        Task<ResUsers> ChangePasswordAsync(ResUsersChangePasswordRequestDto input);
        Task<ResUsers> ChangePasswordWizardAsync(Guid[] ids);
        Task<ResUsers> CheckCalendarCredentialsAsync(Guid[] ids);
        Task<ResUsers> CheckSynchronizationStatusAsync(Guid[] ids);
        Task<ResUsers> ContextGetAsync(Guid[] ids);
        Task<ResUsers> CopyDataAsync(ResUsersCopyDataRequestDto input);
        Task<ResUsers> CreateEmployeeAsync(Guid[] ids);
        Task<ResUsers> CreatePasskeyAsync(Guid[] ids);
        Task<ResUsers> GetAsync(Guid[] ids);
        Task<ResUsers> GetCompanyCurrencyIdAsync(Guid[] ids);
        Task<ResUsers> GetFormviewActionAsync(ResUsersGetFormviewActionRequestDto input);
        Task<ResUsers> GetGamificationRedirectionDataAsync(Guid[] ids);
        Task<ResUsers> GetPasswordPolicyAsync(Guid[] ids);
        Task<ResUsers> GetSelectedCalendarsPartnerIdsAsync(ResUsersGetSelectedCalendarsPartnerIdsRequestDto input);
        Task<ResUsers> GetTotpInviteUrlAsync(Guid[] ids);
        Task<ResUsers> GetViewAsync(ResUsersGetViewRequestDto input);
        Task<ResUsers> GetViewsAsync(ResUsersGetViewsRequestDto input);
        Task<bool> HasGroupAsync(ResUsersHasGroupRequestDto input);
        Task<bool> HasGroupsAsync(ResUsersHasGroupsRequestDto input);
        Task<ResUsers> InitAsync(Guid[] ids);
        Task<ResUsers> IsGoogleCalendarSyncedAsync(Guid[] ids);
        Task<ResUsers> KarmaReportAsync(Guid[] ids);
        Task<ResUsers> NewAsync(ResUsersNewRequestDto input);
        Task<ResUsers> OnChangeLoginAsync(Guid[] ids);
        Task<ResUsers> OnchangeParentIdAsync(Guid[] ids);
        Task<ResUsers> OpenEmployeesAsync(Guid[] ids);
        Task<ResUsers> OpenMyAccountSettingsAsync(Guid[] ids);
        Task<ResUsers> OpenWebsiteUrlAsync(Guid[] ids);
        Task<ResUsers> PauseGoogleSynchronizationAsync(Guid[] ids);
        Task<ResUsers> PauseMicrosoftSynchronizationAsync(Guid[] ids);
        Task<ResUsers> PreferenceChangePasswordAsync(Guid[] ids);
        Task<ResUsers> PreferenceSaveAsync(Guid[] ids);
        Task<ResUsers> RelatedContactAsync(Guid[] ids);
        Task<ResUsers> RemoveOauthAccessTokenAsync(Guid[] ids);
        Task<ResUsers> ResetPasswordAsync(ResUsersResetPasswordRequestDto input);
        Task<ResUsers> ResetPasswordAsync(Guid[] ids);
        Task<ResUsers> RestartGoogleSynchronizationAsync(Guid[] ids);
        Task<ResUsers> RestartMicrosoftSynchronizationAsync(Guid[] ids);
        Task<ResUsers> RevokeAllDevicesAsync(Guid[] ids);
        Task<ResUsers> RevokeAllDevicesActionAsync(Guid[] ids);
        Task<ResUsers> SELFREADABLEFIELDSAsync(Guid[] ids);
        Task<ResUsers> SELFWRITEABLEFIELDSAsync(Guid[] ids);
        Task<ResUsers> SendUnregisteredUserReminderAsync(Guid[] ids);
        Task<ResUsers> SetupOutgoingMailServerAsync(ResUsersSetupOutgoingMailServerRequestDto input);
        Task<ResUsers> ShowAccessesAsync(Guid[] ids);
        Task<ResUsers> ShowGroupsAsync(Guid[] ids);
        Task<ResUsers> ShowRulesAsync(Guid[] ids);
        Task<ResUsers> SignupAsync(ResUsersSignupRequestDto input);
        Task<ResUsers> StopGoogleSynchronizationAsync(Guid[] ids);
        Task<ResUsers> StopMicrosoftSynchronizationAsync(Guid[] ids);
        Task<ResUsers> SwitchTourEnabledAsync(ResUsersSwitchTourEnabledRequestDto input);
        Task<ResUsers> TestOutgoingMailServerAsync(Guid[] ids);
        Task<ResUsers> TotpDisableAsync(Guid[] ids);
        Task<ResUsers> TotpEnableWizardAsync(Guid[] ids);
        Task<ResUsers> TotpInviteAsync(Guid[] ids);
        Task<ResUsers> UnpauseGoogleSynchronizationAsync(Guid[] ids);
        Task<ResUsers> UnpauseMicrosoftSynchronizationAsync(Guid[] ids);
        Task<ResUsers> WebCreateUsersAsync(ResUsersWebCreateUsersRequestDto input);
        Task<ResUsers> WebsitePublishButtonAsync(Guid[] ids);
    }
}