using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Models;
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Application.Contracts.DTOs;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResConfigSettingsAppService : IGenericApplicationService<ResConfigSettings>
    {
        Task<ResConfigSettings> ActivateStripeAsync(Guid id);
        Task<ResConfigSettings> ButtonAccountPeppolConfigureServicesAsync(Guid id);
        Task<ResConfigSettings> ButtonDeregisterPeppolParticipantAsync(Guid id);
        Task<ResConfigSettings> ButtonMigratePeppolRegistrationAsync(Guid id);
        Task<ResConfigSettings> ButtonPeppolSmpRegistrationAsync(Guid id);
        Task<ResConfigSettings> ButtonUpdatePeppolUserDataAsync(Guid id);
        Task<ResConfigSettings> CancelAsync(Guid id);
        Task<ResConfigSettings> ConfigureFirstProviderAsync(Guid id);
        Task<ResConfigSettings> CrmAssignLeadsAsync(Guid id);
        Task<ResConfigSettings> CustomLinkActionAsync(Guid id);
        Task<ResConfigSettings> EditExternalHeaderAsync(Guid id);
        Task<ResConfigSettings> ExecuteAsync(Guid id);
        Task<ResConfigSettings> GenerateQrCodesPageAsync(Guid id);
        Task<ResConfigSettings> GenerateQrCodesZipAsync(Guid id);
        Task<ResConfigSettings> GetConfigWarningAsync(Guid id, ResConfigSettingsGetConfigWarningRequestDto input);
        Task<ResConfigSettings> GetOptionNameAsync(Guid id, ResConfigSettingsGetOptionNameRequestDto input);
        Task<ResConfigSettings> GetOptionPathAsync(Guid id, ResConfigSettingsGetOptionPathRequestDto input);
        Task<ResConfigSettings> GetUriAsync(Guid id);
        Task<ResConfigSettings> GetValuesAsync(Guid id);
        Task<ResConfigSettings> OnchangeAdvLocationAsync(Guid id);
        Task<ResConfigSettings> OnchangeAnalyticAccountingAsync(Guid id);
        Task<ResConfigSettings> OnchangeModuleAccountBudgetAsync(Guid id);
        Task<ResConfigSettings> OnchangeModuleAsync(Guid id, ResConfigSettingsOnchangeModuleRequestDto input);
        Task<ResConfigSettings> OpenAbandonedCartMailTemplateAsync(Guid id);
        Task<ResConfigSettings> OpenBlockedThirdPartyDomainsAsync(Guid id);
        Task<ResConfigSettings> OpenCompanyAsync(Guid id);
        Task<ResConfigSettings> OpenDefaultUserAsync(Guid id);
        Task<ResConfigSettings> OpenEmailLayoutAsync(Guid id);
        Task<ResConfigSettings> OpenExtraInfoAsync(Guid id);
        Task<ResConfigSettings> OpenFollowupLevelFormAsync(Guid id);
        Task<ResConfigSettings> OpenMailTemplatesAsync(Guid id);
        Task<ResConfigSettings> OpenPeppolFormAsync(Guid id);
        Task<ResConfigSettings> OpenRobotsAsync(Guid id);
        Task<ResConfigSettings> OpenSaleMailTemplatesAsync(Guid id);
        Task<ResConfigSettings> OpenTemplateUserAsync(Guid id);
        Task<ResConfigSettings> PosConfigCreateNewAsync(Guid id);
        Task<ResConfigSettings> PosOpenUiAsync(Guid id);
        Task<ResConfigSettings> PreviewSelfOrderAppAsync(Guid id);
        Task<ResConfigSettings> RedirectToBuyAutocompleteCreditAsync(Guid id);
        Task<ResConfigSettings> RegenerateKioskKeyAsync(Guid id);
        Task<ResConfigSettings> ReloadTemplateAsync(Guid id);
        Task<ResConfigSettings> RemoveAccountAsync(Guid id);
        Task<ResConfigSettings> RemoveAccountChartAsync(Guid id);
        Task<ResConfigSettings> RemoveAllAsync(Guid id);
        Task<ResConfigSettings> RemoveDataAsync(Guid id, ResConfigSettingsRemoveDataRequestDto input);
        Task<ResConfigSettings> RemoveExpenseAsync(Guid id);
        Task<ResConfigSettings> RemoveInventoryAsync(Guid id);
        Task<ResConfigSettings> RemoveMessageAsync(Guid id);
        Task<ResConfigSettings> RemoveMrpAsync(Guid id);
        Task<ResConfigSettings> RemoveMrpBomAsync(Guid id);
        Task<ResConfigSettings> RemovePosAsync(Guid id);
        Task<ResConfigSettings> RemoveProductAsync(Guid id);
        Task<ResConfigSettings> RemoveProductAttributeAsync(Guid id);
        Task<ResConfigSettings> RemoveProjectAsync(Guid id);
        Task<ResConfigSettings> RemovePurchaseAsync(Guid id);
        Task<ResConfigSettings> RemoveQualityAsync(Guid id);
        Task<ResConfigSettings> RemoveQualitySettingAsync(Guid id);
        Task<ResConfigSettings> RemoveSalesAsync(Guid id);
        Task<ResConfigSettings> RemoveWebsiteAsync(Guid id);
        Task<ResConfigSettings> ResetCatLocNameAsync(Guid id);
        Task<ResConfigSettings> SetValuesAsync(Guid id);
        Task<ResConfigSettings> UpdateAccessTokensAsync(Guid id);
        Task<ResConfigSettings> UpdateTermsAsync(Guid id);
        Task<ResConfigSettings> ViewInStoreDeliveryMethodsAsync(Guid id);
        Task<ResConfigSettings> WebsiteCreateNewAsync(Guid id);
    }
}