<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.0-rc.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="10.0.0-rc.2" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.0.0-rc.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bamboo.Shared.Common\Bamboo.Shared.Common.csproj" />
  </ItemGroup>

</Project>
