// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface ILoyaltyProgramAppService : IGenericApplicationService<LoyaltyProgram>
    {
        Task<LoyaltyProgram> CreateFromTemplateAsync(Guid id, Guid template_id);
        Task<LoyaltyProgram> GetProgramTemplatesAsync(Guid id);
        Task<LoyaltyProgram> OpenLoyaltyCardsAsync(Guid id);
        Task<LoyaltyProgram> ProgramShareAsync(Guid id);
        Task<LoyaltyProgram> ToggleActiveAsync(Guid id);
    }
}