// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface ICrossoveredBudgetAppService : IGenericApplicationService<CrossoveredBudget>
    {
        Task<CrossoveredBudget> BudgetCancelAsync(Guid id);
        Task<CrossoveredBudget> BudgetConfirmAsync(Guid id);
        Task<CrossoveredBudget> BudgetDoneAsync(Guid id);
        Task<CrossoveredBudget> BudgetDraftAsync(Guid id);
        Task<CrossoveredBudget> BudgetValidateAsync(Guid id);
    }
}