// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface ISmsSmsAppService : IGenericApplicationService<SmsSms>
    {
        Task<SmsSms> ResendFailedAsync(Guid id);
        Task<SmsSms> SendAsync(Guid id, object unlink_failed, object unlink_sent, object auto_commit, object raise_exception);
        Task<SmsSms> SetCanceledAsync(Guid id);
        Task<SmsSms> SetErrorAsync(Guid id, object failure_type);
        Task<SmsSms> SetOutgoingAsync(Guid id);
    }
}