// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResourceCalendarAppService : IGenericApplicationService<ResourceCalendar>
    {
        Task<ResourceCalendar> CopyDataAsync(Guid id, object @default);
        Task<ResourceCalendar> GetWorkDurationDataAsync(Guid id, object from_datetime, object to_datetime, object compute_leaves, object domain);
        Task<ResourceCalendar> GetWorkHoursCountAsync(Guid id, object start_dt, object end_dt, object compute_leaves, object domain);
        Task<ResourceCalendar> OpenContractsAsync(Guid id);
        Task<ResourceCalendar> PlanDaysAsync(Guid id, object days, object day_dt, object compute_leaves, object domain);
        Task<ResourceCalendar> PlanHoursAsync(Guid id, object hours, object day_dt, object compute_leaves, object domain, object resource);
        Task<ResourceCalendar> SwitchCalendarTypeAsync(Guid id);
        Task<ResourceCalendar> TransferLeavesToAsync(Guid id, object other_calendar, object resources, object from_date);
    }
}