// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IIrActionsServerAppService : IGenericApplicationService<IrActServer>
    {
        Task<IrActServer> CopyDataAsync(Guid id, object @default);
        Task<IrActServer> CreateActionAsync(Guid id);
        Task<IrActServer> RunAsync(Guid id);
        Task<IrActServer> UnlinkActionAsync(Guid id);
    }
}