// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IIrFiltersAppService : IGenericApplicationService<IrFilters>
    {
        Task<IrFilters> CopyDataAsync(Guid id, object @default);
        Task<IrFilters> CreateOrReplaceAsync(Guid id, object vals);
        Task<IrFilters> GetFiltersAsync(Guid id, object model, Guid action_id, Guid embedded_action_id, Guid embedded_parent_res_id);
    }
}