// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResCurrencyAppService : IGenericApplicationService<ResCurrency>
    {
        Task<ResCurrency> AmountToTextAsync(Guid id, object amount);
        Task<ResCurrency> CompareAmountsAsync(Guid id, object amount1, object amount2);
        Task<ResCurrency> FormatAsync(Guid id, object amount);
        Task<ResCurrency> GetCompanyCurrencyForSpreadsheetAsync(Guid id, Guid company_id);
        Task<ResCurrency> IsZeroAsync(Guid id, object amount);
        Task<ResCurrency> RoundAsync(Guid id, object amount);
    }
}