// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IResCompanyAppService : IGenericApplicationService<ResCompany>
    {
        Task<ResCompany> AllCompanyBranchesAsync(Guid id);
        Task<ResCompany> CacheInvalidationFieldsAsync(Guid id);
        Task<ResCompany> ComputeAccountTaxFiscalCountryAsync(Guid id);
        Task<ResCompany> ComputeFiscalyearDatesAsync(Guid id, object current_date);
        Task<ResCompany> CreateMissingDropshipPickingTypeAsync(Guid id);
        Task<ResCompany> CreateMissingDropshipRuleAsync(Guid id);
        Task<ResCompany> CreateMissingDropshipSequenceAsync(Guid id);
        Task<ResCompany> CreateMissingInventoryLossLocationAsync(Guid id);
        Task<ResCompany> CreateMissingProductionLocationAsync(Guid id);
        Task<ResCompany> CreateMissingScrapLocationAsync(Guid id);
        Task<ResCompany> CreateMissingScrapSequenceAsync(Guid id);
        Task<ResCompany> CreateMissingTransitLocationAsync(Guid id);
        Task<ResCompany> CreateMissingUnbuildSequencesAsync(Guid id);
        Task<ResCompany> CreateMissingWarehouseAsync(Guid id);
        Task<ResCompany> GetChartOfAccountsOrFailAsync(Guid id);
        Task<ResCompany> GetFiscalDatesAsync(Guid id, object payload);
        Task<ResCompany> GetL10nDeStnrNationalAsync(Guid id);
        Task<ResCompany> GetNewAccountCodeAsync(Guid id, object current_code, object old_prefix, object new_prefix);
        Task<ResCompany> GetNextBatchPaymentCommunicationAsync(Guid id);
        Task<ResCompany> GetUnaffectedEarningsAccountAsync(Guid id);
        Task<ResCompany> GoogleMapImgAsync(Guid id, object zoom, object width, object height);
        Task<ResCompany> GoogleMapLinkAsync(Guid id, object zoom);
        Task<ResCompany> IapEnrichAutoAsync(Guid id);
        Task<ResCompany> InitAsync(Guid id);
        Task<ResCompany> InstallL10nModulesAsync(Guid id);
        Task<ResCompany> OnchangeCountryAsync(Guid id);
        Task<ResCompany> OpenWebsiteThemeSelectorAsync(Guid id);
        Task<ResCompany> OpeningMovePostedAsync(Guid id);
        Task<ResCompany> ReflectCodePrefixChangeAsync(Guid id, object old_code, object new_code);
        Task<ResCompany> SaveOnboardingCompanyDataAsync(Guid id);
        Task<ResCompany> SaveOnboardingSaleTaxAsync(Guid id);
        Task<ResCompany> SettingInitBankAccountActionAsync(Guid id);
        Task<ResCompany> UpdateStateAsPerGstinAsync(Guid id);
        Task<ResCompany> ValidateLockDatesAsync(Guid id);
    }
}