// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IWebsitePageAppService : IGenericApplicationService<WebsitePage>
    {
        Task<WebsitePage> ClonePageAsync(Guid id, Guid page_id, object page_name, object clone_menu);
        Task<WebsitePage> CopyDataAsync(Guid id, object @default);
        Task<WebsitePage> GetWebsiteMetaAsync(Guid id);
        Task<WebsitePage> PageDebugViewAsync(Guid id);
    }
}