// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IWebsiteMenuAppService : IGenericApplicationService<WebsiteMenu>
    {
        Task<WebsiteMenu> GetTreeAsync(Guid id, Guid website_id, Guid menu_id);
        Task<WebsiteMenu> SaveAsync(Guid id, Guid website_id, object data);
    }
}