// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IHrApplicantAppService : IGenericApplicationService<HrApplicant>
    {
        Task<HrApplicant> ArchiveApplicantAsync(Guid id);
        Task<HrApplicant> CreateEmployeeFromApplicantAsync(Guid id);
        Task<HrApplicant> CreateMeetingAsync(Guid id);
        Task<HrApplicant> GetEmptyListHelpAsync(Guid id, object help_message);
        Task<HrApplicant> GetViewAsync(Guid id, Guid view_id, object view_type);
        Task<HrApplicant> InitAsync(Guid id);
        Task<HrApplicant> MessageNewAsync(Guid id, object msg, object custom_values);
        Task<HrApplicant> OpenAttachmentsAsync(Guid id);
        Task<HrApplicant> OpenEmployeeAsync(Guid id);
        Task<HrApplicant> OpenOtherApplicationsAsync(Guid id);
        Task<HrApplicant> PrintSurveyAsync(Guid id);
        Task<HrApplicant> ResetApplicantAsync(Guid id);
        Task<HrApplicant> SendEmailAsync(Guid id);
        Task<HrApplicant> SendSurveyAsync(Guid id);
        Task<HrApplicant> ToggleActiveAsync(Guid id);
        Task<HrApplicant> WebsiteFormInputFilterAsync(Guid id, object request, object values);
    }
}