// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface ISaleOrderAppService : IGenericApplicationService<SaleOrder>
    {
        Task<SaleOrder> CancelAsync(Guid id);
        Task<SaleOrder> ComputePaymentReferenceFinnishAsync(Guid id, object number);
        Task<SaleOrder> ConfirmAsync(Guid id);
        Task<SaleOrder> CopyDataAsync(Guid id, object @default);
        Task<SaleOrder> CreateDocumentFromAttachmentAsync(Guid id, List<Guid> attachment_ids);
        Task<SaleOrder> CreateProjectAsync(Guid id);
        Task<SaleOrder> DraftAsync(Guid id);
        Task<SaleOrder> GetEmptyListHelpAsync(Guid id, object help_msg);
        Task<SaleOrder> GetFinnishCheckDigitAsync(Guid id, object base_number);
        Task<SaleOrder> GetPortalLastTransactionAsync(Guid id);
        Task<SaleOrder> GetPromoCodeErrorAsync(Guid id, object delete);
        Task<SaleOrder> GetPromoCodeSuccessMessageAsync(Guid id, object delete);
        Task<SaleOrder> GetReportMatrixesAsync(Guid id);
        Task<SaleOrder> GetUpdateIncludedPdfParamsAsync(Guid id);
        Task<SaleOrder> InitAsync(Guid id);
        Task<SaleOrder> LockAsync(Guid id);
        Task<SaleOrder> MessagePostAsync(Guid id);
        Task<SaleOrder> Number2numericAsync(Guid id, object number);
        Task<SaleOrder> OnchangeOrderLineAsync(Guid id);
        Task<SaleOrder> OpenBusinessDocAsync(Guid id);
        Task<SaleOrder> OpenDeclarationOfIntentAsync(Guid id);
        Task<SaleOrder> OpenDeliveryWizardAsync(Guid id);
        Task<SaleOrder> OpenDiscountWizardAsync(Guid id);
        Task<SaleOrder> OpenRewardWizardAsync(Guid id);
        Task<SaleOrder> PaymentCaptureAsync(Guid id);
        Task<SaleOrder> PaymentVoidAsync(Guid id);
        Task<SaleOrder> PreviewSaleOrderAsync(Guid id);
        Task<SaleOrder> QuotationSendAsync(Guid id);
        Task<SaleOrder> QuotationSentAsync(Guid id);
        Task<SaleOrder> RecoveryEmailSendAsync(Guid id);
        Task<SaleOrder> SaveIncludedPdfAsync(Guid id, object selected_pdf);
        Task<SaleOrder> SaveNewCustomContentAsync(Guid id, object document_type, object form_field, object content);
        Task<SaleOrder> SetDeliveryLineAsync(Guid id, object carrier, object amount);
        Task<SaleOrder> ShowRepairAsync(Guid id);
        Task<SaleOrder> UnlockAsync(Guid id);
        Task<SaleOrder> UpdatePricesAsync(Guid id);
        Task<SaleOrder> UpdateTaxesAsync(Guid id);
        Task<SaleOrder> ViewAttendeeListAsync(Guid id);
        Task<SaleOrder> ViewBoothListAsync(Guid id);
        Task<SaleOrder> ViewDeliveryAsync(Guid id);
        Task<SaleOrder> ViewDropshipAsync(Guid id);
        Task<SaleOrder> ViewInvoiceAsync(Guid id, object invoices);
        Task<SaleOrder> ViewMilestoneAsync(Guid id);
        Task<SaleOrder> ViewMrpProductionAsync(Guid id);
        Task<SaleOrder> ViewPosOrderAsync(Guid id);
        Task<SaleOrder> ViewProjectIdsAsync(Guid id);
        Task<SaleOrder> ViewPurchaseOrdersAsync(Guid id);
        Task<SaleOrder> ViewTaskAsync(Guid id);
        Task<SaleOrder> ViewTimesheetAsync(Guid id);
    }
}