// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IRecurringPaymentAppService : IGenericApplicationService<RecurringPayment>
    {
        Task<RecurringPayment> ComputeNextDateAsync(Guid id, object date);
        Task<RecurringPayment> CreateLinesAsync(Guid id, object date);
        Task<RecurringPayment> DoneAsync(Guid id);
        Task<RecurringPayment> DraftAsync(Guid id);
        Task<RecurringPayment> GeneratePaymentAsync(Guid id);
    }
}