// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProcurementGroupRunRequestDto
    {
        public object Procurements { get; set; }
        public object RaiseUserError { get; set; }
    }
    
    public class ProcurementGroupRunSchedulerRequestDto
    {
        public object UseNewCursor { get; set; }
        public Guid CompanyId { get; set; }
    }
}