// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MailGroupMessageNewRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? MsgDict { get; set; }
        public object? CustomValues { get; set; }
    }
    
    public class MailGroupMessagePostRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Body { get; set; }
        public object? Subject { get; set; }
        public object? EmailFrom { get; set; }
        public Guid? AuthorId { get; set; }
    }
    
    public class MailGroupMessageUpdateRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? MsgDict { get; set; }
        public object? UpdateVals { get; set; }
    }
    
    public class MailGroupSendGuidelinesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Members { get; set; }
    }
}