// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResourceCalendarAttendanceGetWeekTypeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Date { get; set; }
    }
}