<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Bamboo.Admin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bamboo.Admin.Domain\Bamboo.Admin.Domain.csproj" />
    <ProjectReference Include="..\Bamboo.Admin.TestBase\Bamboo.Admin.TestBase.csproj" />
  </ItemGroup>

</Project>
