// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAuthPasskeyKeyAppService : IGenericApplicationService<AuthPasskeyKey>
    {
        Task<AuthPasskeyKey> DeletePasskeyAsync(Guid id);
        Task<AuthPasskeyKey> InitAsync(Guid id);
        Task<AuthPasskeyKey> RenamePasskeyAsync(Guid id);
    }
}