// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MrpBomExplodeRequestDto
    {
        public object Product { get; set; }
        public object Quantity { get; set; }
        public object PickingType { get; set; }
        public object NeverAttributeValues { get; set; }
    }
}