// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MrpWorkorderButtonStartRequestDto
    {
        public object RaiseOnInvalidState { get; set; }
    }
    
    public class MrpWorkorderEndPreviousRequestDto
    {
        public object Doall { get; set; }
    }
}