// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IPhoneBlacklistAppService : IGenericApplicationService<PhoneBlacklist>
    {
        Task<PhoneBlacklist> AddAsync(Guid id, object number, object message);
        Task<PhoneBlacklist> AddAsync(Guid id);
        Task<PhoneBlacklist> PhoneBlacklistRemoveAsync(Guid id);
        Task<PhoneBlacklist> RemoveAsync(Guid id, object number, object message);
    }
}