// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AuthPasskeyKeyCreateMakeKeyRequestDto
    {
        public object Registration { get; set; }
    }
}