// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class BarcodeNomenclatureGs1DateToDateRequestDto
    {
        public object Gs1Date { get; set; }
    }
    
    public class BarcodeNomenclatureGs1DecomposeExtandedRequestDto
    {
        public object Barcode { get; set; }
    }
    
    public class BarcodeNomenclatureMatchPatternRequestDto
    {
        public object Barcode { get; set; }
        public object Pattern { get; set; }
    }
    
    public class BarcodeNomenclatureParseBarcodeRequestDto
    {
        public object Barcode { get; set; }
    }
    
    public class BarcodeNomenclatureParseGs1RulePatternRequestDto
    {
        public object Match { get; set; }
        public object Rule { get; set; }
    }
    
    public class BarcodeNomenclatureParseNomenclatureBarcodeRequestDto
    {
        public object Barcode { get; set; }
    }
    
    public class BarcodeNomenclatureParseUriRequestDto
    {
        public object Barcode { get; set; }
    }
    
    public class BarcodeNomenclatureSanitizeEanRequestDto
    {
        public object Ean { get; set; }
    }
    
    public class BarcodeNomenclatureSanitizeUpcRequestDto
    {
        public object Upc { get; set; }
    }
}