// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class BusPresenceUpdatePresenceRequestDto
    {
        public object InactivityPeriod { get; set; }
        public object IdentityField { get; set; }
        public object IdentityValue { get; set; }
    }
}