// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrAttachmentCheckRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Mode { get; set; }
        public object? Values { get; set; }
    }
    
    public class IrAttachmentCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class IrAttachmentCreateUniqueRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? ValuesList { get; set; }
    }
    
    public class IrAttachmentRegisterAsMainAttachmentRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Force { get; set; }
    }
}