// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrAttachmentCheckRequestDto
    {
        public object Mode { get; set; }
        public object Values { get; set; }
    }
    
    public class IrAttachmentCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class IrAttachmentCreateUniqueRequestDto
    {
        public object ValuesList { get; set; }
    }
    
    public class IrAttachmentRegisterAsMainAttachmentRequestDto
    {
        public object Force { get; set; }
    }
    
    public class IrAttachmentValidateAccessRequestDto
    {
        public object AccessToken { get; set; }
    }
}