// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrCronToggleRequestDto
    {
        public object Model { get; set; }
        public object Domain { get; set; }
    }
    
    public class IrCronTryWriteRequestDto
    {
        public object Values { get; set; }
    }
}