// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrCronToggleRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Model { get; set; }
        public object? Domain { get; set; }
    }
    
    public class IrCronTryWriteRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Values { get; set; }
    }
}