// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrMailServerSendEmailRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Message { get; set; }
        public Guid? MailServerId { get; set; }
        public object? SmtpServer { get; set; }
        public object? SmtpPort { get; set; }
        public object? SmtpUser { get; set; }
        public object? SmtpPassword { get; set; }
        public object? SmtpEncryption { get; set; }
        public object? SmtpSslCertificate { get; set; }
        public object? SmtpSslPrivateKey { get; set; }
        public object? SmtpDebug { get; set; }
        public object? SmtpSession { get; set; }
    }
    
    public class IrMailServerTestSmtpConnectionRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? AutodetectMaxEmailSize { get; set; }
    }
}