// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrModelDataCheckObjectReferenceRequestDto
    {
        public object Module { get; set; }
        public Guid XmlId { get; set; }
        public object RaiseOnAccessError { get; set; }
    }
    
    public class IrModelDataCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class IrModelDataToggleNoupdateRequestDto
    {
        public object Model { get; set; }
        public Guid ResId { get; set; }
    }
}