// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrModuleModuleCheckExternalDependenciesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? ModuleName { get; set; }
        public object? Newstate { get; set; }
    }
    
    public class IrModuleModuleDownstreamDependenciesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? KnownDeps { get; set; }
        public object? ExcludeStates { get; set; }
    }
    
    public class IrModuleModuleGetModuleInfoRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Name { get; set; }
    }
    
    public class IrModuleModuleSearchPanelSelectRangeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? FieldName { get; set; }
    }
    
    public class IrModuleModuleUpstreamDependenciesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? KnownDeps { get; set; }
        public object? ExcludeStates { get; set; }
    }
    
    public class IrModuleModuleWebReadRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Specification { get; set; }
    }
    
    public class IrModuleModuleWebSearchReadRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Domain { get; set; }
        public object? Specification { get; set; }
        public object? Offset { get; set; }
        public object? Limit { get; set; }
        public object? Order { get; set; }
        public object? CountLimit { get; set; }
    }
}