// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrModuleModuleDependencyAllDependenciesRequestDto
    {
        public object ModuleNames { get; set; }
    }
}