// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class IrSequenceGetRequestDto
    {
        public object Code { get; set; }
    }
    
    public class IrSequenceGetIdRequestDto
    {
        public Guid SequenceCodeOrId { get; set; }
        public Guid CodeOrId { get; set; }
    }
    
    public class IrSequenceGetNextCharRequestDto
    {
        public object NumberNext { get; set; }
    }
    
    public class IrSequenceNextByCodeRequestDto
    {
        public object SequenceCode { get; set; }
        public object SequenceDate { get; set; }
    }
    
    public class IrSequenceNextByIdRequestDto
    {
        public object SequenceDate { get; set; }
    }
}