// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class PaymentTransactionRefundRequestDto
    {
        public object AmountToRefund { get; set; }
    }
}