// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResConfigSettingsGetConfigWarningRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Msg { get; set; }
    }
    
    public class ResConfigSettingsGetOptionNameRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? FullFieldName { get; set; }
    }
    
    public class ResConfigSettingsGetOptionPathRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? MenuXmlId { get; set; }
    }
}