// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResCurrencyAmountToTextRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
    }
    
    public class ResCurrencyCompareAmountsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount1 { get; set; }
        public object? Amount2 { get; set; }
    }
    
    public class ResCurrencyFormatRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
    }
    
    public class ResCurrencyGetCompanyCurrencyForSpreadsheetRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? CompanyId { get; set; }
    }
    
    public class ResCurrencyIsZeroRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
    }
    
    public class ResCurrencyRoundRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Amount { get; set; }
    }
}