// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResGroupsCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class ResGroupsGetApplicationGroupsRequestDto
    {
        public object Domain { get; set; }
    }
}