// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResLangCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class ResLangFormatRequestDto
    {
        public string Percent { get; set; }
        public object Value { get; set; }
        public bool Grouping { get; set; }
    }
}