// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ResPartnerAddressGetRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? AdrPref { get; set; }
    }
    
    public class ResPartnerAutocompleteByNameRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Query { get; set; }
        public Guid? QueryCountryId { get; set; }
        public object? Timeout { get; set; }
    }
    
    public class ResPartnerAutocompleteByVatRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
        public Guid? QueryCountryId { get; set; }
        public object? Timeout { get; set; }
    }
    
    public class ResPartnerButtonAccountPeppolCheckPartnerEndpointRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Company { get; set; }
    }
    
    public class ResPartnerCheckVatAlRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatBrRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatChRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatCrRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatDeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatDoRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatEcRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatGrRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatGtRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatHuRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatIdRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatIeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatIlRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatInRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatJpRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatMaRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatMxRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatNoRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatPeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatPhRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatRoRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatRsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatRuRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatSaRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatThRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatTrRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatTwRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatUaRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatUyRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatVeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCheckVatVnRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class ResPartnerDoPartnerManualActionRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? PartnerIds { get; set; }
    }
    
    public class ResPartnerDoPartnerManualDermanordRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? FollowupLine { get; set; }
    }
    
    public class ResPartnerDoPartnerPrintRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? WizardPartnerIds { get; set; }
        public object? Data { get; set; }
    }
    
    public class ResPartnerEnrichByDomainRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Domain { get; set; }
        public object? Timeout { get; set; }
    }
    
    public class ResPartnerEnrichByDunsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Duns { get; set; }
        public object? Timeout { get; set; }
    }
    
    public class ResPartnerEnrichByGstRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Gst { get; set; }
        public object? Timeout { get; set; }
    }
    
    public class ResPartnerFieldsViewGetRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? ViewId { get; set; }
        public object? ViewType { get; set; }
        public object? Toolbar { get; set; }
        public object? Submenu { get; set; }
    }
    
    public class ResPartnerFindOrCreateRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Email { get; set; }
        public object? AssertValidEmail { get; set; }
    }
    
    public class ResPartnerFormatVatChRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerFormatVatClRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerFormatVatCoRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerFormatVatEuRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerFormatVatHuRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerFormatVatSmRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerFormatVatVnRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerGetAttendeeDetailRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? MeetingIds { get; set; }
    }
    
    public class ResPartnerGetMentionSuggestionsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Search { get; set; }
        public object? Limit { get; set; }
    }
    
    public class ResPartnerGetMentionSuggestionsFromChannelRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? ChannelId { get; set; }
        public object? Search { get; set; }
        public object? Limit { get; set; }
    }
    
    public class ResPartnerGetNewPartnerRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? ConfigId { get; set; }
        public object? Domain { get; set; }
        public object? Offset { get; set; }
    }
    
    public class ResPartnerGetPartnerLocalisationFieldsRequiredToInvoiceRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? CountryId { get; set; }
    }
    
    public class ResPartnerGetWorkingHoursForAllAttendeesRequestDto
    {
        public Guid[]? Ids { get; set; }
        public List<Guid>? AttendeeIds { get; set; }
        public object? DateFrom { get; set; }
        public object? DateTo { get; set; }
        public object? Everybody { get; set; }
    }
    
    public class ResPartnerGetWorklocationRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? StartDate { get; set; }
        public object? EndDate { get; set; }
    }
    
    public class ResPartnerGoogleMapImgRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Zoom { get; set; }
        public object? Width { get; set; }
        public object? Height { get; set; }
    }
    
    public class ResPartnerGoogleMapLinkRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Zoom { get; set; }
    }
    
    public class ResPartnerIapPartnerAutocompleteGetTagIdsRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? UnspscCodes { get; set; }
    }
    
    public class ResPartnerIsValidRucEcRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vat { get; set; }
    }
    
    public class ResPartnerSearchForChannelInviteRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? SearchTerm { get; set; }
        public Guid? ChannelId { get; set; }
        public object? Limit { get; set; }
    }
    
    public class ResPartnerSignupPrepareRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? SignupType { get; set; }
    }
    
    public class ResPartnerViewHeaderGetRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? ViewId { get; set; }
        public object? ViewType { get; set; }
    }
}