using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Models;
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Application.Contracts.DTOs;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAccountMoveAppService : IGenericApplicationService<AccountMove>
    {
        Task<AccountMove> ActivateCurrencyAsync(Guid id);
        Task<AccountMove> AddFromCatalogAsync(Guid id);
        Task<AccountMove> ButtonAbandonCancelPostedPostedMovesAsync(Guid id);
        Task<AccountMove> ButtonCancelAsync(Guid id);
        Task<AccountMove> ButtonCancelPostedMovesAsync(Guid id);
        Task<AccountMove> ButtonCreateLandedCostsAsync(Guid id);
        Task<AccountMove> ButtonDraftAsync(Guid id);
        Task<AccountMove> ButtonForceCancelAsync(Guid id);
        Task<AccountMove> ButtonHashAsync(Guid id);
        Task<AccountMove> ButtonProcessEdiWebServicesAsync(Guid id);
        Task<AccountMove> ButtonRequestCancelAsync(Guid id);
        Task<AccountMove> ButtonSetCheckedAsync(Guid id);
        Task<AccountMove> CancelAsync(Guid id);
        Task<AccountMove> CancelPeppolDocumentsAsync(Guid id);
        Task<AccountMove> CheckMoveSequenceChainAsync(Guid id);
        Task<AccountMove> ComputeMoveSentValuesAsync(Guid id);
        Task<AccountMove> CopyDataAsync(Guid id, AccountMoveCopyDataRequestDto input);
        Task<AccountMove> DebitNoteAsync(Guid id);
        Task<AccountMove> DuplicateAsync(Guid id);
        Task<AccountMove> ForceRegisterPaymentAsync(Guid id);
        Task<AccountMove> GetCurrencyRateAsync(Guid id, AccountMoveGetCurrencyRateRequestDto input);
        Task<AccountMove> GetExtraPrintItemsAsync(Guid id);
        Task<AccountMove> GetInboundTypesAsync(Guid id, AccountMoveGetInboundTypesRequestDto input);
        Task<AccountMove> GetInvoiceLocalisationFieldsRequiredToInvoiceAsync(Guid id, AccountMoveGetInvoiceLocalisationFieldsRequiredToInvoiceRequestDto input);
        Task<AccountMove> GetInvoiceTypesAsync(Guid id, AccountMoveGetInvoiceTypesRequestDto input);
        Task<AccountMove> GetOutboundTypesAsync(Guid id, AccountMoveGetOutboundTypesRequestDto input);
        Task<AccountMove> GetPortalLastTransactionAsync(Guid id);
        Task<AccountMove> GetPurchaseTypesAsync(Guid id, AccountMoveGetPurchaseTypesRequestDto input);
        Task<AccountMove> GetSaleTypesAsync(Guid id, AccountMoveGetSaleTypesRequestDto input);
        Task<AccountMove> InitAsync(Guid id);
        Task<AccountMove> InvoiceDownloadPdfAsync(Guid id);
        Task<AccountMove> InvoiceDownloadUblAsync(Guid id);
        Task<AccountMove> InvoiceSentAsync(Guid id);
        Task<AccountMove> InvoiceValidateSendEmailAsync(Guid id);
        Task<AccountMove> IsEntryAsync(Guid id);
        Task<AccountMove> IsInboundAsync(Guid id, AccountMoveIsInboundRequestDto input);
        Task<AccountMove> IsInvoiceAsync(Guid id, AccountMoveIsInvoiceRequestDto input);
        Task<AccountMove> IsOutboundAsync(Guid id, AccountMoveIsOutboundRequestDto input);
        Task<AccountMove> IsPurchaseDocumentAsync(Guid id, AccountMoveIsPurchaseDocumentRequestDto input);
        Task<AccountMove> IsSaleDocumentAsync(Guid id, AccountMoveIsSaleDocumentRequestDto input);
        Task<AccountMove> JsAssignOutstandingLineAsync(Guid id, AccountMoveJsAssignOutstandingLineRequestDto input);
        Task<AccountMove> JsRemoveOutstandingPartialAsync(Guid id, AccountMoveJsRemoveOutstandingPartialRequestDto input);
        Task<AccountMove> MessageNewAsync(Guid id, AccountMoveMessageNewRequestDto input);
        Task<AccountMove> OpenBusinessDocAsync(Guid id);
        Task<AccountMove> OpenCreatedCabaEntriesAsync(Guid id);
        Task<AccountMove> OpenExpenseReportAsync(Guid id);
        Task<AccountMove> OpenPaymentsAsync(Guid id);
        Task<AccountMove> OpenReconcileViewAsync(Guid id);
        Task<AccountMove> PaymentCaptureAsync(Guid id);
        Task<AccountMove> PaymentVoidAsync(Guid id);
        Task<AccountMove> PostAsync(Guid id);
        Task<AccountMove> PreviewInvoiceAsync(Guid id);
        Task<AccountMove> PrintPdfAsync(Guid id);
        Task<AccountMove> ProcessEdiWebServicesAsync(Guid id, AccountMoveProcessEdiWebServicesRequestDto input);
        Task<AccountMove> PurchaseMatchingAsync(Guid id);
        Task<AccountMove> RefreshInvoiceCurrencyRateAsync(Guid id);
        Task<AccountMove> RegisterPaymentAsync(Guid id);
        Task<AccountMove> RetryEdiDocumentsErrorAsync(Guid id);
        Task<AccountMove> ReverseAsync(Guid id);
        Task<AccountMove> SendAndPrintAsync(Guid id);
        Task<AccountMove> SwitchMoveTypeAsync(Guid id);
        Task<AccountMove> ToggleBlockPaymentAsync(Guid id);
        Task<AccountMove> UpdateFposValuesAsync(Guid id);
        Task<AccountMove> ViewDebitNotesAsync(Guid id);
        Task<AccountMove> ViewLandedCostsAsync(Guid id);
        Task<AccountMove> ViewPaymentTransactionsAsync(Guid id);
        Task<AccountMove> ViewSourcePurchaseOrdersAsync(Guid id);
        Task<AccountMove> ViewSourceSaleOrdersAsync(Guid id);
        Task<AccountMove> ViewTimesheetAsync(Guid id);
        Task<AccountMove> ViewWipProductionAsync(Guid id);
    }
}