using Volo.Abp.Application.Services;
using System;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using Bamboo.Core.Models;
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Application.Contracts.DTOs;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAccountMoveAppService : IGenericAppService<AccountMove>
    {
        Task<AccountMove> ActivateCurrencyAsync(Guid[] ids);
        Task<AccountMove> AddFromCatalogAsync(Guid[] ids);
        Task<AccountMove> ButtonAbandonCancelPostedPostedMovesAsync(Guid[] ids);
        Task<AccountMove> ButtonCancelAsync(Guid[] ids);
        Task<AccountMove> ButtonCancelPostedMovesAsync(Guid[] ids);
        Task<AccountMove> ButtonCreateLandedCostsAsync(Guid[] ids);
        Task<AccountMove> ButtonDraftAsync(Guid[] ids);
        Task<AccountMove> ButtonForceCancelAsync(Guid[] ids);
        Task<AccountMove> ButtonHashAsync(Guid[] ids);
        Task<AccountMove> ButtonProcessEdiWebServicesAsync(Guid[] ids);
        Task<AccountMove> ButtonRequestCancelAsync(Guid[] ids);
        Task<AccountMove> ButtonSetCheckedAsync(Guid[] ids);
        Task<AccountMove> CancelAsync(Guid[] ids);
        Task<AccountMove> CancelPeppolDocumentsAsync(Guid[] ids);
        Task<AccountMove> CheckMoveSequenceChainAsync(Guid[] ids);
        Task<AccountMove> CheckSelectedMovesAsync(Guid[] ids);
        Task<AccountMove> ComputeMoveSentValuesAsync(Guid[] ids);
        Task<AccountMove> CopyDataAsync(AccountMoveCopyDataRequestDto input);
        Task<AccountMove> DebitNoteAsync(Guid[] ids);
        Task<AccountMove> DuplicateAsync(Guid[] ids);
        Task<AccountMove> ForceRegisterPaymentAsync(Guid[] ids);
        Task<AccountMove> GetCurrencyRateAsync(AccountMoveGetCurrencyRateRequestDto input);
        Task<AccountMove> GetExtraPrintItemsAsync(Guid[] ids);
        Task<AccountMove> GetImportTemplatesAsync(Guid[] ids);
        Task<AccountMove> GetInboundTypesAsync(AccountMoveGetInboundTypesRequestDto input);
        Task<AccountMove> GetInvoiceLocalisationFieldsRequiredToInvoiceAsync(AccountMoveGetInvoiceLocalisationFieldsRequiredToInvoiceRequestDto input);
        Task<AccountMove> GetInvoiceTypesAsync(AccountMoveGetInvoiceTypesRequestDto input);
        Task<AccountMove> GetOutboundTypesAsync(AccountMoveGetOutboundTypesRequestDto input);
        Task<AccountMove> GetPortalLastTransactionAsync(Guid[] ids);
        Task<AccountMove> GetPurchaseTypesAsync(AccountMoveGetPurchaseTypesRequestDto input);
        Task<AccountMove> GetSaleTypesAsync(AccountMoveGetSaleTypesRequestDto input);
        Task<AccountMove> InvoiceDownloadPdfAsync(AccountMoveInvoiceDownloadPdfRequestDto input);
        Task<AccountMove> InvoiceDownloadUblAsync(Guid[] ids);
        Task<AccountMove> InvoiceSentAsync(Guid[] ids);
        Task<AccountMove> InvoiceValidateSendEmailAsync(Guid[] ids);
        Task<AccountMove> IsEntryAsync(Guid[] ids);
        Task<AccountMove> IsInboundAsync(AccountMoveIsInboundRequestDto input);
        Task<AccountMove> IsInvoiceAsync(AccountMoveIsInvoiceRequestDto input);
        Task<AccountMove> IsOutboundAsync(AccountMoveIsOutboundRequestDto input);
        Task<AccountMove> IsPurchaseDocumentAsync(AccountMoveIsPurchaseDocumentRequestDto input);
        Task<AccountMove> IsReceiptAsync(Guid[] ids);
        Task<AccountMove> IsSaleDocumentAsync(AccountMoveIsSaleDocumentRequestDto input);
        Task<AccountMove> JsAssignOutstandingLineAsync(AccountMoveJsAssignOutstandingLineRequestDto input);
        Task<AccountMove> JsRemoveOutstandingPartialAsync(AccountMoveJsRemoveOutstandingPartialRequestDto input);
        Task<AccountMove> MessageNewAsync(AccountMoveMessageNewRequestDto input);
        Task<AccountMove> MoveDownloadAllAsync(Guid[] ids);
        Task<AccountMove> OpenAdjustingEntriesAsync(Guid[] ids);
        Task<AccountMove> OpenAdjustingEntryOriginMovesAsync(Guid[] ids);
        Task<AccountMove> OpenBusinessDocAsync(Guid[] ids);
        Task<AccountMove> OpenCreatedCabaEntriesAsync(Guid[] ids);
        Task<AccountMove> OpenExpenseAsync(Guid[] ids);
        Task<AccountMove> OpenPaymentsAsync(Guid[] ids);
        Task<AccountMove> OpenReconcileViewAsync(Guid[] ids);
        Task<AccountMove> PaymentCaptureAsync(Guid[] ids);
        Task<AccountMove> PaymentVoidAsync(Guid[] ids);
        Task<AccountMove> PostAsync(Guid[] ids);
        Task<AccountMove> PreviewInvoiceAsync(Guid[] ids);
        Task<AccountMove> PrintPdfAsync(Guid[] ids);
        Task<AccountMove> ProcessEdiWebServicesAsync(AccountMoveProcessEdiWebServicesRequestDto input);
        Task<AccountMove> PurchaseMatchingAsync(Guid[] ids);
        Task<AccountMove> ReflectCancelledSolAsync(AccountMoveReflectCancelledSolRequestDto input);
        Task<AccountMove> RefreshInvoiceCurrencyRateAsync(Guid[] ids);
        Task<AccountMove> RegisterPaymentAsync(Guid[] ids);
        Task<AccountMove> RetryEdiDocumentsErrorAsync(Guid[] ids);
        Task<AccountMove> ReverseAsync(Guid[] ids);
        Task<AccountMove> SendAndPrintAsync(Guid[] ids);
        Task<AccountMove> SetMovesCheckedAsync(AccountMoveSetMovesCheckedRequestDto input);
        Task<AccountMove> SwitchMoveTypeAsync(Guid[] ids);
        Task<AccountMove> ToggleBlockPaymentAsync(Guid[] ids);
        Task<AccountMove> UnlinkSnailmailLettersAsync(Guid[] ids);
        Task<AccountMove> UpdateFposValuesAsync(Guid[] ids);
        Task<AccountMove> ValidateMovesWithConfirmationAsync(Guid[] ids);
        Task<AccountMove> ViewDebitNotesAsync(Guid[] ids);
        Task<AccountMove> ViewLandedCostsAsync(Guid[] ids);
        Task<AccountMove> ViewPaymentTransactionsAsync(Guid[] ids);
        Task<AccountMove> ViewSourcePosOrdersAsync(Guid[] ids);
        Task<AccountMove> ViewSourcePurchaseOrdersAsync(Guid[] ids);
        Task<AccountMove> ViewSourceSaleOrdersAsync(Guid[] ids);
        Task<AccountMove> ViewTimesheetAsync(Guid[] ids);
        Task<AccountMove> ViewWipProductionAsync(Guid[] ids);
    }
}