<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Bamboo.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.0.0-rc.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\core\Bamboo.Core.Application.Contracts\Bamboo.Core.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
