// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SlideChannelCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class SlideChannelGrantAccessRequestDto
    {
        public Guid PartnerId { get; set; }
    }
    
    public class SlideChannelRedirectToMembersRequestDto
    {
        public object StatusFilter { get; set; }
    }
    
    public class SlideChannelRefuseAccessRequestDto
    {
        public Guid PartnerId { get; set; }
    }
}