// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IStockLandedCostAppService : IGenericApplicationService<StockLandedCost>
    {
        Task<StockLandedCost> ButtonCancelAsync(Guid id);
        Task<StockLandedCost> ButtonValidateAsync(Guid id);
        Task<StockLandedCost> ComputeLandedCostAsync(Guid id);
        Task<StockLandedCost> GetValuationLinesAsync(Guid id);
        Task<StockLandedCost> ReconcileLandedCostAsync(Guid id);
        Task<StockLandedCost> ViewStockValuationLayersAsync(Guid id);
    }
}