// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SpreadsheetDashboardShareGetShareUrlRequestDto
    {
        public object Vals { get; set; }
    }
}