// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IProjectProjectAppService : IGenericApplicationService<ProjectProject>
    {
        Task<ProjectProject> BillableTimeButtonAsync(Guid id);
        Task<ProjectProject> CopyDataAsync(Guid id, object @default);
        Task<ProjectProject> CreateInvoiceAsync(Guid id);
        Task<ProjectProject> CustomerPreviewAsync(Guid id);
        Task<ProjectProject> GetCreateEditProjectIdsAsync(Guid id);
        Task<ProjectProject> GetLastUpdateOrDefaultAsync(Guid id);
        Task<ProjectProject> GetListViewAsync(Guid id);
        Task<ProjectProject> GetMilestonesAsync(Guid id);
        Task<ProjectProject> GetPanelDataAsync(Guid id);
        Task<ProjectProject> GetSaleItemsDataAsync(Guid id, object offset, object limit, object with_action, Guid section_id);
        Task<ProjectProject> MapTasksAsync(Guid id, Guid new_project_id);
        Task<ProjectProject> MessageSubscribeAsync(Guid id, List<Guid> partner_ids, List<Guid> subtype_ids);
        Task<ProjectProject> MessageUnsubscribeAsync(Guid id, List<Guid> partner_ids);
        Task<ProjectProject> OpenAllPickingsAsync(Guid id);
        Task<ProjectProject> OpenAnalyticItemsAsync(Guid id);
        Task<ProjectProject> OpenDeliveriesAsync(Guid id);
        Task<ProjectProject> OpenProjectExpensesAsync(Guid id);
        Task<ProjectProject> OpenProjectInvoicesAsync(Guid id);
        Task<ProjectProject> OpenProjectPurchaseOrdersAsync(Guid id);
        Task<ProjectProject> OpenProjectVendorBillsAsync(Guid id);
        Task<ProjectProject> OpenReceiptsAsync(Guid id);
        Task<ProjectProject> OpenShareProjectWizardAsync(Guid id);
        Task<ProjectProject> ProfitabilityItemsAsync(Guid id, object section_name, object domain, Guid res_id);
        Task<ProjectProject> ProjectTaskBurndownChartReportAsync(Guid id);
        Task<ProjectProject> ProjectTimesheetsAsync(Guid id);
        Task<ProjectProject> ProjectUpdateAllActionAsync(Guid id);
        Task<ProjectProject> ToggleFavoriteAsync(Guid id);
        Task<ProjectProject> ViewAllRatingAsync(Guid id);
        Task<ProjectProject> ViewMrpBomAsync(Guid id);
        Task<ProjectProject> ViewMrpProductionAsync(Guid id);
        Task<ProjectProject> ViewSolsAsync(Guid id);
        Task<ProjectProject> ViewSosAsync(Guid id);
        Task<ProjectProject> ViewTasksAnalysisAsync(Guid id);
        Task<ProjectProject> ViewTasksAsync(Guid id);
        Task<ProjectProject> ViewTimesheetAsync(Guid id);
    }
}