// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IProjectMilestoneAppService : IGenericApplicationService<ProjectMilestone>
    {
        Task<ProjectMilestone> ToggleIsReachedAsync(Guid id, object is_reached);
        Task<ProjectMilestone> ViewSaleOrderAsync(Guid id);
        Task<ProjectMilestone> ViewTasksAsync(Guid id);
    }
}