// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class FetchmailServerConnectRequestDto
    {
        public object AllowArchived { get; set; }
    }
    
    public class FetchmailServerFetchMailRequestDto
    {
        public object RaiseException { get; set; }
    }
}