// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MailMessageExportDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? FieldsToExport { get; set; }
    }
    
    public class MailMessageFetchRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? FieldNames { get; set; }
    }
    
    public class MailMessageMarkAllAsReadRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Domain { get; set; }
    }
    
    public class MailMessagePortalMessageFormatRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Options { get; set; }
    }
}