// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MailMailProcessEmailQueueRequestDto
    {
        public List<Guid> EmailIds { get; set; }
        public object BatchSize { get; set; }
    }
    
    public class MailMailSendRequestDto
    {
        public object AutoCommit { get; set; }
        public object RaiseException { get; set; }
        public object PostSendCallback { get; set; }
    }
}