// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SpreadsheetDashboardShareGetShareUrlRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Vals { get; set; }
    }
}