// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAccountAccountAppService : IGenericApplicationService<AccountAccount>
    {
        Task<AccountAccount> CopyDataAsync(Guid id, object @default);
        Task<AccountAccount> CopyTranslationsAsync(Guid id, object @new, object excluded);
        Task<AccountAccount> GetAccountGroupAsync(Guid id, object account_types);
        Task<AccountAccount> GetImportTemplatesAsync(Guid id);
        Task<AccountAccount> OpenRelatedTaxesAsync(Guid id);
        Task<AccountAccount> SpreadsheetFetchDebitCreditAsync(Guid id, object args_list);
        Task<AccountAccount> SpreadsheetFetchPartnerBalanceAsync(Guid id, object args_list);
        Task<AccountAccount> SpreadsheetFetchResidualAmountAsync(Guid id, object args_list);
        Task<AccountAccount> SpreadsheetMoveLineActionAsync(Guid id, object args);
        Task<AccountAccount> UnmergeAsync(Guid id);
    }
}