// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAccountMoveLineAppService : IGenericApplicationService<AccountMoveLine>
    {
        Task<AccountMoveLine> AddFromCatalogAsync(Guid id);
        Task<AccountMoveLine> AssetCreateAsync(Guid id);
        Task<AccountMoveLine> AutomaticEntryAsync(Guid id, object default_action);
        Task<AccountMoveLine> CopyDataAsync(Guid id, object @default);
        Task<AccountMoveLine> FlushModelAsync(Guid id, object fnames);
        Task<AccountMoveLine> FlushRecordsetAsync(Guid id, object fnames);
        Task<AccountMoveLine> GetImportTemplatesAsync(Guid id);
        Task<AccountMoveLine> GetInvoiceLineAccountAsync(Guid id, object type, object product, object fpos, object company);
        Task<AccountMoveLine> GetViewsAsync(Guid id, object views, object options);
        Task<AccountMoveLine> InitAsync(Guid id);
        Task<AccountMoveLine> InvalidateModelAsync(Guid id, object fnames, object flush);
        Task<AccountMoveLine> InvalidateRecordsetAsync(Guid id, object fnames, object flush);
        Task<AccountMoveLine> OnchangeAssetCategoryIdAsync(Guid id);
        Task<AccountMoveLine> OpenBusinessDocAsync(Guid id);
        Task<AccountMoveLine> OpenReconcileViewAsync(Guid id);
        Task<AccountMoveLine> PaymentItemsRegisterPaymentAsync(Guid id);
        Task<AccountMoveLine> ReconcileAsync(Guid id);
        Task<AccountMoveLine> RegisterPaymentAsync(Guid id, object ctx);
        Task<AccountMoveLine> RemoveMoveReconcileAsync(Guid id);
        Task<AccountMoveLine> SearchFetchAsync(Guid id, object domain, object field_names, object offset, object limit, object order);
        Task<AccountMoveLine> UnreconcileMatchEntriesAsync(Guid id);
    }
}