// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAccountCashRoundingAppService : IGenericApplicationService<AccountCashRounding>
    {
        Task<AccountCashRounding> ComputeDifferenceAsync(Guid id, object currency, object amount);
        Task<AccountCashRounding> RoundAsync(Guid id, object amount);
        Task<AccountCashRounding> ValidateRoundingAsync(Guid id);
    }
}