// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IAccountTaxAppService : IGenericApplicationService<AccountTax>
    {
        Task<AccountTax> ComputeAllAsync(Guid id, object price_unit, object currency, object quantity, object product, object partner, object is_refund, object handle_price_include, object include_caba_tags, object rounding_method);
        Task<AccountTax> CopyDataAsync(Guid id, object @default);
        Task<AccountTax> FlattenTaxesHierarchyAsync(Guid id);
        Task<AccountTax> GetTaxTagsAsync(Guid id, object is_refund, object repartition_type);
        Task<AccountTax> OnchangeAmountAsync(Guid id);
        Task<AccountTax> OnchangeAmountTypeAsync(Guid id);
        Task<AccountTax> OnchangePriceIncludeAsync(Guid id);
        Task<AccountTax> ValidateTaxGroupIdAsync(Guid id);
    }
}