// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IStockMoveAppService : IGenericApplicationService<StockMove>
    {
        Task<StockMove> AddFromCatalogByproductAsync(Guid id);
        Task<StockMove> AddFromCatalogRawAsync(Guid id);
        Task<StockMove> AddFromCatalogRepairAsync(Guid id);
        Task<StockMove> AssignSerialAsync(Guid id);
        Task<StockMove> CopyDataAsync(Guid id, object @default);
        Task<StockMove> ExplodeAsync(Guid id);
        Task<StockMove> GenerateLotLineValsAsync(Guid id, object context, object mode, object first_lot, object count, object lot_text);
        Task<StockMove> GetAccountMovesAsync(Guid id);
        Task<StockMove> InitAsync(Guid id);
        Task<StockMove> OpenReferenceAsync(Guid id);
        Task<StockMove> ProductForecastReportAsync(Guid id);
        Task<StockMove> ProductPriceUpdateBeforeDoneAsync(Guid id, object forced_qty);
        Task<StockMove> ShowDetailsAsync(Guid id);
        Task<StockMove> ShowSubcontractDetailsAsync(Guid id);
        Task<StockMove> SplitLotsAsync(Guid id, object lots);
    }
}