<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Bamboo.Admin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.HttpApi" Version="10.0.0-rc.3" />
    <PackageReference Include="Volo.Abp.Identity.HttpApi" Version="10.0.0-rc.3" />
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" Version="10.0.0-rc.3" />
    <PackageReference Include="Volo.Abp.TenantManagement.HttpApi" Version="10.0.0-rc.3" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" Version="10.0.0-rc.3" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" Version="10.0.0-rc.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\admin\Bamboo.Admin.Application.Contracts\Bamboo.Admin.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
