// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IHrExpenseAppService : IGenericApplicationService<HrExpense>
    {
        Task<HrExpense> ApproveDuplicatesAsync(Guid id);
        Task<HrExpense> AttachDocumentAsync(Guid id);
        Task<HrExpense> CheckAmountNotZeroAsync(Guid id, object vals);
        Task<HrExpense> CreateExpenseFromAttachmentsAsync(Guid id, List<Guid> attachment_ids, object view_type);
        Task<HrExpense> GetAttachmentViewAsync(Guid id);
        Task<HrExpense> GetEmptyListHelpAsync(Guid id, object help_message);
        Task<HrExpense> GetExpenseAttachmentsAsync(Guid id);
        Task<HrExpense> GetExpenseDashboardAsync(Guid id);
        Task<HrExpense> GetExpensesToSubmitAsync(Guid id);
        Task<HrExpense> MessageNewAsync(Guid id, object msg_dict, object custom_values);
        Task<HrExpense> ShowSameReceiptExpenseIdsAsync(Guid id);
        Task<HrExpense> SplitWizardAsync(Guid id);
        Task<HrExpense> SubmitExpensesAsync(Guid id);
        Task<HrExpense> ViewSheetAsync(Guid id);
    }
}