// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IStockValuationLayerAppService : IGenericApplicationService<StockValuationLayer>
    {
        Task<StockValuationLayer> InitAsync(Guid id);
        Task<StockValuationLayer> OpenJournalEntryAsync(Guid id);
        Task<StockValuationLayer> OpenReferenceAsync(Guid id);
        Task<StockValuationLayer> ValuationAtDateAsync(Guid id);
    }
}