// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class AccountTaxComputeAllRequestDto
    {
        public object PriceUnit { get; set; }
        public object Currency { get; set; }
        public object Quantity { get; set; }
        public object Product { get; set; }
        public object Partner { get; set; }
        public object IsRefund { get; set; }
        public object HandlePriceInclude { get; set; }
        public object IncludeCabaTags { get; set; }
        public object RoundingMethod { get; set; }
    }
    
    public class AccountTaxCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class AccountTaxGetTaxTagsRequestDto
    {
        public object IsRefund { get; set; }
        public object RepartitionType { get; set; }
    }
}