// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IBarcodeNomenclatureAppService : IGenericApplicationService<BarcodeNomenclature>
    {
        Task<BarcodeNomenclature> Gs1DateToDateAsync(Guid id, object gs1_date);
        Task<BarcodeNomenclature> Gs1DecomposeExtandedAsync(Guid id, object barcode);
        Task<BarcodeNomenclature> MatchPatternAsync(Guid id, object barcode, object pattern);
        Task<BarcodeNomenclature> ParseBarcodeAsync(Guid id, object barcode);
        Task<BarcodeNomenclature> ParseGs1RulePatternAsync(Guid id, object match, object rule);
        Task<BarcodeNomenclature> ParseNomenclatureBarcodeAsync(Guid id, object barcode);
        Task<BarcodeNomenclature> ParseUriAsync(Guid id, object barcode);
        Task<BarcodeNomenclature> SanitizeEanAsync(Guid id, object ean);
        Task<BarcodeNomenclature> SanitizeUpcAsync(Guid id, object upc);
    }
}