// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface ICardCampaignAppService : IGenericApplicationService<CardCampaign>
    {
        Task<CardCampaign> PreviewAsync(Guid id);
        Task<CardCampaign> ShareAsync(Guid id);
        Task<CardCampaign> ViewCardsAsync(Guid id);
        Task<CardCampaign> ViewCardsClickedAsync(Guid id);
        Task<CardCampaign> ViewCardsSharedAsync(Guid id);
        Task<CardCampaign> ViewMailingsAsync(Guid id);
    }
}