// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class SaleOrderLineComputeUomQtyRequestDto
    {
        public object NewQty { get; set; }
        public object StockMove { get; set; }
        public object Rounding { get; set; }
    }
    
    public class SaleOrderLineCopyDataRequestDto
    {
        public object Default { get; set; }
    }
}