// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IOnboardingOnboardingAppService : IGenericApplicationService<OnboardingOnboarding>
    {
        Task<OnboardingOnboarding> CloseAsync(Guid id);
        Task<OnboardingOnboarding> ClosePanelAccountDashboardAsync(Guid id);
        Task<OnboardingOnboarding> ClosePanelAccountInvoiceAsync(Guid id);
        Task<OnboardingOnboarding> ClosePanelAsync(Guid id, object xmlid);
        Task<OnboardingOnboarding> RefreshProgressIdsAsync(Guid id);
        Task<OnboardingOnboarding> ToggleVisibilityAsync(Guid id);
    }
}