// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProjectProjectStageCopyDataRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Default { get; set; }
    }
    
    public class ProjectProjectStageUnlinkWizardRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? StageView { get; set; }
    }
}