// Auto-generated by Odoo C# Code Generator
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProjectProjectCopyDataRequestDto
    {
        public object Default { get; set; }
    }
    
    public class ProjectProjectGetSaleItemsDataRequestDto
    {
        public object Offset { get; set; }
        public object Limit { get; set; }
        public object WithAction { get; set; }
        public Guid SectionId { get; set; }
    }
    
    public class ProjectProjectMapTasksRequestDto
    {
        public Guid NewProjectId { get; set; }
    }
    
    public class ProjectProjectMessageSubscribeRequestDto
    {
        public List<Guid> PartnerIds { get; set; }
        public List<Guid> SubtypeIds { get; set; }
    }
    
    public class ProjectProjectMessageUnsubscribeRequestDto
    {
        public List<Guid> PartnerIds { get; set; }
    }
    
    public class ProjectProjectProfitabilityItemsRequestDto
    {
        public object SectionName { get; set; }
        public object Domain { get; set; }
        public Guid ResId { get; set; }
    }
}