// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class ProjectTagsArrangeTagListByIdRequestDto
    {
        public object TagList { get; set; }
        public object IdOrder { get; set; }
    }
}