// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IHrEmployeeAppService : IGenericApplicationService<HrEmployee>
    {
        Task<HrEmployee> CreateUserAsync(Guid id);
        Task<HrEmployee> FetchAsync(Guid id, object field_names);
        Task<HrEmployee> GenerateRandomBarcodeAsync(Guid id);
        Task<HrEmployee> GenerateWorkEntriesAsync(Guid id, object date_start, object date_stop, object force);
        Task<HrEmployee> GetAllocationRequestsAmountAsync(Guid id);
        Task<HrEmployee> GetBarcodesAndPinHashedAsync(Guid id);
        Task<HrEmployee> GetFormviewActionAsync(Guid id, object access_uid);
        Task<HrEmployee> GetFormviewIdAsync(Guid id, object access_uid);
        Task<HrEmployee> GetImportTemplatesAsync(Guid id);
        Task<HrEmployee> GetMandatoryDaysAsync(Guid id, object start_date, object end_date);
        Task<HrEmployee> GetMandatoryDaysDataAsync(Guid id, object date_start, object date_end);
        Task<HrEmployee> GetPublicHolidaysDataAsync(Guid id, object date_start, object date_end);
        Task<HrEmployee> GetSpecialDaysDataAsync(Guid id, object date_start, object date_end);
        Task<HrEmployee> GetViewAsync(Guid id, Guid view_id, object view_type);
        Task<HrEmployee> GetViewsAsync(Guid id, object views, object options);
        Task<HrEmployee> OpenContractAsync(Guid id);
        Task<HrEmployee> OpenCoursesAsync(Guid id);
        Task<HrEmployee> OpenEmployeeCarsAsync(Guid id);
        Task<HrEmployee> OpenLastMonthAttendancesAsync(Guid id);
        Task<HrEmployee> OpenLastMonthOvertimeAsync(Guid id);
        Task<HrEmployee> OpenWorkEntriesAsync(Guid id, object initial_date);
        Task<HrEmployee> RelatedContactsAsync(Guid id);
        Task<HrEmployee> SearchFetchAsync(Guid id, object domain, object field_names, object offset, object limit, object order);
        Task<HrEmployee> TimeOffDashboardAsync(Guid id);
        Task<HrEmployee> TimesheetFromEmployeeAsync(Guid id);
        Task<HrEmployee> ToggleActiveAsync(Guid id);
        Task<HrEmployee> UnlinkWizardAsync(Guid id);
    }
}