<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="10.0.0" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bamboo.Shared.Hosting\Bamboo.Shared.Hosting.csproj" />
  </ItemGroup>

</Project>
