
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountAssetDepreciationLineAppService), typeof(AccountAssetDepreciationLineClientProxy))]
public partial class AccountAssetDepreciationLineClientProxy : ClientProxyBase<IAccountAssetDepreciationLineAppService>, IAccountAssetDepreciationLineAppService
{
    //public virtual async Task<ListResultDto<AccountAssetDepreciationLine>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountAssetDepreciationLine>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountAssetDepreciationLine>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountAssetDepreciationLine>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountAssetDepreciationLine> GetAsync(Guid id)
    {
        return await RequestAsync<AccountAssetDepreciationLine>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountAssetDepreciationLine> CreateAsync(AccountAssetDepreciationLine input)
    {
        return await RequestAsync<AccountAssetDepreciationLine>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountAssetDepreciationLine), input }
        });
    }

    public virtual async Task<AccountAssetDepreciationLine> UpdateAsync(Guid id, AccountAssetDepreciationLine input)
    {
        return await RequestAsync<AccountAssetDepreciationLine>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountAssetDepreciationLine), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
