
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountTaxRepartitionLineTemplateAppService), typeof(AccountTaxRepartitionLineTemplateClientProxy))]
public partial class AccountTaxRepartitionLineTemplateClientProxy : ClientProxyBase<IAccountTaxRepartitionLineTemplateAppService>, IAccountTaxRepartitionLineTemplateAppService
{
    //public virtual async Task<ListResultDto<AccountTaxRepartitionLineTemplate>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountTaxRepartitionLineTemplate>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountTaxRepartitionLineTemplate>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountTaxRepartitionLineTemplate>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountTaxRepartitionLineTemplate> GetAsync(Guid id)
    {
        return await RequestAsync<AccountTaxRepartitionLineTemplate>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountTaxRepartitionLineTemplate> CreateAsync(AccountTaxRepartitionLineTemplate input)
    {
        return await RequestAsync<AccountTaxRepartitionLineTemplate>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountTaxRepartitionLineTemplate), input }
        });
    }

    public virtual async Task<AccountTaxRepartitionLineTemplate> UpdateAsync(Guid id, AccountTaxRepartitionLineTemplate input)
    {
        return await RequestAsync<AccountTaxRepartitionLineTemplate>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountTaxRepartitionLineTemplate), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
