
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountFiscalPositionTemplateAppService), typeof(AccountFiscalPositionTemplateClientProxy))]
public partial class AccountFiscalPositionTemplateClientProxy : ClientProxyBase<IAccountFiscalPositionTemplateAppService>, IAccountFiscalPositionTemplateAppService
{
    //public virtual async Task<ListResultDto<AccountFiscalPositionTemplate>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountFiscalPositionTemplate>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountFiscalPositionTemplate>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountFiscalPositionTemplate>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountFiscalPositionTemplate> GetAsync(Guid id)
    {
        return await RequestAsync<AccountFiscalPositionTemplate>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountFiscalPositionTemplate> CreateAsync(AccountFiscalPositionTemplate input)
    {
        return await RequestAsync<AccountFiscalPositionTemplate>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountFiscalPositionTemplate), input }
        });
    }

    public virtual async Task<AccountFiscalPositionTemplate> UpdateAsync(Guid id, AccountFiscalPositionTemplate input)
    {
        return await RequestAsync<AccountFiscalPositionTemplate>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountFiscalPositionTemplate), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
