
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountMoveLineAppService), typeof(AccountMoveLineClientProxy))]
public partial class AccountMoveLineClientProxy : ClientProxyBase<IAccountMoveLineAppService>, IAccountMoveLineAppService
{
    //public virtual async Task<ListResultDto<AccountMoveLine>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountMoveLine>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountMoveLine>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountMoveLine>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountMoveLine> GetAsync(Guid id)
    {
        return await RequestAsync<AccountMoveLine>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountMoveLine> CreateAsync(AccountMoveLine input)
    {
        return await RequestAsync<AccountMoveLine>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountMoveLine), input }
        });
    }

    public virtual async Task<AccountMoveLine> UpdateAsync(Guid id, AccountMoveLine input)
    {
        return await RequestAsync<AccountMoveLine>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountMoveLine), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
