
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountCommonReportAppService), typeof(AccountCommonReportClientProxy))]
public partial class AccountCommonReportClientProxy : ClientProxyBase<IAccountCommonReportAppService>, IAccountCommonReportAppService
{
    //public virtual async Task<ListResultDto<AccountCommonReport>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountCommonReport>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountCommonReport>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountCommonReport>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountCommonReport> GetAsync(Guid id)
    {
        return await RequestAsync<AccountCommonReport>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountCommonReport> CreateAsync(AccountCommonReport input)
    {
        return await RequestAsync<AccountCommonReport>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountCommonReport), input }
        });
    }

    public virtual async Task<AccountCommonReport> UpdateAsync(Guid id, AccountCommonReport input)
    {
        return await RequestAsync<AccountCommonReport>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountCommonReport), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
