
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountReportGeneralLedgerAppService), typeof(AccountReportGeneralLedgerClientProxy))]
public partial class AccountReportGeneralLedgerClientProxy : ClientProxyBase<IAccountReportGeneralLedgerAppService>, IAccountReportGeneralLedgerAppService
{
    //public virtual async Task<ListResultDto<AccountReportGeneralLedger>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountReportGeneralLedger>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountReportGeneralLedger>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountReportGeneralLedger>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountReportGeneralLedger> GetAsync(Guid id)
    {
        return await RequestAsync<AccountReportGeneralLedger>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountReportGeneralLedger> CreateAsync(AccountReportGeneralLedger input)
    {
        return await RequestAsync<AccountReportGeneralLedger>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountReportGeneralLedger), input }
        });
    }

    public virtual async Task<AccountReportGeneralLedger> UpdateAsync(Guid id, AccountReportGeneralLedger input)
    {
        return await RequestAsync<AccountReportGeneralLedger>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountReportGeneralLedger), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
