
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountChartTemplateAppService), typeof(AccountChartTemplateClientProxy))]
public partial class AccountChartTemplateClientProxy : ClientProxyBase<IAccountChartTemplateAppService>, IAccountChartTemplateAppService
{
    //public virtual async Task<ListResultDto<AccountChartTemplate>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountChartTemplate>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountChartTemplate>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountChartTemplate>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountChartTemplate> GetAsync(Guid id)
    {
        return await RequestAsync<AccountChartTemplate>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountChartTemplate> CreateAsync(AccountChartTemplate input)
    {
        return await RequestAsync<AccountChartTemplate>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountChartTemplate), input }
        });
    }

    public virtual async Task<AccountChartTemplate> UpdateAsync(Guid id, AccountChartTemplate input)
    {
        return await RequestAsync<AccountChartTemplate>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountChartTemplate), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
