
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountAccountTemplateAppService), typeof(AccountAccountTemplateClientProxy))]
public partial class AccountAccountTemplateClientProxy : ClientProxyBase<IAccountAccountTemplateAppService>, IAccountAccountTemplateAppService
{
    //public virtual async Task<ListResultDto<AccountAccountTemplate>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AccountAccountTemplate>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AccountAccountTemplate>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AccountAccountTemplate>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AccountAccountTemplate> GetAsync(Guid id)
    {
        return await RequestAsync<AccountAccountTemplate>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AccountAccountTemplate> CreateAsync(AccountAccountTemplate input)
    {
        return await RequestAsync<AccountAccountTemplate>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AccountAccountTemplate), input }
        });
    }

    public virtual async Task<AccountAccountTemplate> UpdateAsync(Guid id, AccountAccountTemplate input)
    {
        return await RequestAsync<AccountAccountTemplate>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AccountAccountTemplate), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
