
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IApplicantSendMailAppService), typeof(ApplicantSendMailClientProxy))]
public partial class ApplicantSendMailClientProxy : ClientProxyBase<IApplicantSendMailAppService>, IApplicantSendMailAppService
{
    //public virtual async Task<ListResultDto<ApplicantSendMail>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ApplicantSendMail>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ApplicantSendMail>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ApplicantSendMail>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ApplicantSendMail> GetAsync(Guid id)
    {
        return await RequestAsync<ApplicantSendMail>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ApplicantSendMail> CreateAsync(ApplicantSendMail input)
    {
        return await RequestAsync<ApplicantSendMail>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ApplicantSendMail), input }
        });
    }

    public virtual async Task<ApplicantSendMail> UpdateAsync(Guid id, ApplicantSendMail input)
    {
        return await RequestAsync<ApplicantSendMail>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ApplicantSendMail), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
