
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAuthTotpWizardAppService), typeof(AuthTotpWizardClientProxy))]
public partial class AuthTotpWizardClientProxy : ClientProxyBase<IAuthTotpWizardAppService>, IAuthTotpWizardAppService
{
    //public virtual async Task<ListResultDto<AuthTotpWizard>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<AuthTotpWizard>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<AuthTotpWizard>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<AuthTotpWizard>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<AuthTotpWizard> GetAsync(Guid id)
    {
        return await RequestAsync<AuthTotpWizard>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AuthTotpWizard> CreateAsync(AuthTotpWizard input)
    {
        return await RequestAsync<AuthTotpWizard>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AuthTotpWizard), input }
        });
    }

    public virtual async Task<AuthTotpWizard> UpdateAsync(Guid id, AuthTotpWizard input)
    {
        return await RequestAsync<AuthTotpWizard>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(AuthTotpWizard), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
