
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBaseImportTestsModelsCharReadonlyAppService), typeof(BaseImportTestsModelsCharReadonlyClientProxy))]
public partial class BaseImportTestsModelsCharReadonlyClientProxy : ClientProxyBase<IBaseImportTestsModelsCharReadonlyAppService>, IBaseImportTestsModelsCharReadonlyAppService
{
    //public virtual async Task<ListResultDto<BaseImportTestsModelsCharReadonly>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<BaseImportTestsModelsCharReadonly>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<BaseImportTestsModelsCharReadonly>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<BaseImportTestsModelsCharReadonly>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharReadonly> GetAsync(Guid id)
    {
        return await RequestAsync<BaseImportTestsModelsCharReadonly>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharReadonly> CreateAsync(BaseImportTestsModelsCharReadonly input)
    {
        return await RequestAsync<BaseImportTestsModelsCharReadonly>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BaseImportTestsModelsCharReadonly), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharReadonly> UpdateAsync(Guid id, BaseImportTestsModelsCharReadonly input)
    {
        return await RequestAsync<BaseImportTestsModelsCharReadonly>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(BaseImportTestsModelsCharReadonly), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
