
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBaseImportTestsModelsCharStateAppService), typeof(BaseImportTestsModelsCharStateClientProxy))]
public partial class BaseImportTestsModelsCharStateClientProxy : ClientProxyBase<IBaseImportTestsModelsCharStateAppService>, IBaseImportTestsModelsCharStateAppService
{
    //public virtual async Task<ListResultDto<BaseImportTestsModelsCharState>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<BaseImportTestsModelsCharState>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<BaseImportTestsModelsCharState>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<BaseImportTestsModelsCharState>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharState> GetAsync(Guid id)
    {
        return await RequestAsync<BaseImportTestsModelsCharState>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharState> CreateAsync(BaseImportTestsModelsCharState input)
    {
        return await RequestAsync<BaseImportTestsModelsCharState>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BaseImportTestsModelsCharState), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharState> UpdateAsync(Guid id, BaseImportTestsModelsCharState input)
    {
        return await RequestAsync<BaseImportTestsModelsCharState>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(BaseImportTestsModelsCharState), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
