
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBaseImportTestsModelsO2mAppService), typeof(BaseImportTestsModelsO2mClientProxy))]
public partial class BaseImportTestsModelsO2mClientProxy : ClientProxyBase<IBaseImportTestsModelsO2mAppService>, IBaseImportTestsModelsO2mAppService
{
    //public virtual async Task<ListResultDto<BaseImportTestsModelsO2m>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<BaseImportTestsModelsO2m>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<BaseImportTestsModelsO2m>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<BaseImportTestsModelsO2m>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsO2m> GetAsync(Guid id)
    {
        return await RequestAsync<BaseImportTestsModelsO2m>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BaseImportTestsModelsO2m> CreateAsync(BaseImportTestsModelsO2m input)
    {
        return await RequestAsync<BaseImportTestsModelsO2m>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BaseImportTestsModelsO2m), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsO2m> UpdateAsync(Guid id, BaseImportTestsModelsO2m input)
    {
        return await RequestAsync<BaseImportTestsModelsO2m>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(BaseImportTestsModelsO2m), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
