
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBaseImportTestsModelsCharRequiredAppService), typeof(BaseImportTestsModelsCharRequiredClientProxy))]
public partial class BaseImportTestsModelsCharRequiredClientProxy : ClientProxyBase<IBaseImportTestsModelsCharRequiredAppService>, IBaseImportTestsModelsCharRequiredAppService
{
    //public virtual async Task<ListResultDto<BaseImportTestsModelsCharRequired>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<BaseImportTestsModelsCharRequired>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<BaseImportTestsModelsCharRequired>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<BaseImportTestsModelsCharRequired>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharRequired> GetAsync(Guid id)
    {
        return await RequestAsync<BaseImportTestsModelsCharRequired>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharRequired> CreateAsync(BaseImportTestsModelsCharRequired input)
    {
        return await RequestAsync<BaseImportTestsModelsCharRequired>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BaseImportTestsModelsCharRequired), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsCharRequired> UpdateAsync(Guid id, BaseImportTestsModelsCharRequired input)
    {
        return await RequestAsync<BaseImportTestsModelsCharRequired>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(BaseImportTestsModelsCharRequired), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
