
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBaseImportTestsModelsCharAppService), typeof(BaseImportTestsModelsCharClientProxy))]
public partial class BaseImportTestsModelsCharClientProxy : ClientProxyBase<IBaseImportTestsModelsCharAppService>, IBaseImportTestsModelsCharAppService
{
    //public virtual async Task<ListResultDto<BaseImportTestsModelsChar>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<BaseImportTestsModelsChar>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<BaseImportTestsModelsChar>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<BaseImportTestsModelsChar>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsChar> GetAsync(Guid id)
    {
        return await RequestAsync<BaseImportTestsModelsChar>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BaseImportTestsModelsChar> CreateAsync(BaseImportTestsModelsChar input)
    {
        return await RequestAsync<BaseImportTestsModelsChar>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BaseImportTestsModelsChar), input }
        });
    }

    public virtual async Task<BaseImportTestsModelsChar> UpdateAsync(Guid id, BaseImportTestsModelsChar input)
    {
        return await RequestAsync<BaseImportTestsModelsChar>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(BaseImportTestsModelsChar), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
