
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBaseLanguageInstallAppService), typeof(BaseLanguageInstallClientProxy))]
public partial class BaseLanguageInstallClientProxy : ClientProxyBase<IBaseLanguageInstallAppService>, IBaseLanguageInstallAppService
{
    //public virtual async Task<ListResultDto<BaseLanguageInstall>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<BaseLanguageInstall>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<BaseLanguageInstall>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<BaseLanguageInstall>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<BaseLanguageInstall> GetAsync(Guid id)
    {
        return await RequestAsync<BaseLanguageInstall>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BaseLanguageInstall> CreateAsync(BaseLanguageInstall input)
    {
        return await RequestAsync<BaseLanguageInstall>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BaseLanguageInstall), input }
        });
    }

    public virtual async Task<BaseLanguageInstall> UpdateAsync(Guid id, BaseLanguageInstall input)
    {
        return await RequestAsync<BaseLanguageInstall>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(BaseLanguageInstall), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
