
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ICalendarEventTypeAppService), typeof(CalendarEventTypeClientProxy))]
public partial class CalendarEventTypeClientProxy : ClientProxyBase<ICalendarEventTypeAppService>, ICalendarEventTypeAppService
{
    //public virtual async Task<ListResultDto<CalendarEventType>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<CalendarEventType>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<CalendarEventType>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<CalendarEventType>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<CalendarEventType> GetAsync(long id)
    {
        return await RequestAsync<CalendarEventType>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<CalendarEventType> CreateAsync(CalendarEventType input)
    {
        return await RequestAsync<CalendarEventType>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CalendarEventType), input }
        });
    }

    public virtual async Task<CalendarEventType> UpdateAsync(long id, CalendarEventType input)
    {
        return await RequestAsync<CalendarEventType>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(CalendarEventType), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
