
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IChangePasswordWizardAppService), typeof(ChangePasswordWizardClientProxy))]
public partial class ChangePasswordWizardClientProxy : ClientProxyBase<IChangePasswordWizardAppService>, IChangePasswordWizardAppService
{
    //public virtual async Task<ListResultDto<ChangePasswordWizard>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ChangePasswordWizard>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ChangePasswordWizard>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ChangePasswordWizard>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ChangePasswordWizard> GetAsync(Guid id)
    {
        return await RequestAsync<ChangePasswordWizard>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ChangePasswordWizard> CreateAsync(ChangePasswordWizard input)
    {
        return await RequestAsync<ChangePasswordWizard>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ChangePasswordWizard), input }
        });
    }

    public virtual async Task<ChangePasswordWizard> UpdateAsync(Guid id, ChangePasswordWizard input)
    {
        return await RequestAsync<ChangePasswordWizard>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ChangePasswordWizard), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
