
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ICrmIapLeadMiningRequestAppService), typeof(CrmIapLeadMiningRequestClientProxy))]
public partial class CrmIapLeadMiningRequestClientProxy : ClientProxyBase<ICrmIapLeadMiningRequestAppService>, ICrmIapLeadMiningRequestAppService
{
    //public virtual async Task<ListResultDto<CrmIapLeadMiningRequest>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<CrmIapLeadMiningRequest>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<CrmIapLeadMiningRequest>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<CrmIapLeadMiningRequest>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<CrmIapLeadMiningRequest> GetAsync(Guid id)
    {
        return await RequestAsync<CrmIapLeadMiningRequest>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CrmIapLeadMiningRequest> CreateAsync(CrmIapLeadMiningRequest input)
    {
        return await RequestAsync<CrmIapLeadMiningRequest>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CrmIapLeadMiningRequest), input }
        });
    }

    public virtual async Task<CrmIapLeadMiningRequest> UpdateAsync(Guid id, CrmIapLeadMiningRequest input)
    {
        return await RequestAsync<CrmIapLeadMiningRequest>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CrmIapLeadMiningRequest), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
