
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFleetVehicleAppService), typeof(FleetVehicleClientProxy))]
public partial class FleetVehicleClientProxy : ClientProxyBase<IFleetVehicleAppService>, IFleetVehicleAppService
{
    //public virtual async Task<ListResultDto<FleetVehicle>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<FleetVehicle>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<FleetVehicle>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<FleetVehicle>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<FleetVehicle> GetAsync(Guid id)
    {
        return await RequestAsync<FleetVehicle>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<FleetVehicle> CreateAsync(FleetVehicle input)
    {
        return await RequestAsync<FleetVehicle>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(FleetVehicle), input }
        });
    }

    public virtual async Task<FleetVehicle> UpdateAsync(Guid id, FleetVehicle input)
    {
        return await RequestAsync<FleetVehicle>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(FleetVehicle), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
