
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFollowupLineAppService), typeof(FollowupLineClientProxy))]
public partial class FollowupLineClientProxy : ClientProxyBase<IFollowupLineAppService>, IFollowupLineAppService
{
    //public virtual async Task<ListResultDto<FollowupLine>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<FollowupLine>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<FollowupLine>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<FollowupLine>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<FollowupLine> GetAsync(Guid id)
    {
        return await RequestAsync<FollowupLine>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<FollowupLine> CreateAsync(FollowupLine input)
    {
        return await RequestAsync<FollowupLine>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(FollowupLine), input }
        });
    }

    public virtual async Task<FollowupLine> UpdateAsync(Guid id, FollowupLine input)
    {
        return await RequestAsync<FollowupLine>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(FollowupLine), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
