
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrDepartureReasonAppService), typeof(HrDepartureReasonClientProxy))]
public partial class HrDepartureReasonClientProxy : ClientProxyBase<IHrDepartureReasonAppService>, IHrDepartureReasonAppService
{
    //public virtual async Task<ListResultDto<HrDepartureReason>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrDepartureReason>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrDepartureReason>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrDepartureReason>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrDepartureReason> GetAsync(long id)
    {
        return await RequestAsync<HrDepartureReason>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<HrDepartureReason> CreateAsync(HrDepartureReason input)
    {
        return await RequestAsync<HrDepartureReason>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrDepartureReason), input }
        });
    }

    public virtual async Task<HrDepartureReason> UpdateAsync(long id, HrDepartureReason input)
    {
        return await RequestAsync<HrDepartureReason>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(HrDepartureReason), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
