
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrEmployeeAppService), typeof(HrEmployeeClientProxy))]
public partial class HrEmployeeClientProxy : ClientProxyBase<IHrEmployeeAppService>, IHrEmployeeAppService
{
    //public virtual async Task<ListResultDto<HrEmployee>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrEmployee>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrEmployee>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrEmployee>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrEmployee> GetAsync(Guid id)
    {
        return await RequestAsync<HrEmployee>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrEmployee> CreateAsync(HrEmployee input)
    {
        return await RequestAsync<HrEmployee>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrEmployee), input }
        });
    }

    public virtual async Task<HrEmployee> UpdateAsync(Guid id, HrEmployee input)
    {
        return await RequestAsync<HrEmployee>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrEmployee), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
