
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrExpenseSheetAppService), typeof(HrExpenseSheetClientProxy))]
public partial class HrExpenseSheetClientProxy : ClientProxyBase<IHrExpenseSheetAppService>, IHrExpenseSheetAppService
{
    //public virtual async Task<ListResultDto<HrExpenseSheet>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrExpenseSheet>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrExpenseSheet>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrExpenseSheet>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrExpenseSheet> GetAsync(Guid id)
    {
        return await RequestAsync<HrExpenseSheet>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrExpenseSheet> CreateAsync(HrExpenseSheet input)
    {
        return await RequestAsync<HrExpenseSheet>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrExpenseSheet), input }
        });
    }

    public virtual async Task<HrExpenseSheet> UpdateAsync(Guid id, HrExpenseSheet input)
    {
        return await RequestAsync<HrExpenseSheet>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrExpenseSheet), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
