
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrExpenseApproveDuplicateAppService), typeof(HrExpenseApproveDuplicateClientProxy))]
public partial class HrExpenseApproveDuplicateClientProxy : ClientProxyBase<IHrExpenseApproveDuplicateAppService>, IHrExpenseApproveDuplicateAppService
{
    //public virtual async Task<ListResultDto<HrExpenseApproveDuplicate>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrExpenseApproveDuplicate>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrExpenseApproveDuplicate>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrExpenseApproveDuplicate>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrExpenseApproveDuplicate> GetAsync(Guid id)
    {
        return await RequestAsync<HrExpenseApproveDuplicate>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrExpenseApproveDuplicate> CreateAsync(HrExpenseApproveDuplicate input)
    {
        return await RequestAsync<HrExpenseApproveDuplicate>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrExpenseApproveDuplicate), input }
        });
    }

    public virtual async Task<HrExpenseApproveDuplicate> UpdateAsync(Guid id, HrExpenseApproveDuplicate input)
    {
        return await RequestAsync<HrExpenseApproveDuplicate>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrExpenseApproveDuplicate), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
