
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrExpenseSplitAppService), typeof(HrExpenseSplitClientProxy))]
public partial class HrExpenseSplitClientProxy : ClientProxyBase<IHrExpenseSplitAppService>, IHrExpenseSplitAppService
{
    //public virtual async Task<ListResultDto<HrExpenseSplit>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrExpenseSplit>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrExpenseSplit>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrExpenseSplit>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrExpenseSplit> GetAsync(Guid id)
    {
        return await RequestAsync<HrExpenseSplit>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrExpenseSplit> CreateAsync(HrExpenseSplit input)
    {
        return await RequestAsync<HrExpenseSplit>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrExpenseSplit), input }
        });
    }

    public virtual async Task<HrExpenseSplit> UpdateAsync(Guid id, HrExpenseSplit input)
    {
        return await RequestAsync<HrExpenseSplit>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrExpenseSplit), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
