
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrExpenseAppService), typeof(HrExpenseClientProxy))]
public partial class HrExpenseClientProxy : ClientProxyBase<IHrExpenseAppService>, IHrExpenseAppService
{
    //public virtual async Task<ListResultDto<HrExpense>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrExpense>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrExpense>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrExpense>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrExpense> GetAsync(Guid id)
    {
        return await RequestAsync<HrExpense>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrExpense> CreateAsync(HrExpense input)
    {
        return await RequestAsync<HrExpense>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrExpense), input }
        });
    }

    public virtual async Task<HrExpense> UpdateAsync(Guid id, HrExpense input)
    {
        return await RequestAsync<HrExpense>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrExpense), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
