
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrPlanWizardAppService), typeof(HrPlanWizardClientProxy))]
public partial class HrPlanWizardClientProxy : ClientProxyBase<IHrPlanWizardAppService>, IHrPlanWizardAppService
{
    //public virtual async Task<ListResultDto<HrPlanWizard>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrPlanWizard>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrPlanWizard>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrPlanWizard>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrPlanWizard> GetAsync(Guid id)
    {
        return await RequestAsync<HrPlanWizard>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrPlanWizard> CreateAsync(HrPlanWizard input)
    {
        return await RequestAsync<HrPlanWizard>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrPlanWizard), input }
        });
    }

    public virtual async Task<HrPlanWizard> UpdateAsync(Guid id, HrPlanWizard input)
    {
        return await RequestAsync<HrPlanWizard>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrPlanWizard), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
