
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrRecruitmentSourceAppService), typeof(HrRecruitmentSourceClientProxy))]
public partial class HrRecruitmentSourceClientProxy : ClientProxyBase<IHrRecruitmentSourceAppService>, IHrRecruitmentSourceAppService
{
    //public virtual async Task<ListResultDto<HrRecruitmentSource>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrRecruitmentSource>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrRecruitmentSource>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrRecruitmentSource>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrRecruitmentSource> GetAsync(Guid id)
    {
        return await RequestAsync<HrRecruitmentSource>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrRecruitmentSource> CreateAsync(HrRecruitmentSource input)
    {
        return await RequestAsync<HrRecruitmentSource>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrRecruitmentSource), input }
        });
    }

    public virtual async Task<HrRecruitmentSource> UpdateAsync(Guid id, HrRecruitmentSource input)
    {
        return await RequestAsync<HrRecruitmentSource>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrRecruitmentSource), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
