
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrRecruitmentStageAppService), typeof(HrRecruitmentStageClientProxy))]
public partial class HrRecruitmentStageClientProxy : ClientProxyBase<IHrRecruitmentStageAppService>, IHrRecruitmentStageAppService
{
    //public virtual async Task<ListResultDto<HrRecruitmentStage>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrRecruitmentStage>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrRecruitmentStage>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrRecruitmentStage>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrRecruitmentStage> GetAsync(long id)
    {
        return await RequestAsync<HrRecruitmentStage>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<HrRecruitmentStage> CreateAsync(HrRecruitmentStage input)
    {
        return await RequestAsync<HrRecruitmentStage>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrRecruitmentStage), input }
        });
    }

    public virtual async Task<HrRecruitmentStage> UpdateAsync(long id, HrRecruitmentStage input)
    {
        return await RequestAsync<HrRecruitmentStage>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(HrRecruitmentStage), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
