
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrSkillLevelAppService), typeof(HrSkillLevelClientProxy))]
public partial class HrSkillLevelClientProxy : ClientProxyBase<IHrSkillLevelAppService>, IHrSkillLevelAppService
{
    //public virtual async Task<ListResultDto<HrSkillLevel>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrSkillLevel>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrSkillLevel>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrSkillLevel>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrSkillLevel> GetAsync(long id)
    {
        return await RequestAsync<HrSkillLevel>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<HrSkillLevel> CreateAsync(HrSkillLevel input)
    {
        return await RequestAsync<HrSkillLevel>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrSkillLevel), input }
        });
    }

    public virtual async Task<HrSkillLevel> UpdateAsync(long id, HrSkillLevel input)
    {
        return await RequestAsync<HrSkillLevel>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(HrSkillLevel), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
