
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrSkillAppService), typeof(HrSkillClientProxy))]
public partial class HrSkillClientProxy : ClientProxyBase<IHrSkillAppService>, IHrSkillAppService
{
    //public virtual async Task<ListResultDto<HrSkill>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrSkill>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrSkill>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrSkill>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrSkill> GetAsync(Guid id)
    {
        return await RequestAsync<HrSkill>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrSkill> CreateAsync(HrSkill input)
    {
        return await RequestAsync<HrSkill>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrSkill), input }
        });
    }

    public virtual async Task<HrSkill> UpdateAsync(Guid id, HrSkill input)
    {
        return await RequestAsync<HrSkill>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrSkill), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
