
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHrWorkLocationAppService), typeof(HrWorkLocationClientProxy))]
public partial class HrWorkLocationClientProxy : ClientProxyBase<IHrWorkLocationAppService>, IHrWorkLocationAppService
{
    //public virtual async Task<ListResultDto<HrWorkLocation>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<HrWorkLocation>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<HrWorkLocation>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<HrWorkLocation>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<HrWorkLocation> GetAsync(Guid id)
    {
        return await RequestAsync<HrWorkLocation>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HrWorkLocation> CreateAsync(HrWorkLocation input)
    {
        return await RequestAsync<HrWorkLocation>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HrWorkLocation), input }
        });
    }

    public virtual async Task<HrWorkLocation> UpdateAsync(Guid id, HrWorkLocation input)
    {
        return await RequestAsync<HrWorkLocation>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HrWorkLocation), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
