
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIrActWindowAppService), typeof(IrActWindowClientProxy))]
public partial class IrActWindowClientProxy : ClientProxyBase<IIrActWindowAppService>, IIrActWindowAppService
{
    //public virtual async Task<ListResultDto<IrActWindow>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<IrActWindow>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<IrActWindow>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IrActWindow>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<IrActWindow> GetAsync(Guid id)
    {
        return await RequestAsync<IrActWindow>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IrActWindow> CreateAsync(IrActWindow input)
    {
        return await RequestAsync<IrActWindow>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IrActWindow), input }
        });
    }

    public virtual async Task<IrActWindow> UpdateAsync(Guid id, IrActWindow input)
    {
        return await RequestAsync<IrActWindow>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IrActWindow), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
