
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIrLoggingAppService), typeof(IrLoggingClientProxy))]
public partial class IrLoggingClientProxy : ClientProxyBase<IIrLoggingAppService>, IIrLoggingAppService
{
    //public virtual async Task<ListResultDto<IrLogging>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<IrLogging>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<IrLogging>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IrLogging>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<IrLogging> GetAsync(Guid id)
    {
        return await RequestAsync<IrLogging>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IrLogging> CreateAsync(IrLogging input)
    {
        return await RequestAsync<IrLogging>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IrLogging), input }
        });
    }

    public virtual async Task<IrLogging> UpdateAsync(Guid id, IrLogging input)
    {
        return await RequestAsync<IrLogging>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IrLogging), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
