
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIrModelFieldsSelectionAppService), typeof(IrModelFieldsSelectionClientProxy))]
public partial class IrModelFieldsSelectionClientProxy : ClientProxyBase<IIrModelFieldsSelectionAppService>, IIrModelFieldsSelectionAppService
{
    //public virtual async Task<ListResultDto<IrModelFieldsSelection>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<IrModelFieldsSelection>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<IrModelFieldsSelection>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IrModelFieldsSelection>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<IrModelFieldsSelection> GetAsync(Guid id)
    {
        return await RequestAsync<IrModelFieldsSelection>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IrModelFieldsSelection> CreateAsync(IrModelFieldsSelection input)
    {
        return await RequestAsync<IrModelFieldsSelection>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IrModelFieldsSelection), input }
        });
    }

    public virtual async Task<IrModelFieldsSelection> UpdateAsync(Guid id, IrModelFieldsSelection input)
    {
        return await RequestAsync<IrModelFieldsSelection>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IrModelFieldsSelection), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
