
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIrRuleAppService), typeof(IrRuleClientProxy))]
public partial class IrRuleClientProxy : ClientProxyBase<IIrRuleAppService>, IIrRuleAppService
{
    //public virtual async Task<ListResultDto<IrRule>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<IrRule>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<IrRule>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IrRule>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<IrRule> GetAsync(Guid id)
    {
        return await RequestAsync<IrRule>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IrRule> CreateAsync(IrRule input)
    {
        return await RequestAsync<IrRule>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IrRule), input }
        });
    }

    public virtual async Task<IrRule> UpdateAsync(Guid id, IrRule input)
    {
        return await RequestAsync<IrRule>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IrRule), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
