
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIrSequenceDateRangeAppService), typeof(IrSequenceDateRangeClientProxy))]
public partial class IrSequenceDateRangeClientProxy : ClientProxyBase<IIrSequenceDateRangeAppService>, IIrSequenceDateRangeAppService
{
    //public virtual async Task<ListResultDto<IrSequenceDateRange>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<IrSequenceDateRange>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<IrSequenceDateRange>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IrSequenceDateRange>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<IrSequenceDateRange> GetAsync(Guid id)
    {
        return await RequestAsync<IrSequenceDateRange>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IrSequenceDateRange> CreateAsync(IrSequenceDateRange input)
    {
        return await RequestAsync<IrSequenceDateRange>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IrSequenceDateRange), input }
        });
    }

    public virtual async Task<IrSequenceDateRange> UpdateAsync(Guid id, IrSequenceDateRange input)
    {
        return await RequestAsync<IrSequenceDateRange>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IrSequenceDateRange), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
