
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIrSequenceAppService), typeof(IrSequenceClientProxy))]
public partial class IrSequenceClientProxy : ClientProxyBase<IIrSequenceAppService>, IIrSequenceAppService
{
    //public virtual async Task<ListResultDto<IrSequence>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<IrSequence>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<IrSequence>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IrSequence>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<IrSequence> GetAsync(Guid id)
    {
        return await RequestAsync<IrSequence>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IrSequence> CreateAsync(IrSequence input)
    {
        return await RequestAsync<IrSequence>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IrSequence), input }
        });
    }

    public virtual async Task<IrSequence> UpdateAsync(Guid id, IrSequence input)
    {
        return await RequestAsync<IrSequence>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IrSequence), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
