
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ILunchToppingAppService), typeof(LunchToppingClientProxy))]
public partial class LunchToppingClientProxy : ClientProxyBase<ILunchToppingAppService>, ILunchToppingAppService
{
    //public virtual async Task<ListResultDto<LunchTopping>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<LunchTopping>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<LunchTopping>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LunchTopping>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<LunchTopping> GetAsync(Guid id)
    {
        return await RequestAsync<LunchTopping>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<LunchTopping> CreateAsync(LunchTopping input)
    {
        return await RequestAsync<LunchTopping>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LunchTopping), input }
        });
    }

    public virtual async Task<LunchTopping> UpdateAsync(Guid id, LunchTopping input)
    {
        return await RequestAsync<LunchTopping>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(LunchTopping), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
