
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMailMessageAppService), typeof(MailMessageClientProxy))]
public partial class MailMessageClientProxy : ClientProxyBase<IMailMessageAppService>, IMailMessageAppService
{
    //public virtual async Task<ListResultDto<MailMessage>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MailMessage>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MailMessage>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MailMessage>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MailMessage> GetAsync(Guid id)
    {
        return await RequestAsync<MailMessage>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MailMessage> CreateAsync(MailMessage input)
    {
        return await RequestAsync<MailMessage>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MailMessage), input }
        });
    }

    public virtual async Task<MailMessage> UpdateAsync(Guid id, MailMessage input)
    {
        return await RequestAsync<MailMessage>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MailMessage), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
