
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMailTrackingValueAppService), typeof(MailTrackingValueClientProxy))]
public partial class MailTrackingValueClientProxy : ClientProxyBase<IMailTrackingValueAppService>, IMailTrackingValueAppService
{
    //public virtual async Task<ListResultDto<MailTrackingValue>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MailTrackingValue>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MailTrackingValue>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MailTrackingValue>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MailTrackingValue> GetAsync(Guid id)
    {
        return await RequestAsync<MailTrackingValue>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MailTrackingValue> CreateAsync(MailTrackingValue input)
    {
        return await RequestAsync<MailTrackingValue>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MailTrackingValue), input }
        });
    }

    public virtual async Task<MailTrackingValue> UpdateAsync(Guid id, MailTrackingValue input)
    {
        return await RequestAsync<MailTrackingValue>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MailTrackingValue), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
