
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMailIceServerAppService), typeof(MailIceServerClientProxy))]
public partial class MailIceServerClientProxy : ClientProxyBase<IMailIceServerAppService>, IMailIceServerAppService
{
    //public virtual async Task<ListResultDto<MailIceServer>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MailIceServer>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MailIceServer>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MailIceServer>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MailIceServer> GetAsync(Guid id)
    {
        return await RequestAsync<MailIceServer>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MailIceServer> CreateAsync(MailIceServer input)
    {
        return await RequestAsync<MailIceServer>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MailIceServer), input }
        });
    }

    public virtual async Task<MailIceServer> UpdateAsync(Guid id, MailIceServer input)
    {
        return await RequestAsync<MailIceServer>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MailIceServer), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
