
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMaintenanceTeamAppService), typeof(MaintenanceTeamClientProxy))]
public partial class MaintenanceTeamClientProxy : ClientProxyBase<IMaintenanceTeamAppService>, IMaintenanceTeamAppService
{
    //public virtual async Task<ListResultDto<MaintenanceTeam>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MaintenanceTeam>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MaintenanceTeam>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MaintenanceTeam>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MaintenanceTeam> GetAsync(Guid id)
    {
        return await RequestAsync<MaintenanceTeam>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MaintenanceTeam> CreateAsync(MaintenanceTeam input)
    {
        return await RequestAsync<MaintenanceTeam>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MaintenanceTeam), input }
        });
    }

    public virtual async Task<MaintenanceTeam> UpdateAsync(Guid id, MaintenanceTeam input)
    {
        return await RequestAsync<MaintenanceTeam>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MaintenanceTeam), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
