
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMrpBomLineAppService), typeof(MrpBomLineClientProxy))]
public partial class MrpBomLineClientProxy : ClientProxyBase<IMrpBomLineAppService>, IMrpBomLineAppService
{
    //public virtual async Task<ListResultDto<MrpBomLine>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MrpBomLine>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MrpBomLine>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MrpBomLine>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MrpBomLine> GetAsync(Guid id)
    {
        return await RequestAsync<MrpBomLine>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MrpBomLine> CreateAsync(MrpBomLine input)
    {
        return await RequestAsync<MrpBomLine>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MrpBomLine), input }
        });
    }

    public virtual async Task<MrpBomLine> UpdateAsync(Guid id, MrpBomLine input)
    {
        return await RequestAsync<MrpBomLine>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MrpBomLine), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
