
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMrpConsumptionWarningLineAppService), typeof(MrpConsumptionWarningLineClientProxy))]
public partial class MrpConsumptionWarningLineClientProxy : ClientProxyBase<IMrpConsumptionWarningLineAppService>, IMrpConsumptionWarningLineAppService
{
    //public virtual async Task<ListResultDto<MrpConsumptionWarningLine>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MrpConsumptionWarningLine>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MrpConsumptionWarningLine>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MrpConsumptionWarningLine>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MrpConsumptionWarningLine> GetAsync(Guid id)
    {
        return await RequestAsync<MrpConsumptionWarningLine>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MrpConsumptionWarningLine> CreateAsync(MrpConsumptionWarningLine input)
    {
        return await RequestAsync<MrpConsumptionWarningLine>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MrpConsumptionWarningLine), input }
        });
    }

    public virtual async Task<MrpConsumptionWarningLine> UpdateAsync(Guid id, MrpConsumptionWarningLine input)
    {
        return await RequestAsync<MrpConsumptionWarningLine>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MrpConsumptionWarningLine), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
