
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMrpImmediateProductionAppService), typeof(MrpImmediateProductionClientProxy))]
public partial class MrpImmediateProductionClientProxy : ClientProxyBase<IMrpImmediateProductionAppService>, IMrpImmediateProductionAppService
{
    //public virtual async Task<ListResultDto<MrpImmediateProduction>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MrpImmediateProduction>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MrpImmediateProduction>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MrpImmediateProduction>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MrpImmediateProduction> GetAsync(Guid id)
    {
        return await RequestAsync<MrpImmediateProduction>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MrpImmediateProduction> CreateAsync(MrpImmediateProduction input)
    {
        return await RequestAsync<MrpImmediateProduction>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MrpImmediateProduction), input }
        });
    }

    public virtual async Task<MrpImmediateProduction> UpdateAsync(Guid id, MrpImmediateProduction input)
    {
        return await RequestAsync<MrpImmediateProduction>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MrpImmediateProduction), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
