
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMrpWorkcenterAppService), typeof(MrpWorkcenterClientProxy))]
public partial class MrpWorkcenterClientProxy : ClientProxyBase<IMrpWorkcenterAppService>, IMrpWorkcenterAppService
{
    //public virtual async Task<ListResultDto<MrpWorkcenter>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<MrpWorkcenter>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<MrpWorkcenter>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MrpWorkcenter>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<MrpWorkcenter> GetAsync(Guid id)
    {
        return await RequestAsync<MrpWorkcenter>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MrpWorkcenter> CreateAsync(MrpWorkcenter input)
    {
        return await RequestAsync<MrpWorkcenter>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MrpWorkcenter), input }
        });
    }

    public virtual async Task<MrpWorkcenter> UpdateAsync(Guid id, MrpWorkcenter input)
    {
        return await RequestAsync<MrpWorkcenter>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MrpWorkcenter), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
