
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPaymentProviderAppService), typeof(PaymentProviderClientProxy))]
public partial class PaymentProviderClientProxy : ClientProxyBase<IPaymentProviderAppService>, IPaymentProviderAppService
{
    //public virtual async Task<ListResultDto<PaymentProvider>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PaymentProvider>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PaymentProvider>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PaymentProvider>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PaymentProvider> GetAsync(Guid id)
    {
        return await RequestAsync<PaymentProvider>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PaymentProvider> CreateAsync(PaymentProvider input)
    {
        return await RequestAsync<PaymentProvider>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PaymentProvider), input }
        });
    }

    public virtual async Task<PaymentProvider> UpdateAsync(Guid id, PaymentProvider input)
    {
        return await RequestAsync<PaymentProvider>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PaymentProvider), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
