
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPaymentIconAppService), typeof(PaymentIconClientProxy))]
public partial class PaymentIconClientProxy : ClientProxyBase<IPaymentIconAppService>, IPaymentIconAppService
{
    //public virtual async Task<ListResultDto<PaymentIcon>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PaymentIcon>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PaymentIcon>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PaymentIcon>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PaymentIcon> GetAsync(Guid id)
    {
        return await RequestAsync<PaymentIcon>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PaymentIcon> CreateAsync(PaymentIcon input)
    {
        return await RequestAsync<PaymentIcon>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PaymentIcon), input }
        });
    }

    public virtual async Task<PaymentIcon> UpdateAsync(Guid id, PaymentIcon input)
    {
        return await RequestAsync<PaymentIcon>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PaymentIcon), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
