
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPortalShareAppService), typeof(PortalShareClientProxy))]
public partial class PortalShareClientProxy : ClientProxyBase<IPortalShareAppService>, IPortalShareAppService
{
    //public virtual async Task<ListResultDto<PortalShare>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PortalShare>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PortalShare>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PortalShare>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PortalShare> GetAsync(Guid id)
    {
        return await RequestAsync<PortalShare>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PortalShare> CreateAsync(PortalShare input)
    {
        return await RequestAsync<PortalShare>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PortalShare), input }
        });
    }

    public virtual async Task<PortalShare> UpdateAsync(Guid id, PortalShare input)
    {
        return await RequestAsync<PortalShare>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PortalShare), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
