
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPortalWizardAppService), typeof(PortalWizardClientProxy))]
public partial class PortalWizardClientProxy : ClientProxyBase<IPortalWizardAppService>, IPortalWizardAppService
{
    //public virtual async Task<ListResultDto<PortalWizard>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PortalWizard>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PortalWizard>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PortalWizard>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PortalWizard> GetAsync(Guid id)
    {
        return await RequestAsync<PortalWizard>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PortalWizard> CreateAsync(PortalWizard input)
    {
        return await RequestAsync<PortalWizard>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PortalWizard), input }
        });
    }

    public virtual async Task<PortalWizard> UpdateAsync(Guid id, PortalWizard input)
    {
        return await RequestAsync<PortalWizard>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PortalWizard), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
