
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPortalWizardUserAppService), typeof(PortalWizardUserClientProxy))]
public partial class PortalWizardUserClientProxy : ClientProxyBase<IPortalWizardUserAppService>, IPortalWizardUserAppService
{
    //public virtual async Task<ListResultDto<PortalWizardUser>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PortalWizardUser>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PortalWizardUser>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PortalWizardUser>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PortalWizardUser> GetAsync(Guid id)
    {
        return await RequestAsync<PortalWizardUser>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PortalWizardUser> CreateAsync(PortalWizardUser input)
    {
        return await RequestAsync<PortalWizardUser>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PortalWizardUser), input }
        });
    }

    public virtual async Task<PortalWizardUser> UpdateAsync(Guid id, PortalWizardUser input)
    {
        return await RequestAsync<PortalWizardUser>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PortalWizardUser), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
