
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPosBillAppService), typeof(PosBillClientProxy))]
public partial class PosBillClientProxy : ClientProxyBase<IPosBillAppService>, IPosBillAppService
{
    //public virtual async Task<ListResultDto<PosBill>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PosBill>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PosBill>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PosBill>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PosBill> GetAsync(Guid id)
    {
        return await RequestAsync<PosBill>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PosBill> CreateAsync(PosBill input)
    {
        return await RequestAsync<PosBill>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PosBill), input }
        });
    }

    public virtual async Task<PosBill> UpdateAsync(Guid id, PosBill input)
    {
        return await RequestAsync<PosBill>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PosBill), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
