
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPosCategoryAppService), typeof(PosCategoryClientProxy))]
public partial class PosCategoryClientProxy : ClientProxyBase<IPosCategoryAppService>, IPosCategoryAppService
{
    //public virtual async Task<ListResultDto<PosCategory>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<PosCategory>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<PosCategory>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<PosCategory>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<PosCategory> GetAsync(long id)
    {
        return await RequestAsync<PosCategory>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<PosCategory> CreateAsync(PosCategory input)
    {
        return await RequestAsync<PosCategory>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PosCategory), input }
        });
    }

    public virtual async Task<PosCategory> UpdateAsync(long id, PosCategory input)
    {
        return await RequestAsync<PosCategory>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(PosCategory), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
