
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProductPublicCategoryAppService), typeof(ProductPublicCategoryClientProxy))]
public partial class ProductPublicCategoryClientProxy : ClientProxyBase<IProductPublicCategoryAppService>, IProductPublicCategoryAppService
{
    //public virtual async Task<ListResultDto<ProductPublicCategory>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ProductPublicCategory>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ProductPublicCategory>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ProductPublicCategory>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ProductPublicCategory> GetAsync(long id)
    {
        return await RequestAsync<ProductPublicCategory>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<ProductPublicCategory> CreateAsync(ProductPublicCategory input)
    {
        return await RequestAsync<ProductPublicCategory>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProductPublicCategory), input }
        });
    }

    public virtual async Task<ProductPublicCategory> UpdateAsync(long id, ProductPublicCategory input)
    {
        return await RequestAsync<ProductPublicCategory>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(ProductPublicCategory), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
