
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProductTemplateAppService), typeof(ProductTemplateClientProxy))]
public partial class ProductTemplateClientProxy : ClientProxyBase<IProductTemplateAppService>, IProductTemplateAppService
{
    //public virtual async Task<ListResultDto<ProductTemplate>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ProductTemplate>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ProductTemplate>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ProductTemplate>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ProductTemplate> GetAsync(Guid id)
    {
        return await RequestAsync<ProductTemplate>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ProductTemplate> CreateAsync(ProductTemplate input)
    {
        return await RequestAsync<ProductTemplate>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProductTemplate), input }
        });
    }

    public virtual async Task<ProductTemplate> UpdateAsync(Guid id, ProductTemplate input)
    {
        return await RequestAsync<ProductTemplate>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ProductTemplate), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
