
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProductAttributeValueAppService), typeof(ProductAttributeValueClientProxy))]
public partial class ProductAttributeValueClientProxy : ClientProxyBase<IProductAttributeValueAppService>, IProductAttributeValueAppService
{
    //public virtual async Task<ListResultDto<ProductAttributeValue>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ProductAttributeValue>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ProductAttributeValue>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ProductAttributeValue>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ProductAttributeValue> GetAsync(Guid id)
    {
        return await RequestAsync<ProductAttributeValue>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ProductAttributeValue> CreateAsync(ProductAttributeValue input)
    {
        return await RequestAsync<ProductAttributeValue>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProductAttributeValue), input }
        });
    }

    public virtual async Task<ProductAttributeValue> UpdateAsync(Guid id, ProductAttributeValue input)
    {
        return await RequestAsync<ProductAttributeValue>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ProductAttributeValue), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
