
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProductProductAppService), typeof(ProductProductClientProxy))]
public partial class ProductProductClientProxy : ClientProxyBase<IProductProductAppService>, IProductProductAppService
{
    //public virtual async Task<ListResultDto<ProductProduct>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ProductProduct>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ProductProduct>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ProductProduct>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ProductProduct> GetAsync(Guid id)
    {
        return await RequestAsync<ProductProduct>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ProductProduct> CreateAsync(ProductProduct input)
    {
        return await RequestAsync<ProductProduct>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProductProduct), input }
        });
    }

    public virtual async Task<ProductProduct> UpdateAsync(Guid id, ProductProduct input)
    {
        return await RequestAsync<ProductProduct>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ProductProduct), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
