
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IResetViewArchWizardAppService), typeof(ResetViewArchWizardClientProxy))]
public partial class ResetViewArchWizardClientProxy : ClientProxyBase<IResetViewArchWizardAppService>, IResetViewArchWizardAppService
{
    //public virtual async Task<ListResultDto<ResetViewArchWizard>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ResetViewArchWizard>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ResetViewArchWizard>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ResetViewArchWizard>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ResetViewArchWizard> GetAsync(Guid id)
    {
        return await RequestAsync<ResetViewArchWizard>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ResetViewArchWizard> CreateAsync(ResetViewArchWizard input)
    {
        return await RequestAsync<ResetViewArchWizard>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResetViewArchWizard), input }
        });
    }

    public virtual async Task<ResetViewArchWizard> UpdateAsync(Guid id, ResetViewArchWizard input)
    {
        return await RequestAsync<ResetViewArchWizard>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ResetViewArchWizard), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
