
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IResourceCalendarAppService), typeof(ResourceCalendarClientProxy))]
public partial class ResourceCalendarClientProxy : ClientProxyBase<IResourceCalendarAppService>, IResourceCalendarAppService
{
    //public virtual async Task<ListResultDto<ResourceCalendar>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ResourceCalendar>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ResourceCalendar>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ResourceCalendar>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ResourceCalendar> GetAsync(Guid id)
    {
        return await RequestAsync<ResourceCalendar>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ResourceCalendar> CreateAsync(ResourceCalendar input)
    {
        return await RequestAsync<ResourceCalendar>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResourceCalendar), input }
        });
    }

    public virtual async Task<ResourceCalendar> UpdateAsync(Guid id, ResourceCalendar input)
    {
        return await RequestAsync<ResourceCalendar>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ResourceCalendar), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
