
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IResPartnerIndustryAppService), typeof(ResPartnerIndustryClientProxy))]
public partial class ResPartnerIndustryClientProxy : ClientProxyBase<IResPartnerIndustryAppService>, IResPartnerIndustryAppService
{
    //public virtual async Task<ListResultDto<ResPartnerIndustry>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ResPartnerIndustry>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ResPartnerIndustry>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ResPartnerIndustry>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ResPartnerIndustry> GetAsync(long id)
    {
        return await RequestAsync<ResPartnerIndustry>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<ResPartnerIndustry> CreateAsync(ResPartnerIndustry input)
    {
        return await RequestAsync<ResPartnerIndustry>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResPartnerIndustry), input }
        });
    }

    public virtual async Task<ResPartnerIndustry> UpdateAsync(long id, ResPartnerIndustry input)
    {
        return await RequestAsync<ResPartnerIndustry>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(ResPartnerIndustry), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
