
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IResPartnerTitleAppService), typeof(ResPartnerTitleClientProxy))]
public partial class ResPartnerTitleClientProxy : ClientProxyBase<IResPartnerTitleAppService>, IResPartnerTitleAppService
{
    //public virtual async Task<ListResultDto<ResPartnerTitle>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ResPartnerTitle>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ResPartnerTitle>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ResPartnerTitle>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ResPartnerTitle> GetAsync(long id)
    {
        return await RequestAsync<ResPartnerTitle>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<ResPartnerTitle> CreateAsync(ResPartnerTitle input)
    {
        return await RequestAsync<ResPartnerTitle>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResPartnerTitle), input }
        });
    }

    public virtual async Task<ResPartnerTitle> UpdateAsync(long id, ResPartnerTitle input)
    {
        return await RequestAsync<ResPartnerTitle>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(ResPartnerTitle), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }
}
