
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IResUsersSettingAppService), typeof(ResUsersSettingClientProxy))]
public partial class ResUsersSettingClientProxy : ClientProxyBase<IResUsersSettingAppService>, IResUsersSettingAppService
{
    //public virtual async Task<ListResultDto<ResUsersSetting>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ResUsersSetting>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ResUsersSetting>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ResUsersSetting>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ResUsersSetting> GetAsync(Guid id)
    {
        return await RequestAsync<ResUsersSetting>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ResUsersSetting> CreateAsync(ResUsersSetting input)
    {
        return await RequestAsync<ResUsersSetting>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResUsersSetting), input }
        });
    }

    public virtual async Task<ResUsersSetting> UpdateAsync(Guid id, ResUsersSetting input)
    {
        return await RequestAsync<ResUsersSetting>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ResUsersSetting), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
