
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IResUsersLogAppService), typeof(ResUsersLogClientProxy))]
public partial class ResUsersLogClientProxy : ClientProxyBase<IResUsersLogAppService>, IResUsersLogAppService
{
    //public virtual async Task<ListResultDto<ResUsersLog>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<ResUsersLog>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<ResUsersLog>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<ResUsersLog>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ResUsersLog> GetAsync(Guid id)
    {
        return await RequestAsync<ResUsersLog>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ResUsersLog> CreateAsync(ResUsersLog input)
    {
        return await RequestAsync<ResUsersLog>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResUsersLog), input }
        });
    }

    public virtual async Task<ResUsersLog> UpdateAsync(Guid id, ResUsersLog input)
    {
        return await RequestAsync<ResUsersLog>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ResUsersLog), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
