
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISaleOrderAppService), typeof(SaleOrderClientProxy))]
public partial class SaleOrderClientProxy : ClientProxyBase<ISaleOrderAppService>, ISaleOrderAppService
{
    //public virtual async Task<ListResultDto<SaleOrder>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<SaleOrder>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<SaleOrder>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<SaleOrder>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<SaleOrder> GetAsync(Guid id)
    {
        return await RequestAsync<SaleOrder>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<SaleOrder> CreateAsync(SaleOrder input)
    {
        return await RequestAsync<SaleOrder>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SaleOrder), input }
        });
    }

    public virtual async Task<SaleOrder> UpdateAsync(Guid id, SaleOrder input)
    {
        return await RequestAsync<SaleOrder>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SaleOrder), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
