
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISaleOrderCancelAppService), typeof(SaleOrderCancelClientProxy))]
public partial class SaleOrderCancelClientProxy : ClientProxyBase<ISaleOrderCancelAppService>, ISaleOrderCancelAppService
{
    //public virtual async Task<ListResultDto<SaleOrderCancel>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<SaleOrderCancel>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<SaleOrderCancel>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<SaleOrderCancel>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<SaleOrderCancel> GetAsync(Guid id)
    {
        return await RequestAsync<SaleOrderCancel>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<SaleOrderCancel> CreateAsync(SaleOrderCancel input)
    {
        return await RequestAsync<SaleOrderCancel>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SaleOrderCancel), input }
        });
    }

    public virtual async Task<SaleOrderCancel> UpdateAsync(Guid id, SaleOrderCancel input)
    {
        return await RequestAsync<SaleOrderCancel>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SaleOrderCancel), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
