
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISmsComposerAppService), typeof(SmsComposerClientProxy))]
public partial class SmsComposerClientProxy : ClientProxyBase<ISmsComposerAppService>, ISmsComposerAppService
{
    //public virtual async Task<ListResultDto<SmsComposer>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<SmsComposer>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<SmsComposer>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<SmsComposer>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<SmsComposer> GetAsync(Guid id)
    {
        return await RequestAsync<SmsComposer>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<SmsComposer> CreateAsync(SmsComposer input)
    {
        return await RequestAsync<SmsComposer>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SmsComposer), input }
        });
    }

    public virtual async Task<SmsComposer> UpdateAsync(Guid id, SmsComposer input)
    {
        return await RequestAsync<SmsComposer>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SmsComposer), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
