
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISnailmailLetterMissingRequiredFieldAppService), typeof(SnailmailLetterMissingRequiredFieldClientProxy))]
public partial class SnailmailLetterMissingRequiredFieldClientProxy : ClientProxyBase<ISnailmailLetterMissingRequiredFieldAppService>, ISnailmailLetterMissingRequiredFieldAppService
{
    //public virtual async Task<ListResultDto<SnailmailLetterMissingRequiredField>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<SnailmailLetterMissingRequiredField>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<SnailmailLetterMissingRequiredField>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<SnailmailLetterMissingRequiredField>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<SnailmailLetterMissingRequiredField> GetAsync(Guid id)
    {
        return await RequestAsync<SnailmailLetterMissingRequiredField>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<SnailmailLetterMissingRequiredField> CreateAsync(SnailmailLetterMissingRequiredField input)
    {
        return await RequestAsync<SnailmailLetterMissingRequiredField>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SnailmailLetterMissingRequiredField), input }
        });
    }

    public virtual async Task<SnailmailLetterMissingRequiredField> UpdateAsync(Guid id, SnailmailLetterMissingRequiredField input)
    {
        return await RequestAsync<SnailmailLetterMissingRequiredField>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SnailmailLetterMissingRequiredField), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
