
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStockTrackLineAppService), typeof(StockTrackLineClientProxy))]
public partial class StockTrackLineClientProxy : ClientProxyBase<IStockTrackLineAppService>, IStockTrackLineAppService
{
    //public virtual async Task<ListResultDto<StockTrackLine>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<StockTrackLine>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<StockTrackLine>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<StockTrackLine>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<StockTrackLine> GetAsync(Guid id)
    {
        return await RequestAsync<StockTrackLine>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<StockTrackLine> CreateAsync(StockTrackLine input)
    {
        return await RequestAsync<StockTrackLine>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StockTrackLine), input }
        });
    }

    public virtual async Task<StockTrackLine> UpdateAsync(Guid id, StockTrackLine input)
    {
        return await RequestAsync<StockTrackLine>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(StockTrackLine), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
