
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStockTrackConfirmationAppService), typeof(StockTrackConfirmationClientProxy))]
public partial class StockTrackConfirmationClientProxy : ClientProxyBase<IStockTrackConfirmationAppService>, IStockTrackConfirmationAppService
{
    //public virtual async Task<ListResultDto<StockTrackConfirmation>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<StockTrackConfirmation>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<StockTrackConfirmation>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<StockTrackConfirmation>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<StockTrackConfirmation> GetAsync(Guid id)
    {
        return await RequestAsync<StockTrackConfirmation>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<StockTrackConfirmation> CreateAsync(StockTrackConfirmation input)
    {
        return await RequestAsync<StockTrackConfirmation>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StockTrackConfirmation), input }
        });
    }

    public virtual async Task<StockTrackConfirmation> UpdateAsync(Guid id, StockTrackConfirmation input)
    {
        return await RequestAsync<StockTrackConfirmation>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(StockTrackConfirmation), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
