
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStockPickingTypeAppService), typeof(StockPickingTypeClientProxy))]
public partial class StockPickingTypeClientProxy : ClientProxyBase<IStockPickingTypeAppService>, IStockPickingTypeAppService
{
    //public virtual async Task<ListResultDto<StockPickingType>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<StockPickingType>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<StockPickingType>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<StockPickingType>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<StockPickingType> GetAsync(Guid id)
    {
        return await RequestAsync<StockPickingType>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<StockPickingType> CreateAsync(StockPickingType input)
    {
        return await RequestAsync<StockPickingType>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StockPickingType), input }
        });
    }

    public virtual async Task<StockPickingType> UpdateAsync(Guid id, StockPickingType input)
    {
        return await RequestAsync<StockPickingType>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(StockPickingType), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
