
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStockScrapAppService), typeof(StockScrapClientProxy))]
public partial class StockScrapClientProxy : ClientProxyBase<IStockScrapAppService>, IStockScrapAppService
{
    //public virtual async Task<ListResultDto<StockScrap>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<StockScrap>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<StockScrap>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<StockScrap>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<StockScrap> GetAsync(Guid id)
    {
        return await RequestAsync<StockScrap>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<StockScrap> CreateAsync(StockScrap input)
    {
        return await RequestAsync<StockScrap>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StockScrap), input }
        });
    }

    public virtual async Task<StockScrap> UpdateAsync(Guid id, StockScrap input)
    {
        return await RequestAsync<StockScrap>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(StockScrap), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
