
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStockRequestCountAppService), typeof(StockRequestCountClientProxy))]
public partial class StockRequestCountClientProxy : ClientProxyBase<IStockRequestCountAppService>, IStockRequestCountAppService
{
    //public virtual async Task<ListResultDto<StockRequestCount>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<StockRequestCount>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<StockRequestCount>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<StockRequestCount>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<StockRequestCount> GetAsync(Guid id)
    {
        return await RequestAsync<StockRequestCount>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<StockRequestCount> CreateAsync(StockRequestCount input)
    {
        return await RequestAsync<StockRequestCount>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StockRequestCount), input }
        });
    }

    public virtual async Task<StockRequestCount> UpdateAsync(Guid id, StockRequestCount input)
    {
        return await RequestAsync<StockRequestCount>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(StockRequestCount), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
