
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStockPackageDestinationAppService), typeof(StockPackageDestinationClientProxy))]
public partial class StockPackageDestinationClientProxy : ClientProxyBase<IStockPackageDestinationAppService>, IStockPackageDestinationAppService
{
    //public virtual async Task<ListResultDto<StockPackageDestination>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<StockPackageDestination>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<StockPackageDestination>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<StockPackageDestination>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<StockPackageDestination> GetAsync(Guid id)
    {
        return await RequestAsync<StockPackageDestination>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<StockPackageDestination> CreateAsync(StockPackageDestination input)
    {
        return await RequestAsync<StockPackageDestination>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StockPackageDestination), input }
        });
    }

    public virtual async Task<StockPackageDestination> UpdateAsync(Guid id, StockPackageDestination input)
    {
        return await RequestAsync<StockPackageDestination>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(StockPackageDestination), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
