
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWebEditorConverterTestAppService), typeof(WebEditorConverterTestClientProxy))]
public partial class WebEditorConverterTestClientProxy : ClientProxyBase<IWebEditorConverterTestAppService>, IWebEditorConverterTestAppService
{
    //public virtual async Task<ListResultDto<WebEditorConverterTest>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<WebEditorConverterTest>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<WebEditorConverterTest>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<WebEditorConverterTest>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<WebEditorConverterTest> GetAsync(Guid id)
    {
        return await RequestAsync<WebEditorConverterTest>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WebEditorConverterTest> CreateAsync(WebEditorConverterTest input)
    {
        return await RequestAsync<WebEditorConverterTest>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WebEditorConverterTest), input }
        });
    }

    public virtual async Task<WebEditorConverterTest> UpdateAsync(Guid id, WebEditorConverterTest input)
    {
        return await RequestAsync<WebEditorConverterTest>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(WebEditorConverterTest), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
