
// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;

using Bamboo.Core.Models;
using Bamboo.Core.Services;

// ReSharper disable once CheckNamespace
namespace Bamboo.Core.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWebsiteVisitorAppService), typeof(WebsiteVisitorClientProxy))]
public partial class WebsiteVisitorClientProxy : ClientProxyBase<IWebsiteVisitorAppService>, IWebsiteVisitorAppService
{
    //public virtual async Task<ListResultDto<WebsiteVisitor>> GetAllListAsync()
    //{
    //    return await RequestAsync<ListResultDto<WebsiteVisitor>>(nameof(GetAllListAsync));
    //}

    public virtual async Task<PagedResultDto<WebsiteVisitor>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<WebsiteVisitor>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<WebsiteVisitor> GetAsync(Guid id)
    {
        return await RequestAsync<WebsiteVisitor>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WebsiteVisitor> CreateAsync(WebsiteVisitor input)
    {
        return await RequestAsync<WebsiteVisitor>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WebsiteVisitor), input }
        });
    }

    public virtual async Task<WebsiteVisitor> UpdateAsync(Guid id, WebsiteVisitor input)
    {
        return await RequestAsync<WebsiteVisitor>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(WebsiteVisitor), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
