// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MaintenanceRequestMessageNewRequestDto
    {
        public object MsgDict { get; set; }
        public object CustomValues { get; set; }
    }
}