// Auto-generated by C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MrpBomExplodeRequestDto
    {
        public Guid[]? Ids { get; set; }
        public object? Product { get; set; }
        public object? Quantity { get; set; }
        public object? PickingType { get; set; }
        public object? NeverAttributeValues { get; set; }
    }
}