// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class MrpWorkorderButtonStartRequestDto
    {
        public object RaiseOnInvalidState { get; set; }
    }
    
    public class MrpWorkorderEndPreviousRequestDto
    {
        public object Doall { get; set; }
    }
    
    public class MrpWorkorderSetStateRequestDto
    {
        public object State { get; set; }
    }
}