// Auto-generated by Odoo C# Code Generator
using System;
using System.Collections.Generic;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class StockPickingAddEntirePacksRequestDto
    {
        public List<Guid> PackageIds { get; set; }
    }
    
    public class StockPickingAssignBatchUserRequestDto
    {
        public Guid UserId { get; set; }
    }
    
    public class StockPickingCalculateDateCategoryRequestDto
    {
        public object Datetime { get; set; }
    }
    
    public class StockPickingDateCategoryToDomainRequestDto
    {
        public object FieldName { get; set; }
        public object DateCategory { get; set; }
    }
    
    public class StockPickingGetEmptyListHelpRequestDto
    {
        public object HelpMessage { get; set; }
    }
}