// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts.Interfaces;
using System.Collections.Generic;
using System;

namespace Bamboo.Core.Application.Contracts.DTOs
{
    public class StockMoveLineGetMoveLineQuantMatchRequestDto
    {
        public Guid[]? Ids { get; set; }
        public Guid? MoveId { get; set; }
        public List<Guid>? DirtyMoveLineIds { get; set; }
        public List<Guid>? DirtyQuantIds { get; set; }
    }
}