// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IMailGroupAppService : IGenericApplicationService<MailGroup>
    {
        Task<MailGroup> GoToWebsiteAsync(Guid id);
        Task<MailGroup> JoinAsync(Guid id);
        Task<MailGroup> LeaveAsync(Guid id);
        Task<MailGroup> MessageNewAsync(Guid id, object msg_dict, object custom_values);
        Task<MailGroup> MessagePostAsync(Guid id, object body, object subject, object email_from, Guid author_id);
        Task<MailGroup> MessageUpdateAsync(Guid id, object msg_dict, object update_vals);
        Task<MailGroup> SendGuidelinesAsync(Guid id, object members);
    }
}