// Auto-generated by Odoo C# Code Generator
using Bamboo.Core.Application.Contracts;
using Bamboo.Core.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Volo.Abp.Application.Services;
namespace Bamboo.Core.Application.Contracts.Interfaces
{
    public interface IMrpRoutingWorkcenterAppService : IGenericApplicationService<MrpRoutingWorkcenter>
    {
        Task<MrpRoutingWorkcenter> ArchiveAsync(Guid id);
        Task<MrpRoutingWorkcenter> CopyExistingOperationsAsync(Guid id);
        Task<MrpRoutingWorkcenter> CopyToBomAsync(Guid id);
        Task<MrpRoutingWorkcenter> UnarchiveAsync(Guid id);
    }
}